# Auto-generated type stubs for win32more
# Generated by winui3/tools/generate_win32more_stubs.py
# Property types are typed as Any; the goal is attribute existence,
# not full type safety for win32more internals.

from typing import Any

from win32more.Microsoft.UI.Xaml import DependencyObject

class AcrylicBrush(XamlCompositionBrushBase):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    AlwaysUseFallback: Any
    TintColor: Any
    TintLuminosityOpacity: Any
    TintOpacity: Any
    TintTransitionDuration: Any
    AlwaysUseFallbackProperty: Any
    TintColorProperty: Any
    TintLuminosityOpacityProperty: Any
    TintOpacityProperty: Any
    TintTransitionDurationProperty: Any

class AlignmentX(int):
    Left: int
    Center: int
    Right: int

class AlignmentY(int):
    Top: int
    Center: int
    Bottom: int

class ArcSegment(PathSegment):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    IsLargeArc: Any
    Point: Any
    RotationAngle: Any
    Size: Any
    SweepDirection: Any
    IsLargeArcProperty: Any
    PointProperty: Any
    RotationAngleProperty: Any
    SizeProperty: Any
    SweepDirectionProperty: Any

class BezierSegment(PathSegment):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Point1: Any
    Point2: Any
    Point3: Any
    Point1Property: Any
    Point2Property: Any
    Point3Property: Any

class BitmapCache(CacheMode):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class Brush(DependencyObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Opacity: Any
    RelativeTransform: Any
    Transform: Any
    OpacityProperty: Any
    RelativeTransformProperty: Any
    TransformProperty: Any
    def PopulatePropertyInfoOverride(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def PopulatePropertyInfo(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class BrushCollection:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any
    def GetAt(self, _p0: Any = ...) -> Any: ...
    def GetView(self) -> Any: ...
    def IndexOf(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def SetAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def InsertAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def RemoveAt(self, _p0: Any = ...) -> Any: ...
    def Append(self, _p0: Any = ...) -> Any: ...
    def RemoveAtEnd(self) -> Any: ...
    def Clear(self) -> Any: ...
    def GetMany(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def ReplaceAll(self, _p0: Any = ...) -> Any: ...
    def First(self) -> Any: ...

class BrushMappingMode(int):
    Absolute: int
    RelativeToBoundingBox: int

class CacheMode(DependencyObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class ColorInterpolationMode(int):
    ScRgbLinearInterpolation: int
    SRgbLinearInterpolation: int

class CompositeTransform(Transform):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    CenterX: Any
    CenterY: Any
    Rotation: Any
    ScaleX: Any
    ScaleY: Any
    SkewX: Any
    SkewY: Any
    TranslateX: Any
    TranslateY: Any
    CenterXProperty: Any
    CenterYProperty: Any
    RotationProperty: Any
    ScaleXProperty: Any
    ScaleYProperty: Any
    SkewXProperty: Any
    SkewYProperty: Any
    TranslateXProperty: Any
    TranslateYProperty: Any

class CompositionTarget:
    def add_Rendering(self, _p0: Any = ...) -> Any: ...
    def remove_Rendering(self, _p0: Any = ...) -> Any: ...
    def add_Rendered(self, _p0: Any = ...) -> Any: ...
    def remove_Rendered(self, _p0: Any = ...) -> Any: ...
    def add_SurfaceContentsLost(self, _p0: Any = ...) -> Any: ...
    def remove_SurfaceContentsLost(self, _p0: Any = ...) -> Any: ...
    @classmethod
    def GetCompositorForCurrentThread(cls) -> Any: ...

class DesktopAcrylicBackdrop(SystemBackdrop):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class DoubleCollection:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any
    def GetAt(self, _p0: Any = ...) -> Any: ...
    def GetView(self) -> Any: ...
    def IndexOf(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def SetAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def InsertAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def RemoveAt(self, _p0: Any = ...) -> Any: ...
    def Append(self, _p0: Any = ...) -> Any: ...
    def RemoveAtEnd(self) -> Any: ...
    def Clear(self) -> Any: ...
    def GetMany(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def ReplaceAll(self, _p0: Any = ...) -> Any: ...
    def First(self) -> Any: ...

class ElementCompositeMode(int):
    Inherit: int
    SourceOver: int
    MinBlend: int

class EllipseGeometry(Geometry):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Center: Any
    RadiusX: Any
    RadiusY: Any
    CenterProperty: Any
    RadiusXProperty: Any
    RadiusYProperty: Any

class FastPlayFallbackBehaviour(int):
    Skip: int
    Hide: int
    Disable: int

class FillRule(int):
    EvenOdd: int
    Nonzero: int

class FontFamily:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Source: Any
    XamlAutoFontFamily: Any
    @classmethod
    def CreateInstanceWithName(cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...

class GeneralTransform(DependencyObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Inverse: Any
    InverseCore: Any
    def TransformPoint(self, _p0: Any = ...) -> Any: ...
    def TryTransform(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def TransformBounds(self, _p0: Any = ...) -> Any: ...
    def TryTransformCore(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def TransformBoundsCore(self, _p0: Any = ...) -> Any: ...

class Geometry(DependencyObject):
    Bounds: Any
    Transform: Any
    Empty: Any
    StandardFlatteningTolerance: Any
    TransformProperty: Any

class GeometryCollection:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any
    def GetAt(self, _p0: Any = ...) -> Any: ...
    def GetView(self) -> Any: ...
    def IndexOf(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def SetAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def InsertAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def RemoveAt(self, _p0: Any = ...) -> Any: ...
    def Append(self, _p0: Any = ...) -> Any: ...
    def RemoveAtEnd(self) -> Any: ...
    def Clear(self) -> Any: ...
    def GetMany(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def ReplaceAll(self, _p0: Any = ...) -> Any: ...
    def First(self) -> Any: ...

class GeometryGroup(Geometry):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Children: Any
    FillRule: Any
    ChildrenProperty: Any
    FillRuleProperty: Any

class GradientBrush(Brush):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    ColorInterpolationMode: Any
    GradientStops: Any
    MappingMode: Any
    SpreadMethod: Any
    ColorInterpolationModeProperty: Any
    GradientStopsProperty: Any
    MappingModeProperty: Any
    SpreadMethodProperty: Any

class GradientSpreadMethod(int):
    Pad: int
    Reflect: int
    Repeat: int

class GradientStop(DependencyObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Color: Any
    Offset: Any
    ColorProperty: Any
    OffsetProperty: Any

class GradientStopCollection:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any
    def GetAt(self, _p0: Any = ...) -> Any: ...
    def GetView(self) -> Any: ...
    def IndexOf(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def SetAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def InsertAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def RemoveAt(self, _p0: Any = ...) -> Any: ...
    def Append(self, _p0: Any = ...) -> Any: ...
    def RemoveAtEnd(self) -> Any: ...
    def Clear(self) -> Any: ...
    def GetMany(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def ReplaceAll(self, _p0: Any = ...) -> Any: ...
    def First(self) -> Any: ...

class IAcrylicBrush:
    AlwaysUseFallback: Any
    TintColor: Any
    TintOpacity: Any
    TintTransitionDuration: Any

class IAcrylicBrush2:
    TintLuminosityOpacity: Any

class IAcrylicBrushStatics:
    AlwaysUseFallbackProperty: Any
    TintColorProperty: Any
    TintOpacityProperty: Any
    TintTransitionDurationProperty: Any

class IAcrylicBrushStatics2:
    TintLuminosityOpacityProperty: Any

class IArcSegment:
    IsLargeArc: Any
    Point: Any
    RotationAngle: Any
    Size: Any
    SweepDirection: Any

class IArcSegmentStatics:
    IsLargeArcProperty: Any
    PointProperty: Any
    RotationAngleProperty: Any
    SizeProperty: Any
    SweepDirectionProperty: Any

class IBezierSegment:
    Point1: Any
    Point2: Any
    Point3: Any

class IBezierSegmentStatics:
    Point1Property: Any
    Point2Property: Any
    Point3Property: Any

class IBrush:
    Opacity: Any
    RelativeTransform: Any
    Transform: Any

class IBrushStatics:
    OpacityProperty: Any
    RelativeTransformProperty: Any
    TransformProperty: Any

class ICompositeTransform:
    CenterX: Any
    CenterY: Any
    Rotation: Any
    ScaleX: Any
    ScaleY: Any
    SkewX: Any
    SkewY: Any
    TranslateX: Any
    TranslateY: Any

class ICompositeTransformStatics:
    CenterXProperty: Any
    CenterYProperty: Any
    RotationProperty: Any
    ScaleXProperty: Any
    ScaleYProperty: Any
    SkewXProperty: Any
    SkewYProperty: Any
    TranslateXProperty: Any
    TranslateYProperty: Any

class IEllipseGeometry:
    Center: Any
    RadiusX: Any
    RadiusY: Any

class IEllipseGeometryStatics:
    CenterProperty: Any
    RadiusXProperty: Any
    RadiusYProperty: Any

class IFontFamily:
    Source: Any

class IFontFamilyStatics:
    XamlAutoFontFamily: Any

class IGeneralTransform:
    Inverse: Any
    def TransformPoint(self, _p0: Any = ...) -> Any: ...
    def TryTransform(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def TransformBounds(self, _p0: Any = ...) -> Any: ...

class IGeneralTransformOverrides:
    InverseCore: Any
    def TryTransformCore(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def TransformBoundsCore(self, _p0: Any = ...) -> Any: ...

class IGeometry:
    Bounds: Any
    Transform: Any

class IGeometryGroup:
    Children: Any
    FillRule: Any

class IGeometryGroupStatics:
    ChildrenProperty: Any
    FillRuleProperty: Any

class IGeometryStatics:
    Empty: Any
    StandardFlatteningTolerance: Any
    TransformProperty: Any

class IGradientBrush:
    ColorInterpolationMode: Any
    GradientStops: Any
    MappingMode: Any
    SpreadMethod: Any

class IGradientBrushStatics:
    ColorInterpolationModeProperty: Any
    GradientStopsProperty: Any
    MappingModeProperty: Any
    SpreadMethodProperty: Any

class IGradientStop:
    Color: Any
    Offset: Any

class IGradientStopStatics:
    ColorProperty: Any
    OffsetProperty: Any

class IImageBrush:
    ImageSource: Any
    ImageFailed: Any
    ImageOpened: Any
    def add_ImageFailed(self, _p0: Any = ...) -> Any: ...
    def remove_ImageFailed(self, _p0: Any = ...) -> Any: ...
    def add_ImageOpened(self, _p0: Any = ...) -> Any: ...
    def remove_ImageOpened(self, _p0: Any = ...) -> Any: ...

class IImageBrushStatics:
    ImageSourceProperty: Any

class ILineGeometry:
    EndPoint: Any
    StartPoint: Any

class ILineGeometryStatics:
    EndPointProperty: Any
    StartPointProperty: Any

class ILineSegment:
    Point: Any

class ILineSegmentStatics:
    PointProperty: Any

class ILinearGradientBrush:
    EndPoint: Any
    StartPoint: Any

class ILinearGradientBrushStatics:
    EndPointProperty: Any
    StartPointProperty: Any

class ILoadedImageSourceLoadCompletedEventArgs:
    Status: Any

class ILoadedImageSurface:
    DecodedPhysicalSize: Any
    DecodedSize: Any
    NaturalSize: Any
    LoadCompleted: Any
    def add_LoadCompleted(self, _p0: Any = ...) -> Any: ...
    def remove_LoadCompleted(self, _p0: Any = ...) -> Any: ...

class IMatrix3DProjection:
    ProjectionMatrix: Any

class IMatrix3DProjectionStatics:
    ProjectionMatrixProperty: Any

class IMatrixHelperStatics:
    Identity: Any
    def FromElements(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ..., _p4: Any = ..., _p5: Any = ...) -> Any: ...
    def GetIsIdentity(self, _p0: Any = ...) -> Any: ...
    def Transform(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class IMatrixTransform:
    Matrix: Any

class IMatrixTransformStatics:
    MatrixProperty: Any

class IMicaBackdrop:
    Kind: Any

class IMicaBackdropStatics:
    KindProperty: Any

class IPathFigure:
    IsClosed: Any
    IsFilled: Any
    Segments: Any
    StartPoint: Any

class IPathFigureStatics:
    IsClosedProperty: Any
    IsFilledProperty: Any
    SegmentsProperty: Any
    StartPointProperty: Any

class IPathGeometry:
    Figures: Any
    FillRule: Any

class IPathGeometryStatics:
    FiguresProperty: Any
    FillRuleProperty: Any

class IPlaneProjection:
    CenterOfRotationX: Any
    CenterOfRotationY: Any
    CenterOfRotationZ: Any
    GlobalOffsetX: Any
    GlobalOffsetY: Any
    GlobalOffsetZ: Any
    LocalOffsetX: Any
    LocalOffsetY: Any
    LocalOffsetZ: Any
    ProjectionMatrix: Any
    RotationX: Any
    RotationY: Any
    RotationZ: Any

class IPlaneProjectionStatics:
    CenterOfRotationXProperty: Any
    CenterOfRotationYProperty: Any
    CenterOfRotationZProperty: Any
    GlobalOffsetXProperty: Any
    GlobalOffsetYProperty: Any
    GlobalOffsetZProperty: Any
    LocalOffsetXProperty: Any
    LocalOffsetYProperty: Any
    LocalOffsetZProperty: Any
    ProjectionMatrixProperty: Any
    RotationXProperty: Any
    RotationYProperty: Any
    RotationZProperty: Any

class IPolyBezierSegment:
    Points: Any

class IPolyBezierSegmentStatics:
    PointsProperty: Any

class IPolyLineSegment:
    Points: Any

class IPolyLineSegmentStatics:
    PointsProperty: Any

class IPolyQuadraticBezierSegment:
    Points: Any

class IPolyQuadraticBezierSegmentStatics:
    PointsProperty: Any

class IQuadraticBezierSegment:
    Point1: Any
    Point2: Any

class IQuadraticBezierSegmentStatics:
    Point1Property: Any
    Point2Property: Any

class IRadialGradientBrush:
    Center: Any
    GradientOrigin: Any
    GradientStops: Any
    InterpolationSpace: Any
    MappingMode: Any
    RadiusX: Any
    RadiusY: Any
    SpreadMethod: Any

class IRadialGradientBrushStatics:
    CenterProperty: Any
    GradientOriginProperty: Any
    InterpolationSpaceProperty: Any
    MappingModeProperty: Any
    RadiusXProperty: Any
    RadiusYProperty: Any
    SpreadMethodProperty: Any

class IRectangleGeometry:
    Rect: Any

class IRectangleGeometryStatics:
    RectProperty: Any

class IRenderedEventArgs:
    FrameDuration: Any

class IRenderingEventArgs:
    RenderingTime: Any

class IRotateTransform:
    Angle: Any
    CenterX: Any
    CenterY: Any

class IRotateTransformStatics:
    AngleProperty: Any
    CenterXProperty: Any
    CenterYProperty: Any

class IScaleTransform:
    CenterX: Any
    CenterY: Any
    ScaleX: Any
    ScaleY: Any

class IScaleTransformStatics:
    CenterXProperty: Any
    CenterYProperty: Any
    ScaleXProperty: Any
    ScaleYProperty: Any

class ISkewTransform:
    AngleX: Any
    AngleY: Any
    CenterX: Any
    CenterY: Any

class ISkewTransformStatics:
    AngleXProperty: Any
    AngleYProperty: Any
    CenterXProperty: Any
    CenterYProperty: Any

class ISolidColorBrush:
    Color: Any

class ISolidColorBrushStatics:
    ColorProperty: Any

class IThemeShadow:
    Receivers: Any

class ITileBrush:
    AlignmentX: Any
    AlignmentY: Any
    Stretch: Any

class ITileBrushStatics:
    AlignmentXProperty: Any
    AlignmentYProperty: Any
    StretchProperty: Any

class ITransformGroup:
    Children: Any
    Value: Any

class ITransformGroupStatics:
    ChildrenProperty: Any

class ITranslateTransform:
    X: Any
    Y: Any

class ITranslateTransformStatics:
    XProperty: Any
    YProperty: Any

class IXamlCompositionBrushBase:
    FallbackColor: Any

class IXamlCompositionBrushBaseProtected:
    CompositionBrush: Any

class IXamlCompositionBrushBaseStatics:
    FallbackColorProperty: Any

class IXamlLightProtected:
    CompositionLight: Any

class ImageBrush(TileBrush):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    ImageSource: Any
    ImageFailed: Any
    ImageOpened: Any
    ImageSourceProperty: Any
    def add_ImageFailed(self, _p0: Any = ...) -> Any: ...
    def remove_ImageFailed(self, _p0: Any = ...) -> Any: ...
    def add_ImageOpened(self, _p0: Any = ...) -> Any: ...
    def remove_ImageOpened(self, _p0: Any = ...) -> Any: ...

class ImageSource(DependencyObject):
    ...

class LineGeometry(Geometry):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    EndPoint: Any
    StartPoint: Any
    EndPointProperty: Any
    StartPointProperty: Any

class LineSegment(PathSegment):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Point: Any
    PointProperty: Any

class LinearGradientBrush(GradientBrush):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    EndPoint: Any
    StartPoint: Any
    EndPointProperty: Any
    StartPointProperty: Any
    @classmethod
    def CreateInstanceWithGradientStopCollectionAndAngle(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class LoadedImageSourceLoadCompletedEventArgs:
    Status: Any

class LoadedImageSourceLoadStatus(int):
    Success: int
    NetworkError: int
    InvalidFormat: int
    Other: int

class LoadedImageSurface:
    DecodedPhysicalSize: Any
    DecodedSize: Any
    NaturalSize: Any
    LoadCompleted: Any
    def add_LoadCompleted(self, _p0: Any = ...) -> Any: ...
    def remove_LoadCompleted(self, _p0: Any = ...) -> Any: ...
    def Close(self) -> Any: ...
    @classmethod
    def StartLoadFromUriWithSize(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def StartLoadFromUri(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def StartLoadFromStreamWithSize(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def StartLoadFromStream(cls, _p0: Any = ...) -> Any: ...

class Matrix:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    M11: Any
    M12: Any
    M21: Any
    M22: Any
    OffsetX: Any
    OffsetY: Any

class Matrix3DProjection(Projection):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    ProjectionMatrix: Any
    ProjectionMatrixProperty: Any

class MatrixHelper:
    Identity: Any
    @classmethod
    def FromElements(cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ..., _p4: Any = ..., _p5: Any = ...) -> Any: ...
    @classmethod
    def GetIsIdentity(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def Transform(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class MatrixTransform(Transform):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Matrix: Any
    MatrixProperty: Any

class MediaTransportControlsThumbnailRequestedEventArgs:
    def SetThumbnailImage(self, _p0: Any = ...) -> Any: ...
    def GetDeferral(self) -> Any: ...

class MicaBackdrop(SystemBackdrop):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Kind: Any
    KindProperty: Any

class PathFigure(DependencyObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    IsClosed: Any
    IsFilled: Any
    Segments: Any
    StartPoint: Any
    IsClosedProperty: Any
    IsFilledProperty: Any
    SegmentsProperty: Any
    StartPointProperty: Any

class PathFigureCollection:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any
    def GetAt(self, _p0: Any = ...) -> Any: ...
    def GetView(self) -> Any: ...
    def IndexOf(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def SetAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def InsertAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def RemoveAt(self, _p0: Any = ...) -> Any: ...
    def Append(self, _p0: Any = ...) -> Any: ...
    def RemoveAtEnd(self) -> Any: ...
    def Clear(self) -> Any: ...
    def GetMany(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def ReplaceAll(self, _p0: Any = ...) -> Any: ...
    def First(self) -> Any: ...

class PathGeometry(Geometry):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Figures: Any
    FillRule: Any
    FiguresProperty: Any
    FillRuleProperty: Any

class PathSegment(DependencyObject):
    ...

class PathSegmentCollection:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any
    def GetAt(self, _p0: Any = ...) -> Any: ...
    def GetView(self) -> Any: ...
    def IndexOf(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def SetAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def InsertAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def RemoveAt(self, _p0: Any = ...) -> Any: ...
    def Append(self, _p0: Any = ...) -> Any: ...
    def RemoveAtEnd(self) -> Any: ...
    def Clear(self) -> Any: ...
    def GetMany(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def ReplaceAll(self, _p0: Any = ...) -> Any: ...
    def First(self) -> Any: ...

class PenLineCap(int):
    Flat: int
    Square: int
    Round: int
    Triangle: int

class PenLineJoin(int):
    Miter: int
    Bevel: int
    Round: int

class PlaneProjection(Projection):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    CenterOfRotationX: Any
    CenterOfRotationY: Any
    CenterOfRotationZ: Any
    GlobalOffsetX: Any
    GlobalOffsetY: Any
    GlobalOffsetZ: Any
    LocalOffsetX: Any
    LocalOffsetY: Any
    LocalOffsetZ: Any
    ProjectionMatrix: Any
    RotationX: Any
    RotationY: Any
    RotationZ: Any
    CenterOfRotationXProperty: Any
    CenterOfRotationYProperty: Any
    CenterOfRotationZProperty: Any
    GlobalOffsetXProperty: Any
    GlobalOffsetYProperty: Any
    GlobalOffsetZProperty: Any
    LocalOffsetXProperty: Any
    LocalOffsetYProperty: Any
    LocalOffsetZProperty: Any
    ProjectionMatrixProperty: Any
    RotationXProperty: Any
    RotationYProperty: Any
    RotationZProperty: Any

class PointCollection:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any
    def GetAt(self, _p0: Any = ...) -> Any: ...
    def GetView(self) -> Any: ...
    def IndexOf(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def SetAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def InsertAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def RemoveAt(self, _p0: Any = ...) -> Any: ...
    def Append(self, _p0: Any = ...) -> Any: ...
    def RemoveAtEnd(self) -> Any: ...
    def Clear(self) -> Any: ...
    def GetMany(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def ReplaceAll(self, _p0: Any = ...) -> Any: ...
    def First(self) -> Any: ...

class PolyBezierSegment(PathSegment):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Points: Any
    PointsProperty: Any

class PolyLineSegment(PathSegment):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Points: Any
    PointsProperty: Any

class PolyQuadraticBezierSegment(PathSegment):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Points: Any
    PointsProperty: Any

class Projection(DependencyObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class QuadraticBezierSegment(PathSegment):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Point1: Any
    Point2: Any
    Point1Property: Any
    Point2Property: Any

class RadialGradientBrush(XamlCompositionBrushBase):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Center: Any
    GradientOrigin: Any
    GradientStops: Any
    InterpolationSpace: Any
    MappingMode: Any
    RadiusX: Any
    RadiusY: Any
    SpreadMethod: Any
    CenterProperty: Any
    GradientOriginProperty: Any
    InterpolationSpaceProperty: Any
    MappingModeProperty: Any
    RadiusXProperty: Any
    RadiusYProperty: Any
    SpreadMethodProperty: Any

class RectangleGeometry(Geometry):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Rect: Any
    RectProperty: Any

class RenderedEventArgs:
    FrameDuration: Any

class RenderingEventArgs:
    RenderingTime: Any

class RotateTransform(Transform):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Angle: Any
    CenterX: Any
    CenterY: Any
    AngleProperty: Any
    CenterXProperty: Any
    CenterYProperty: Any

class ScaleTransform(Transform):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    CenterX: Any
    CenterY: Any
    ScaleX: Any
    ScaleY: Any
    CenterXProperty: Any
    CenterYProperty: Any
    ScaleXProperty: Any
    ScaleYProperty: Any

class Shadow(DependencyObject):
    ...

class SkewTransform(Transform):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    AngleX: Any
    AngleY: Any
    CenterX: Any
    CenterY: Any
    AngleXProperty: Any
    AngleYProperty: Any
    CenterXProperty: Any
    CenterYProperty: Any

class SolidColorBrush(Brush):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Color: Any
    ColorProperty: Any
    @classmethod
    def CreateInstanceWithColor(cls, _p0: Any = ...) -> Any: ...

class Stretch(int):
    None_: int
    Fill: int
    Uniform: int
    UniformToFill: int

class StyleSimulations(int):
    None_: int
    BoldSimulation: int
    ItalicSimulation: int
    BoldItalicSimulation: int

class SweepDirection(int):
    Counterclockwise: int
    Clockwise: int

class SystemBackdrop(DependencyObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def GetDefaultSystemBackdropConfiguration(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def OnTargetConnected(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def OnTargetDisconnected(self, _p0: Any = ...) -> Any: ...
    def OnDefaultSystemBackdropConfigurationChanged(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class ThemeShadow(Shadow):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Receivers: Any

class TileBrush(Brush):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    AlignmentX: Any
    AlignmentY: Any
    Stretch: Any
    AlignmentXProperty: Any
    AlignmentYProperty: Any
    StretchProperty: Any

class Transform(GeneralTransform):
    ...

class TransformCollection:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any
    def GetAt(self, _p0: Any = ...) -> Any: ...
    def GetView(self) -> Any: ...
    def IndexOf(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def SetAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def InsertAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def RemoveAt(self, _p0: Any = ...) -> Any: ...
    def Append(self, _p0: Any = ...) -> Any: ...
    def RemoveAtEnd(self) -> Any: ...
    def Clear(self) -> Any: ...
    def GetMany(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def ReplaceAll(self, _p0: Any = ...) -> Any: ...
    def First(self) -> Any: ...

class TransformGroup(Transform):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Children: Any
    Value: Any
    ChildrenProperty: Any

class TranslateTransform(Transform):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    X: Any
    Y: Any
    XProperty: Any
    YProperty: Any

class VisualTreeHelper:
    @classmethod
    def FindElementsInHostCoordinatesPoint(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def FindElementsInHostCoordinatesRect(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def FindAllElementsInHostCoordinatesPoint(cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    @classmethod
    def FindAllElementsInHostCoordinatesRect(cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    @classmethod
    def GetChild(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def GetChildrenCount(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def GetParent(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def DisconnectChildrenRecursive(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def GetOpenPopups(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def GetOpenPopupsForXamlRoot(cls, _p0: Any = ...) -> Any: ...

class XamlCompositionBrushBase(Brush):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    CompositionBrush: Any
    FallbackColor: Any
    FallbackColorProperty: Any
    def OnConnected(self) -> Any: ...
    def OnDisconnected(self) -> Any: ...

class XamlLight(DependencyObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    CompositionLight: Any
    def GetId(self) -> Any: ...
    def OnConnected(self, _p0: Any = ...) -> Any: ...
    def OnDisconnected(self, _p0: Any = ...) -> Any: ...
    @classmethod
    def AddTargetElement(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def RemoveTargetElement(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def AddTargetBrush(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def RemoveTargetBrush(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
