# Auto-generated type stubs for win32more
# Generated by winui3/tools/generate_win32more_stubs.py
# Property types are typed as Any; the goal is attribute existence,
# not full type safety for win32more internals.

from typing import Any

from win32more.Microsoft.UI.Xaml import DependencyObject, FrameworkElement, RoutedEventArgs
from win32more.Microsoft.UI.Xaml.Controls import Canvas, CommandBar, ContentControl, ContentPresenter, Control, Grid, ItemsControl, ListView, NonVirtualizingLayout, Panel, Slider, VirtualizingPanel

class AnimationDirection(int):
    Left: int
    Top: int
    Right: int
    Bottom: int

class AppBarButtonTemplateSettings(DependencyObject):
    KeyboardAcceleratorTextMinWidth: Any

class AppBarTemplateSettings(DependencyObject):
    ClipRect: Any
    CompactRootMargin: Any
    CompactVerticalDelta: Any
    HiddenRootMargin: Any
    HiddenVerticalDelta: Any
    MinimalRootMargin: Any
    MinimalVerticalDelta: Any
    NegativeCompactVerticalDelta: Any
    NegativeHiddenVerticalDelta: Any
    NegativeMinimalVerticalDelta: Any

class AppBarToggleButtonTemplateSettings(DependencyObject):
    KeyboardAcceleratorTextMinWidth: Any

class AutoSuggestBoxHelper:
    KeepInteriorCornersSquareProperty: Any
    @classmethod
    def SetKeepInteriorCornersSquare(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def GetKeepInteriorCornersSquare(cls, _p0: Any = ...) -> Any: ...

class ButtonBase(ContentControl):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    ClickMode: Any
    Command: Any
    CommandParameter: Any
    IsPointerOver: Any
    IsPressed: Any
    Click: Any
    ClickModeProperty: Any
    CommandParameterProperty: Any
    CommandProperty: Any
    IsPointerOverProperty: Any
    IsPressedProperty: Any
    def add_Click(self, _p0: Any = ...) -> Any: ...
    def remove_Click(self, _p0: Any = ...) -> Any: ...

class CalendarPanel(Panel):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class CalendarViewTemplateSettings(DependencyObject):
    CenterX: Any
    CenterY: Any
    ClipRect: Any
    HasMoreContentAfter: Any
    HasMoreContentBefore: Any
    HasMoreViews: Any
    HeaderText: Any
    MinViewWidth: Any
    WeekDay1: Any
    WeekDay2: Any
    WeekDay3: Any
    WeekDay4: Any
    WeekDay5: Any
    WeekDay6: Any
    WeekDay7: Any

class CarouselPanel(VirtualizingPanel):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    AreHorizontalSnapPointsRegular: Any
    AreVerticalSnapPointsRegular: Any
    CanHorizontallyScroll: Any
    CanVerticallyScroll: Any
    ExtentHeight: Any
    ExtentWidth: Any
    HorizontalOffset: Any
    ScrollOwner: Any
    VerticalOffset: Any
    ViewportHeight: Any
    ViewportWidth: Any
    HorizontalSnapPointsChanged: Any
    VerticalSnapPointsChanged: Any
    def LineUp(self) -> Any: ...
    def LineDown(self) -> Any: ...
    def LineLeft(self) -> Any: ...
    def LineRight(self) -> Any: ...
    def PageUp(self) -> Any: ...
    def PageDown(self) -> Any: ...
    def PageLeft(self) -> Any: ...
    def PageRight(self) -> Any: ...
    def MouseWheelUp(self) -> Any: ...
    def MouseWheelDown(self) -> Any: ...
    def MouseWheelLeft(self) -> Any: ...
    def MouseWheelRight(self) -> Any: ...
    def SetHorizontalOffset(self, _p0: Any = ...) -> Any: ...
    def SetVerticalOffset(self, _p0: Any = ...) -> Any: ...
    def MakeVisible(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def add_HorizontalSnapPointsChanged(self, _p0: Any = ...) -> Any: ...
    def remove_HorizontalSnapPointsChanged(self, _p0: Any = ...) -> Any: ...
    def add_VerticalSnapPointsChanged(self, _p0: Any = ...) -> Any: ...
    def remove_VerticalSnapPointsChanged(self, _p0: Any = ...) -> Any: ...
    def GetIrregularSnapPoints(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetRegularSnapPoints(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...

class ColorPickerSlider(Slider):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    ColorChannel: Any
    ColorChannelProperty: Any

class ColorSpectrum(Control):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Color: Any
    Components: Any
    HsvColor: Any
    MaxHue: Any
    MaxSaturation: Any
    MaxValue: Any
    MinHue: Any
    MinSaturation: Any
    MinValue: Any
    Shape: Any
    ColorChanged: Any
    ColorProperty: Any
    ComponentsProperty: Any
    HsvColorProperty: Any
    MaxHueProperty: Any
    MaxSaturationProperty: Any
    MaxValueProperty: Any
    MinHueProperty: Any
    MinSaturationProperty: Any
    MinValueProperty: Any
    ShapeProperty: Any
    def add_ColorChanged(self, _p0: Any = ...) -> Any: ...
    def remove_ColorChanged(self, _p0: Any = ...) -> Any: ...

class ColumnMajorUniformToLargestGridLayout(NonVirtualizingLayout):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    ColumnSpacing: Any
    MaxColumns: Any
    RowSpacing: Any
    ColumnSpacingProperty: Any
    MaxColumnsProperty: Any
    RowSpacingProperty: Any

class ComboBoxHelper:
    KeepInteriorCornersSquareProperty: Any
    @classmethod
    def SetKeepInteriorCornersSquare(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def GetKeepInteriorCornersSquare(cls, _p0: Any = ...) -> Any: ...

class ComboBoxTemplateSettings(DependencyObject):
    DropDownClosedHeight: Any
    DropDownContentMinWidth: Any
    DropDownOffset: Any
    DropDownOpenedHeight: Any
    SelectedItemDirection: Any

class CommandBarFlyoutCommandBar(CommandBar):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    FlyoutTemplateSettings: Any
    SystemBackdrop: Any
    SystemBackdropProperty: Any

class CommandBarFlyoutCommandBarAutomationProperties:
    ControlTypeProperty: Any
    @classmethod
    def GetControlType(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def SetControlType(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class CommandBarFlyoutCommandBarTemplateSettings(DependencyObject):
    CloseAnimationEndPosition: Any
    ContentClipRect: Any
    CurrentWidth: Any
    ExpandDownAnimationEndPosition: Any
    ExpandDownAnimationHoldPosition: Any
    ExpandDownAnimationStartPosition: Any
    ExpandDownOverflowVerticalPosition: Any
    ExpandUpAnimationEndPosition: Any
    ExpandUpAnimationHoldPosition: Any
    ExpandUpAnimationStartPosition: Any
    ExpandUpOverflowVerticalPosition: Any
    ExpandedWidth: Any
    OpenAnimationEndPosition: Any
    OpenAnimationStartPosition: Any
    OverflowContentClipRect: Any
    WidthExpansionAnimationEndPosition: Any
    WidthExpansionAnimationStartPosition: Any
    WidthExpansionDelta: Any
    WidthExpansionMoreButtonAnimationEndPosition: Any
    WidthExpansionMoreButtonAnimationStartPosition: Any

class CommandBarTemplateSettings(DependencyObject):
    ContentHeight: Any
    EffectiveOverflowButtonVisibility: Any
    NegativeOverflowContentHeight: Any
    OverflowContentClipRect: Any
    OverflowContentCompactYTranslation: Any
    OverflowContentHeight: Any
    OverflowContentHiddenYTranslation: Any
    OverflowContentHorizontalOffset: Any
    OverflowContentMaxHeight: Any
    OverflowContentMaxWidth: Any
    OverflowContentMinWidth: Any
    OverflowContentMinimalYTranslation: Any

class ComponentResourceLocation(int):
    Application: int
    Nested: int

class CornerRadiusFilterConverter(DependencyObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Filter: Any
    Scale: Any
    FilterProperty: Any
    ScaleProperty: Any
    def Convert(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...) -> Any: ...
    def ConvertBack(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...) -> Any: ...

class CornerRadiusFilterKind(int):
    None_: int
    Top: int
    Right: int
    Bottom: int
    Left: int
    TopLeftValue: int
    BottomRightValue: int

class CornerRadiusToThicknessConverter(DependencyObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    ConversionKind: Any
    Multiplier: Any
    ConversionKindProperty: Any
    MultiplierProperty: Any
    def Convert(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...) -> Any: ...
    def ConvertBack(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...) -> Any: ...

class CornerRadiusToThicknessConverterKind(int):
    FilterTopAndBottomFromLeft: int
    FilterTopAndBottomFromRight: int
    FilterLeftAndRightFromTop: int
    FilterLeftAndRightFromBottom: int
    FilterTopFromTopLeft: int
    FilterTopFromTopRight: int
    FilterRightFromTopRight: int
    FilterRightFromBottomRight: int
    FilterBottomFromBottomRight: int
    FilterBottomFromBottomLeft: int
    FilterLeftFromBottomLeft: int
    FilterLeftFromTopLeft: int

class DragCompletedEventArgs(RoutedEventArgs):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Canceled: Any
    HorizontalChange: Any
    VerticalChange: Any
    @classmethod
    def CreateInstanceWithHorizontalChangeVerticalChangeAndCanceled(cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ..., _p4: Any = ...) -> Any: ...

class DragCompletedEventHandler:
    def Invoke(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class DragDeltaEventArgs(RoutedEventArgs):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    HorizontalChange: Any
    VerticalChange: Any
    @classmethod
    def CreateInstanceWithHorizontalChangeAndVerticalChange(cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...) -> Any: ...

class DragDeltaEventHandler:
    def Invoke(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class DragStartedEventArgs(RoutedEventArgs):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    HorizontalOffset: Any
    VerticalOffset: Any
    @classmethod
    def CreateInstanceWithHorizontalOffsetAndVerticalOffset(cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...) -> Any: ...

class DragStartedEventHandler:
    def Invoke(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class EdgeTransitionLocation(int):
    Left: int
    Top: int
    Right: int
    Bottom: int

class FlyoutBase(DependencyObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    AllowFocusOnInteraction: Any
    AllowFocusWhenDisabled: Any
    AreOpenCloseAnimationsEnabled: Any
    ElementSoundMode: Any
    InputDevicePrefersPrimaryCommands: Any
    IsConstrainedToRootBounds: Any
    IsOpen: Any
    LightDismissOverlayMode: Any
    OverlayInputPassThroughElement: Any
    Placement: Any
    ShouldConstrainToRootBounds: Any
    ShowMode: Any
    SystemBackdrop: Any
    Target: Any
    XamlRoot: Any
    Closed: Any
    Closing: Any
    Opened: Any
    Opening: Any
    AllowFocusOnInteractionProperty: Any
    AllowFocusWhenDisabledProperty: Any
    AreOpenCloseAnimationsEnabledProperty: Any
    AttachedFlyoutProperty: Any
    ElementSoundModeProperty: Any
    InputDevicePrefersPrimaryCommandsProperty: Any
    IsOpenProperty: Any
    LightDismissOverlayModeProperty: Any
    OverlayInputPassThroughElementProperty: Any
    PlacementProperty: Any
    ShouldConstrainToRootBoundsProperty: Any
    ShowModeProperty: Any
    SystemBackdropProperty: Any
    TargetProperty: Any
    def add_Opened(self, _p0: Any = ...) -> Any: ...
    def remove_Opened(self, _p0: Any = ...) -> Any: ...
    def add_Closed(self, _p0: Any = ...) -> Any: ...
    def remove_Closed(self, _p0: Any = ...) -> Any: ...
    def add_Opening(self, _p0: Any = ...) -> Any: ...
    def remove_Opening(self, _p0: Any = ...) -> Any: ...
    def add_Closing(self, _p0: Any = ...) -> Any: ...
    def remove_Closing(self, _p0: Any = ...) -> Any: ...
    def ShowAt(self, _p0: Any = ...) -> Any: ...
    def ShowAtWithOptions(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def Hide(self) -> Any: ...
    def TryInvokeKeyboardAccelerator(self, _p0: Any = ...) -> Any: ...
    def CreatePresenter(self) -> Any: ...
    def OnProcessKeyboardAccelerators(self, _p0: Any = ...) -> Any: ...
    @classmethod
    def GetAttachedFlyout(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def SetAttachedFlyout(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def ShowAttachedFlyout(cls, _p0: Any = ...) -> Any: ...

class FlyoutBaseClosingEventArgs:
    Cancel: Any

class FlyoutPlacementMode(int):
    Top: int
    Bottom: int
    Left: int
    Right: int
    Full: int
    TopEdgeAlignedLeft: int
    TopEdgeAlignedRight: int
    BottomEdgeAlignedLeft: int
    BottomEdgeAlignedRight: int
    LeftEdgeAlignedTop: int
    LeftEdgeAlignedBottom: int
    RightEdgeAlignedTop: int
    RightEdgeAlignedBottom: int
    Auto: int

class FlyoutShowMode(int):
    Auto: int
    Standard: int
    Transient: int
    TransientWithDismissOnPointerMoveAway: int

class FlyoutShowOptions:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    ExclusionRect: Any
    Placement: Any
    Position: Any
    ShowMode: Any

class GeneratorDirection(int):
    Forward: int
    Backward: int

class GeneratorPosition:
    Index: Any
    Offset: Any

class GeneratorPositionHelper:
    @classmethod
    def FromIndexAndOffset(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class GridViewItemPresenter(ContentPresenter):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    CheckBrush: Any
    CheckHintBrush: Any
    CheckSelectingBrush: Any
    ContentMargin: Any
    DisabledOpacity: Any
    DragBackground: Any
    DragForeground: Any
    DragOpacity: Any
    FocusBorderBrush: Any
    GridViewItemPresenterHorizontalContentAlignment: Any
    GridViewItemPresenterPadding: Any
    GridViewItemPresenterVerticalContentAlignment: Any
    PlaceholderBackground: Any
    PointerOverBackground: Any
    PointerOverBackgroundMargin: Any
    ReorderHintOffset: Any
    SelectedBackground: Any
    SelectedBorderThickness: Any
    SelectedForeground: Any
    SelectedPointerOverBackground: Any
    SelectedPointerOverBorderBrush: Any
    SelectionCheckMarkVisualEnabled: Any
    CheckBrushProperty: Any
    CheckHintBrushProperty: Any
    CheckSelectingBrushProperty: Any
    ContentMarginProperty: Any
    DisabledOpacityProperty: Any
    DragBackgroundProperty: Any
    DragForegroundProperty: Any
    DragOpacityProperty: Any
    FocusBorderBrushProperty: Any
    GridViewItemPresenterHorizontalContentAlignmentProperty: Any
    GridViewItemPresenterPaddingProperty: Any
    GridViewItemPresenterVerticalContentAlignmentProperty: Any
    PlaceholderBackgroundProperty: Any
    PointerOverBackgroundMarginProperty: Any
    PointerOverBackgroundProperty: Any
    ReorderHintOffsetProperty: Any
    SelectedBackgroundProperty: Any
    SelectedBorderThicknessProperty: Any
    SelectedForegroundProperty: Any
    SelectedPointerOverBackgroundProperty: Any
    SelectedPointerOverBorderBrushProperty: Any
    SelectionCheckMarkVisualEnabledProperty: Any

class GridViewItemTemplateSettings(DependencyObject):
    DragItemsCount: Any

class GroupHeaderPlacement(int):
    Top: int
    Left: int

class IAppBarButtonTemplateSettings:
    KeyboardAcceleratorTextMinWidth: Any

class IAppBarTemplateSettings:
    ClipRect: Any
    CompactRootMargin: Any
    CompactVerticalDelta: Any
    HiddenRootMargin: Any
    HiddenVerticalDelta: Any
    MinimalRootMargin: Any
    MinimalVerticalDelta: Any
    NegativeCompactVerticalDelta: Any
    NegativeHiddenVerticalDelta: Any
    NegativeMinimalVerticalDelta: Any

class IAppBarToggleButtonTemplateSettings:
    KeyboardAcceleratorTextMinWidth: Any

class IAutoSuggestBoxHelperStatics:
    KeepInteriorCornersSquareProperty: Any
    def SetKeepInteriorCornersSquare(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetKeepInteriorCornersSquare(self, _p0: Any = ...) -> Any: ...

class IButtonBase:
    ClickMode: Any
    Command: Any
    CommandParameter: Any
    IsPointerOver: Any
    IsPressed: Any
    Click: Any
    def add_Click(self, _p0: Any = ...) -> Any: ...
    def remove_Click(self, _p0: Any = ...) -> Any: ...

class IButtonBaseStatics:
    ClickModeProperty: Any
    CommandParameterProperty: Any
    CommandProperty: Any
    IsPointerOverProperty: Any
    IsPressedProperty: Any

class ICalendarViewTemplateSettings:
    CenterX: Any
    CenterY: Any
    ClipRect: Any
    HasMoreContentAfter: Any
    HasMoreContentBefore: Any
    HasMoreViews: Any
    HeaderText: Any
    MinViewWidth: Any
    WeekDay1: Any
    WeekDay2: Any
    WeekDay3: Any
    WeekDay4: Any
    WeekDay5: Any
    WeekDay6: Any
    WeekDay7: Any

class ICarouselPanel:
    CanHorizontallyScroll: Any
    CanVerticallyScroll: Any
    ExtentHeight: Any
    ExtentWidth: Any
    HorizontalOffset: Any
    ScrollOwner: Any
    VerticalOffset: Any
    ViewportHeight: Any
    ViewportWidth: Any
    def LineUp(self) -> Any: ...
    def LineDown(self) -> Any: ...
    def LineLeft(self) -> Any: ...
    def LineRight(self) -> Any: ...
    def PageUp(self) -> Any: ...
    def PageDown(self) -> Any: ...
    def PageLeft(self) -> Any: ...
    def PageRight(self) -> Any: ...
    def MouseWheelUp(self) -> Any: ...
    def MouseWheelDown(self) -> Any: ...
    def MouseWheelLeft(self) -> Any: ...
    def MouseWheelRight(self) -> Any: ...
    def SetHorizontalOffset(self, _p0: Any = ...) -> Any: ...
    def SetVerticalOffset(self, _p0: Any = ...) -> Any: ...
    def MakeVisible(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class IColorPickerSlider:
    ColorChannel: Any

class IColorPickerSliderStatics:
    ColorChannelProperty: Any

class IColorSpectrum:
    Color: Any
    Components: Any
    HsvColor: Any
    MaxHue: Any
    MaxSaturation: Any
    MaxValue: Any
    MinHue: Any
    MinSaturation: Any
    MinValue: Any
    Shape: Any
    ColorChanged: Any
    def add_ColorChanged(self, _p0: Any = ...) -> Any: ...
    def remove_ColorChanged(self, _p0: Any = ...) -> Any: ...

class IColorSpectrumStatics:
    ColorProperty: Any
    ComponentsProperty: Any
    HsvColorProperty: Any
    MaxHueProperty: Any
    MaxSaturationProperty: Any
    MaxValueProperty: Any
    MinHueProperty: Any
    MinSaturationProperty: Any
    MinValueProperty: Any
    ShapeProperty: Any

class IColumnMajorUniformToLargestGridLayout:
    ColumnSpacing: Any
    MaxColumns: Any
    RowSpacing: Any

class IColumnMajorUniformToLargestGridLayoutStatics:
    ColumnSpacingProperty: Any
    MaxColumnsProperty: Any
    RowSpacingProperty: Any

class IComboBoxHelperStatics:
    KeepInteriorCornersSquareProperty: Any
    def SetKeepInteriorCornersSquare(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetKeepInteriorCornersSquare(self, _p0: Any = ...) -> Any: ...

class IComboBoxTemplateSettings:
    DropDownClosedHeight: Any
    DropDownContentMinWidth: Any
    DropDownOffset: Any
    DropDownOpenedHeight: Any
    SelectedItemDirection: Any

class ICommandBarFlyoutCommandBar:
    FlyoutTemplateSettings: Any

class ICommandBarFlyoutCommandBar2:
    SystemBackdrop: Any

class ICommandBarFlyoutCommandBarAutomationPropertiesStatics:
    ControlTypeProperty: Any
    def GetControlType(self, _p0: Any = ...) -> Any: ...
    def SetControlType(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class ICommandBarFlyoutCommandBarStatics:
    SystemBackdropProperty: Any

class ICommandBarFlyoutCommandBarTemplateSettings:
    CloseAnimationEndPosition: Any
    ContentClipRect: Any
    CurrentWidth: Any
    ExpandDownAnimationEndPosition: Any
    ExpandDownAnimationHoldPosition: Any
    ExpandDownAnimationStartPosition: Any
    ExpandDownOverflowVerticalPosition: Any
    ExpandUpAnimationEndPosition: Any
    ExpandUpAnimationHoldPosition: Any
    ExpandUpAnimationStartPosition: Any
    ExpandUpOverflowVerticalPosition: Any
    ExpandedWidth: Any
    OpenAnimationEndPosition: Any
    OpenAnimationStartPosition: Any
    OverflowContentClipRect: Any
    WidthExpansionAnimationEndPosition: Any
    WidthExpansionAnimationStartPosition: Any
    WidthExpansionDelta: Any
    WidthExpansionMoreButtonAnimationEndPosition: Any
    WidthExpansionMoreButtonAnimationStartPosition: Any

class ICommandBarTemplateSettings:
    ContentHeight: Any
    EffectiveOverflowButtonVisibility: Any
    NegativeOverflowContentHeight: Any
    OverflowContentClipRect: Any
    OverflowContentCompactYTranslation: Any
    OverflowContentHeight: Any
    OverflowContentHiddenYTranslation: Any
    OverflowContentHorizontalOffset: Any
    OverflowContentMaxHeight: Any
    OverflowContentMaxWidth: Any
    OverflowContentMinWidth: Any
    OverflowContentMinimalYTranslation: Any

class ICornerRadiusFilterConverter:
    Filter: Any
    Scale: Any

class ICornerRadiusFilterConverterStatics:
    FilterProperty: Any
    ScaleProperty: Any

class ICornerRadiusToThicknessConverter:
    ConversionKind: Any
    Multiplier: Any

class ICornerRadiusToThicknessConverterStatics:
    ConversionKindProperty: Any
    MultiplierProperty: Any

class IDragCompletedEventArgs:
    Canceled: Any
    HorizontalChange: Any
    VerticalChange: Any

class IDragDeltaEventArgs:
    HorizontalChange: Any
    VerticalChange: Any

class IDragStartedEventArgs:
    HorizontalOffset: Any
    VerticalOffset: Any

class IFlyoutBase:
    AllowFocusOnInteraction: Any
    AllowFocusWhenDisabled: Any
    AreOpenCloseAnimationsEnabled: Any
    ElementSoundMode: Any
    InputDevicePrefersPrimaryCommands: Any
    IsConstrainedToRootBounds: Any
    IsOpen: Any
    LightDismissOverlayMode: Any
    OverlayInputPassThroughElement: Any
    Placement: Any
    ShouldConstrainToRootBounds: Any
    ShowMode: Any
    Target: Any
    XamlRoot: Any
    Closed: Any
    Closing: Any
    Opened: Any
    Opening: Any
    def add_Opened(self, _p0: Any = ...) -> Any: ...
    def remove_Opened(self, _p0: Any = ...) -> Any: ...
    def add_Closed(self, _p0: Any = ...) -> Any: ...
    def remove_Closed(self, _p0: Any = ...) -> Any: ...
    def add_Opening(self, _p0: Any = ...) -> Any: ...
    def remove_Opening(self, _p0: Any = ...) -> Any: ...
    def add_Closing(self, _p0: Any = ...) -> Any: ...
    def remove_Closing(self, _p0: Any = ...) -> Any: ...
    def ShowAt(self, _p0: Any = ...) -> Any: ...
    def ShowAtWithOptions(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def Hide(self) -> Any: ...
    def TryInvokeKeyboardAccelerator(self, _p0: Any = ...) -> Any: ...

class IFlyoutBase2:
    SystemBackdrop: Any

class IFlyoutBaseClosingEventArgs:
    Cancel: Any

class IFlyoutBaseStatics:
    AllowFocusOnInteractionProperty: Any
    AllowFocusWhenDisabledProperty: Any
    AreOpenCloseAnimationsEnabledProperty: Any
    AttachedFlyoutProperty: Any
    ElementSoundModeProperty: Any
    InputDevicePrefersPrimaryCommandsProperty: Any
    IsOpenProperty: Any
    LightDismissOverlayModeProperty: Any
    OverlayInputPassThroughElementProperty: Any
    PlacementProperty: Any
    ShouldConstrainToRootBoundsProperty: Any
    ShowModeProperty: Any
    TargetProperty: Any
    def GetAttachedFlyout(self, _p0: Any = ...) -> Any: ...
    def SetAttachedFlyout(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def ShowAttachedFlyout(self, _p0: Any = ...) -> Any: ...

class IFlyoutBaseStatics2:
    SystemBackdropProperty: Any

class IFlyoutShowOptions:
    ExclusionRect: Any
    Placement: Any
    Position: Any
    ShowMode: Any

class IGridViewItemPresenter:
    CheckBrush: Any
    CheckHintBrush: Any
    CheckSelectingBrush: Any
    ContentMargin: Any
    DisabledOpacity: Any
    DragBackground: Any
    DragForeground: Any
    DragOpacity: Any
    FocusBorderBrush: Any
    GridViewItemPresenterHorizontalContentAlignment: Any
    GridViewItemPresenterPadding: Any
    GridViewItemPresenterVerticalContentAlignment: Any
    PlaceholderBackground: Any
    PointerOverBackground: Any
    PointerOverBackgroundMargin: Any
    ReorderHintOffset: Any
    SelectedBackground: Any
    SelectedBorderThickness: Any
    SelectedForeground: Any
    SelectedPointerOverBackground: Any
    SelectedPointerOverBorderBrush: Any
    SelectionCheckMarkVisualEnabled: Any

class IGridViewItemPresenterStatics:
    CheckBrushProperty: Any
    CheckHintBrushProperty: Any
    CheckSelectingBrushProperty: Any
    ContentMarginProperty: Any
    DisabledOpacityProperty: Any
    DragBackgroundProperty: Any
    DragForegroundProperty: Any
    DragOpacityProperty: Any
    FocusBorderBrushProperty: Any
    GridViewItemPresenterHorizontalContentAlignmentProperty: Any
    GridViewItemPresenterPaddingProperty: Any
    GridViewItemPresenterVerticalContentAlignmentProperty: Any
    PlaceholderBackgroundProperty: Any
    PointerOverBackgroundMarginProperty: Any
    PointerOverBackgroundProperty: Any
    ReorderHintOffsetProperty: Any
    SelectedBackgroundProperty: Any
    SelectedBorderThicknessProperty: Any
    SelectedForegroundProperty: Any
    SelectedPointerOverBackgroundProperty: Any
    SelectedPointerOverBorderBrushProperty: Any
    SelectionCheckMarkVisualEnabledProperty: Any

class IGridViewItemTemplateSettings:
    DragItemsCount: Any

class IInfoBarPanel:
    HorizontalOrientationPadding: Any
    VerticalOrientationPadding: Any

class IInfoBarPanelStatics:
    HorizontalOrientationMarginProperty: Any
    HorizontalOrientationPaddingProperty: Any
    VerticalOrientationMarginProperty: Any
    VerticalOrientationPaddingProperty: Any
    def SetHorizontalOrientationMargin(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetHorizontalOrientationMargin(self, _p0: Any = ...) -> Any: ...
    def SetVerticalOrientationMargin(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetVerticalOrientationMargin(self, _p0: Any = ...) -> Any: ...

class IItemsChangedEventArgs:
    Action: Any
    ItemCount: Any
    ItemUICount: Any
    OldPosition: Any
    Position: Any

class IJumpListItemBackgroundConverter:
    Disabled: Any
    Enabled: Any

class IJumpListItemBackgroundConverterStatics:
    DisabledProperty: Any
    EnabledProperty: Any

class IJumpListItemForegroundConverter:
    Disabled: Any
    Enabled: Any

class IJumpListItemForegroundConverterStatics:
    DisabledProperty: Any
    EnabledProperty: Any

class IListViewItemPresenter:
    CheckBoxBorderBrush: Any
    CheckBoxBrush: Any
    CheckBoxCornerRadius: Any
    CheckBoxDisabledBorderBrush: Any
    CheckBoxDisabledBrush: Any
    CheckBoxPointerOverBorderBrush: Any
    CheckBoxPointerOverBrush: Any
    CheckBoxPressedBorderBrush: Any
    CheckBoxPressedBrush: Any
    CheckBoxSelectedBrush: Any
    CheckBoxSelectedDisabledBrush: Any
    CheckBoxSelectedPointerOverBrush: Any
    CheckBoxSelectedPressedBrush: Any
    CheckBrush: Any
    CheckDisabledBrush: Any
    CheckHintBrush: Any
    CheckMode: Any
    CheckPressedBrush: Any
    CheckSelectingBrush: Any
    ContentMargin: Any
    DisabledOpacity: Any
    DragBackground: Any
    DragForeground: Any
    DragOpacity: Any
    FocusBorderBrush: Any
    FocusSecondaryBorderBrush: Any
    ListViewItemPresenterHorizontalContentAlignment: Any
    ListViewItemPresenterPadding: Any
    ListViewItemPresenterVerticalContentAlignment: Any
    PlaceholderBackground: Any
    PointerOverBackground: Any
    PointerOverBackgroundMargin: Any
    PointerOverBorderBrush: Any
    PointerOverForeground: Any
    PressedBackground: Any
    ReorderHintOffset: Any
    RevealBackground: Any
    RevealBackgroundShowsAboveContent: Any
    RevealBorderBrush: Any
    RevealBorderThickness: Any
    SelectedBackground: Any
    SelectedBorderBrush: Any
    SelectedBorderThickness: Any
    SelectedDisabledBackground: Any
    SelectedDisabledBorderBrush: Any
    SelectedForeground: Any
    SelectedInnerBorderBrush: Any
    SelectedPointerOverBackground: Any
    SelectedPointerOverBorderBrush: Any
    SelectedPressedBackground: Any
    SelectedPressedBorderBrush: Any
    SelectionCheckMarkVisualEnabled: Any
    SelectionIndicatorBrush: Any
    SelectionIndicatorCornerRadius: Any
    SelectionIndicatorDisabledBrush: Any
    SelectionIndicatorMode: Any
    SelectionIndicatorPointerOverBrush: Any
    SelectionIndicatorPressedBrush: Any
    SelectionIndicatorVisualEnabled: Any

class IListViewItemPresenterStatics:
    CheckBoxBorderBrushProperty: Any
    CheckBoxBrushProperty: Any
    CheckBoxCornerRadiusProperty: Any
    CheckBoxDisabledBorderBrushProperty: Any
    CheckBoxDisabledBrushProperty: Any
    CheckBoxPointerOverBorderBrushProperty: Any
    CheckBoxPointerOverBrushProperty: Any
    CheckBoxPressedBorderBrushProperty: Any
    CheckBoxPressedBrushProperty: Any
    CheckBoxSelectedBrushProperty: Any
    CheckBoxSelectedDisabledBrushProperty: Any
    CheckBoxSelectedPointerOverBrushProperty: Any
    CheckBoxSelectedPressedBrushProperty: Any
    CheckBrushProperty: Any
    CheckDisabledBrushProperty: Any
    CheckHintBrushProperty: Any
    CheckModeProperty: Any
    CheckPressedBrushProperty: Any
    CheckSelectingBrushProperty: Any
    ContentMarginProperty: Any
    DisabledOpacityProperty: Any
    DragBackgroundProperty: Any
    DragForegroundProperty: Any
    DragOpacityProperty: Any
    FocusBorderBrushProperty: Any
    FocusSecondaryBorderBrushProperty: Any
    ListViewItemPresenterHorizontalContentAlignmentProperty: Any
    ListViewItemPresenterPaddingProperty: Any
    ListViewItemPresenterVerticalContentAlignmentProperty: Any
    PlaceholderBackgroundProperty: Any
    PointerOverBackgroundMarginProperty: Any
    PointerOverBackgroundProperty: Any
    PointerOverBorderBrushProperty: Any
    PointerOverForegroundProperty: Any
    PressedBackgroundProperty: Any
    ReorderHintOffsetProperty: Any
    RevealBackgroundProperty: Any
    RevealBackgroundShowsAboveContentProperty: Any
    RevealBorderBrushProperty: Any
    RevealBorderThicknessProperty: Any
    SelectedBackgroundProperty: Any
    SelectedBorderBrushProperty: Any
    SelectedBorderThicknessProperty: Any
    SelectedDisabledBackgroundProperty: Any
    SelectedDisabledBorderBrushProperty: Any
    SelectedForegroundProperty: Any
    SelectedInnerBorderBrushProperty: Any
    SelectedPointerOverBackgroundProperty: Any
    SelectedPointerOverBorderBrushProperty: Any
    SelectedPressedBackgroundProperty: Any
    SelectedPressedBorderBrushProperty: Any
    SelectionCheckMarkVisualEnabledProperty: Any
    SelectionIndicatorBrushProperty: Any
    SelectionIndicatorCornerRadiusProperty: Any
    SelectionIndicatorDisabledBrushProperty: Any
    SelectionIndicatorModeProperty: Any
    SelectionIndicatorPointerOverBrushProperty: Any
    SelectionIndicatorPressedBrushProperty: Any
    SelectionIndicatorVisualEnabledProperty: Any

class IListViewItemTemplateSettings:
    DragItemsCount: Any

class ILoopingSelector:
    ItemHeight: Any
    ItemTemplate: Any
    ItemWidth: Any
    Items: Any
    SelectedIndex: Any
    SelectedItem: Any
    ShouldLoop: Any
    SelectionChanged: Any
    def add_SelectionChanged(self, _p0: Any = ...) -> Any: ...
    def remove_SelectionChanged(self, _p0: Any = ...) -> Any: ...

class ILoopingSelectorStatics:
    ItemHeightProperty: Any
    ItemTemplateProperty: Any
    ItemWidthProperty: Any
    ItemsProperty: Any
    SelectedIndexProperty: Any
    SelectedItemProperty: Any
    ShouldLoopProperty: Any

class IMenuFlyoutItemTemplateSettings:
    KeyboardAcceleratorTextMinWidth: Any

class IMenuFlyoutPresenterTemplateSettings:
    FlyoutContentMinWidth: Any

class IMonochromaticOverlayPresenter:
    ReplacementColor: Any
    SourceElement: Any

class IMonochromaticOverlayPresenterStatics:
    ReplacementColorProperty: Any
    SourceElementProperty: Any

class INavigationViewItemPresenter:
    Icon: Any
    TemplateSettings: Any

class INavigationViewItemPresenter2:
    InfoBadge: Any

class INavigationViewItemPresenterStatics:
    IconProperty: Any
    TemplateSettingsProperty: Any

class INavigationViewItemPresenterStatics2:
    InfoBadgeProperty: Any

class INavigationViewItemPresenterTemplateSettings:
    IconWidth: Any
    SmallerIconWidth: Any

class INavigationViewItemPresenterTemplateSettingsStatics:
    IconWidthProperty: Any
    SmallerIconWidthProperty: Any

class IOrientedVirtualizingPanel:
    CanHorizontallyScroll: Any
    CanVerticallyScroll: Any
    ExtentHeight: Any
    ExtentWidth: Any
    HorizontalOffset: Any
    ScrollOwner: Any
    VerticalOffset: Any
    ViewportHeight: Any
    ViewportWidth: Any
    def LineUp(self) -> Any: ...
    def LineDown(self) -> Any: ...
    def LineLeft(self) -> Any: ...
    def LineRight(self) -> Any: ...
    def PageUp(self) -> Any: ...
    def PageDown(self) -> Any: ...
    def PageLeft(self) -> Any: ...
    def PageRight(self) -> Any: ...
    def MouseWheelUp(self) -> Any: ...
    def MouseWheelDown(self) -> Any: ...
    def MouseWheelLeft(self) -> Any: ...
    def MouseWheelRight(self) -> Any: ...
    def SetHorizontalOffset(self, _p0: Any = ...) -> Any: ...
    def SetVerticalOffset(self, _p0: Any = ...) -> Any: ...
    def MakeVisible(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class IPickerFlyoutBaseStatics:
    TitleProperty: Any
    def GetTitle(self, _p0: Any = ...) -> Any: ...
    def SetTitle(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class IPopup:
    Child: Any
    ChildTransitions: Any
    HorizontalOffset: Any
    IsConstrainedToRootBounds: Any
    IsLightDismissEnabled: Any
    IsOpen: Any
    LightDismissOverlayMode: Any
    ShouldConstrainToRootBounds: Any
    VerticalOffset: Any
    Closed: Any
    Opened: Any
    def add_Opened(self, _p0: Any = ...) -> Any: ...
    def remove_Opened(self, _p0: Any = ...) -> Any: ...
    def add_Closed(self, _p0: Any = ...) -> Any: ...
    def remove_Closed(self, _p0: Any = ...) -> Any: ...

class IPopup2:
    ActualPlacement: Any
    DesiredPlacement: Any
    PlacementTarget: Any
    ActualPlacementChanged: Any
    def add_ActualPlacementChanged(self, _p0: Any = ...) -> Any: ...
    def remove_ActualPlacementChanged(self, _p0: Any = ...) -> Any: ...

class IPopup3:
    SystemBackdrop: Any

class IPopupStatics:
    ChildProperty: Any
    ChildTransitionsProperty: Any
    HorizontalOffsetProperty: Any
    IsLightDismissEnabledProperty: Any
    IsOpenProperty: Any
    LightDismissOverlayModeProperty: Any
    ShouldConstrainToRootBoundsProperty: Any
    VerticalOffsetProperty: Any

class IPopupStatics2:
    DesiredPlacementProperty: Any
    PlacementTargetProperty: Any

class IPopupStatics3:
    SystemBackdropProperty: Any

class IRangeBase:
    LargeChange: Any
    Maximum: Any
    Minimum: Any
    SmallChange: Any
    Value: Any
    ValueChanged: Any
    def add_ValueChanged(self, _p0: Any = ...) -> Any: ...
    def remove_ValueChanged(self, _p0: Any = ...) -> Any: ...

class IRangeBaseStatics:
    LargeChangeProperty: Any
    MaximumProperty: Any
    MinimumProperty: Any
    SmallChangeProperty: Any
    ValueProperty: Any

class IRangeBaseValueChangedEventArgs:
    NewValue: Any
    OldValue: Any

class IRepeatButton:
    Delay: Any
    Interval: Any

class IRepeatButtonStatics:
    DelayProperty: Any
    IntervalProperty: Any

class IRepeatedScrollSnapPoint:
    End: Any
    Interval: Any
    Offset: Any
    Start: Any

class IRepeatedZoomSnapPoint:
    End: Any
    Interval: Any
    Offset: Any
    Start: Any

class IScrollBar:
    IndicatorMode: Any
    Orientation: Any
    ViewportSize: Any
    Scroll: Any
    def add_Scroll(self, _p0: Any = ...) -> Any: ...
    def remove_Scroll(self, _p0: Any = ...) -> Any: ...

class IScrollBarStatics:
    IndicatorModeProperty: Any
    OrientationProperty: Any
    ViewportSizeProperty: Any

class IScrollController:
    CanScroll: Any
    IsScrollingWithMouse: Any
    PanningInfo: Any
    AddScrollVelocityRequested: Any
    CanScrollChanged: Any
    IsScrollingWithMouseChanged: Any
    ScrollByRequested: Any
    ScrollToRequested: Any
    def SetIsScrollable(self, _p0: Any = ...) -> Any: ...
    def SetValues(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...) -> Any: ...
    def GetScrollAnimation(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...) -> Any: ...
    def NotifyRequestedScrollCompleted(self, _p0: Any = ...) -> Any: ...
    def add_CanScrollChanged(self, _p0: Any = ...) -> Any: ...
    def remove_CanScrollChanged(self, _p0: Any = ...) -> Any: ...
    def add_IsScrollingWithMouseChanged(self, _p0: Any = ...) -> Any: ...
    def remove_IsScrollingWithMouseChanged(self, _p0: Any = ...) -> Any: ...
    def add_ScrollToRequested(self, _p0: Any = ...) -> Any: ...
    def remove_ScrollToRequested(self, _p0: Any = ...) -> Any: ...
    def add_ScrollByRequested(self, _p0: Any = ...) -> Any: ...
    def remove_ScrollByRequested(self, _p0: Any = ...) -> Any: ...
    def add_AddScrollVelocityRequested(self, _p0: Any = ...) -> Any: ...
    def remove_AddScrollVelocityRequested(self, _p0: Any = ...) -> Any: ...

class IScrollControllerAddScrollVelocityRequestedEventArgs:
    CorrelationId: Any
    InertiaDecayRate: Any
    OffsetVelocity: Any

class IScrollControllerPanRequestedEventArgs:
    Handled: Any
    PointerPoint: Any

class IScrollControllerPanningInfo:
    IsRailEnabled: Any
    PanOrientation: Any
    PanningElementAncestor: Any
    Changed: Any
    PanRequested: Any
    def SetPanningElementExpressionAnimationSources(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ..., _p4: Any = ...) -> Any: ...
    def add_Changed(self, _p0: Any = ...) -> Any: ...
    def remove_Changed(self, _p0: Any = ...) -> Any: ...
    def add_PanRequested(self, _p0: Any = ...) -> Any: ...
    def remove_PanRequested(self, _p0: Any = ...) -> Any: ...

class IScrollControllerScrollByRequestedEventArgs:
    CorrelationId: Any
    OffsetDelta: Any
    Options: Any

class IScrollControllerScrollToRequestedEventArgs:
    CorrelationId: Any
    Offset: Any
    Options: Any

class IScrollEventArgs:
    NewValue: Any
    ScrollEventType: Any

class IScrollPresenter:
    Background: Any
    ComputedHorizontalScrollMode: Any
    ComputedVerticalScrollMode: Any
    Content: Any
    ContentOrientation: Any
    ExpressionAnimationSources: Any
    ExtentHeight: Any
    ExtentWidth: Any
    HorizontalAnchorRatio: Any
    HorizontalOffset: Any
    HorizontalScrollChainMode: Any
    HorizontalScrollController: Any
    HorizontalScrollMode: Any
    HorizontalScrollRailMode: Any
    HorizontalSnapPoints: Any
    IgnoredInputKinds: Any
    MaxZoomFactor: Any
    MinZoomFactor: Any
    ScrollableHeight: Any
    ScrollableWidth: Any
    State: Any
    VerticalAnchorRatio: Any
    VerticalOffset: Any
    VerticalScrollChainMode: Any
    VerticalScrollController: Any
    VerticalScrollMode: Any
    VerticalScrollRailMode: Any
    VerticalSnapPoints: Any
    ViewportHeight: Any
    ViewportWidth: Any
    ZoomChainMode: Any
    ZoomFactor: Any
    ZoomMode: Any
    ZoomSnapPoints: Any
    AnchorRequested: Any
    BringingIntoView: Any
    ExtentChanged: Any
    ScrollAnimationStarting: Any
    ScrollCompleted: Any
    StateChanged: Any
    ViewChanged: Any
    ZoomAnimationStarting: Any
    ZoomCompleted: Any
    def ScrollTo(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def ScrollToWithOptions(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def ScrollBy(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def ScrollByWithOptions(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def AddScrollVelocity(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def ZoomTo(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def ZoomToWithOptions(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def ZoomBy(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def ZoomByWithOptions(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def AddZoomVelocity(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def add_ExtentChanged(self, _p0: Any = ...) -> Any: ...
    def remove_ExtentChanged(self, _p0: Any = ...) -> Any: ...
    def add_StateChanged(self, _p0: Any = ...) -> Any: ...
    def remove_StateChanged(self, _p0: Any = ...) -> Any: ...
    def add_ViewChanged(self, _p0: Any = ...) -> Any: ...
    def remove_ViewChanged(self, _p0: Any = ...) -> Any: ...
    def add_ScrollAnimationStarting(self, _p0: Any = ...) -> Any: ...
    def remove_ScrollAnimationStarting(self, _p0: Any = ...) -> Any: ...
    def add_ZoomAnimationStarting(self, _p0: Any = ...) -> Any: ...
    def remove_ZoomAnimationStarting(self, _p0: Any = ...) -> Any: ...
    def add_ScrollCompleted(self, _p0: Any = ...) -> Any: ...
    def remove_ScrollCompleted(self, _p0: Any = ...) -> Any: ...
    def add_ZoomCompleted(self, _p0: Any = ...) -> Any: ...
    def remove_ZoomCompleted(self, _p0: Any = ...) -> Any: ...
    def add_BringingIntoView(self, _p0: Any = ...) -> Any: ...
    def remove_BringingIntoView(self, _p0: Any = ...) -> Any: ...
    def add_AnchorRequested(self, _p0: Any = ...) -> Any: ...
    def remove_AnchorRequested(self, _p0: Any = ...) -> Any: ...

class IScrollPresenterStatics:
    BackgroundProperty: Any
    ComputedHorizontalScrollModeProperty: Any
    ComputedVerticalScrollModeProperty: Any
    ContentOrientationProperty: Any
    ContentProperty: Any
    HorizontalAnchorRatioProperty: Any
    HorizontalScrollChainModeProperty: Any
    HorizontalScrollModeProperty: Any
    HorizontalScrollRailModeProperty: Any
    IgnoredInputKindsProperty: Any
    MaxZoomFactorProperty: Any
    MinZoomFactorProperty: Any
    VerticalAnchorRatioProperty: Any
    VerticalScrollChainModeProperty: Any
    VerticalScrollModeProperty: Any
    VerticalScrollRailModeProperty: Any
    ZoomChainModeProperty: Any
    ZoomModeProperty: Any

class IScrollSnapPoint:
    Value: Any

class IScrollSnapPointBase:
    Alignment: Any

class IScrollSnapPointsInfo:
    AreHorizontalSnapPointsRegular: Any
    AreVerticalSnapPointsRegular: Any
    HorizontalSnapPointsChanged: Any
    VerticalSnapPointsChanged: Any
    def add_HorizontalSnapPointsChanged(self, _p0: Any = ...) -> Any: ...
    def remove_HorizontalSnapPointsChanged(self, _p0: Any = ...) -> Any: ...
    def add_VerticalSnapPointsChanged(self, _p0: Any = ...) -> Any: ...
    def remove_VerticalSnapPointsChanged(self, _p0: Any = ...) -> Any: ...
    def GetIrregularSnapPoints(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetRegularSnapPoints(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...

class ISelector:
    IsSynchronizedWithCurrentItem: Any
    SelectedIndex: Any
    SelectedItem: Any
    SelectedValue: Any
    SelectedValuePath: Any
    SelectionChanged: Any
    def add_SelectionChanged(self, _p0: Any = ...) -> Any: ...
    def remove_SelectionChanged(self, _p0: Any = ...) -> Any: ...

class ISelectorItem:
    IsSelected: Any

class ISelectorItemStatics:
    IsSelectedProperty: Any

class ISelectorStatics:
    IsSynchronizedWithCurrentItemProperty: Any
    SelectedIndexProperty: Any
    SelectedItemProperty: Any
    SelectedValuePathProperty: Any
    SelectedValueProperty: Any
    def GetIsSelectionActive(self, _p0: Any = ...) -> Any: ...

class ISplitViewTemplateSettings:
    CompactPaneGridLength: Any
    NegativeOpenPaneLength: Any
    NegativeOpenPaneLengthMinusCompactLength: Any
    OpenPaneGridLength: Any
    OpenPaneLength: Any
    OpenPaneLengthMinusCompactLength: Any

class IThumb:
    IsDragging: Any
    DragCompleted: Any
    DragDelta: Any
    DragStarted: Any
    def add_DragStarted(self, _p0: Any = ...) -> Any: ...
    def remove_DragStarted(self, _p0: Any = ...) -> Any: ...
    def add_DragDelta(self, _p0: Any = ...) -> Any: ...
    def remove_DragDelta(self, _p0: Any = ...) -> Any: ...
    def add_DragCompleted(self, _p0: Any = ...) -> Any: ...
    def remove_DragCompleted(self, _p0: Any = ...) -> Any: ...
    def CancelDrag(self) -> Any: ...

class IThumbStatics:
    IsDraggingProperty: Any

class ITickBar:
    Fill: Any

class ITickBarStatics:
    FillProperty: Any

class IToggleButton:
    IsChecked: Any
    IsThreeState: Any
    Checked: Any
    Indeterminate: Any
    Unchecked: Any
    def add_Checked(self, _p0: Any = ...) -> Any: ...
    def remove_Checked(self, _p0: Any = ...) -> Any: ...
    def add_Unchecked(self, _p0: Any = ...) -> Any: ...
    def remove_Unchecked(self, _p0: Any = ...) -> Any: ...
    def add_Indeterminate(self, _p0: Any = ...) -> Any: ...
    def remove_Indeterminate(self, _p0: Any = ...) -> Any: ...

class IToggleButtonStatics:
    IsCheckedProperty: Any
    IsThreeStateProperty: Any

class IToggleSwitchTemplateSettings:
    CurtainCurrentToOffOffset: Any
    CurtainCurrentToOnOffset: Any
    CurtainOffToOnOffset: Any
    CurtainOnToOffOffset: Any
    KnobCurrentToOffOffset: Any
    KnobCurrentToOnOffset: Any
    KnobOffToOnOffset: Any
    KnobOnToOffOffset: Any

class IToolTipTemplateSettings:
    FromHorizontalOffset: Any
    FromVerticalOffset: Any

class IZoomSnapPoint:
    Value: Any

class InfoBarPanel(Panel):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    HorizontalOrientationPadding: Any
    VerticalOrientationPadding: Any
    HorizontalOrientationMarginProperty: Any
    HorizontalOrientationPaddingProperty: Any
    VerticalOrientationMarginProperty: Any
    VerticalOrientationPaddingProperty: Any
    @classmethod
    def SetHorizontalOrientationMargin(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def GetHorizontalOrientationMargin(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def SetVerticalOrientationMargin(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def GetVerticalOrientationMargin(cls, _p0: Any = ...) -> Any: ...

class ItemsChangedEventArgs:
    Action: Any
    ItemCount: Any
    ItemUICount: Any
    OldPosition: Any
    Position: Any

class ItemsChangedEventHandler:
    def Invoke(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class JumpListItemBackgroundConverter(DependencyObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Disabled: Any
    Enabled: Any
    DisabledProperty: Any
    EnabledProperty: Any
    def Convert(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...) -> Any: ...
    def ConvertBack(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...) -> Any: ...

class JumpListItemForegroundConverter(DependencyObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Disabled: Any
    Enabled: Any
    DisabledProperty: Any
    EnabledProperty: Any
    def Convert(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...) -> Any: ...
    def ConvertBack(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...) -> Any: ...

class LayoutInformation:
    @classmethod
    def GetLayoutExceptionElement(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def GetLayoutSlot(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def GetAvailableSize(cls, _p0: Any = ...) -> Any: ...

class ListViewItemPresenter(ContentPresenter):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    CheckBoxBorderBrush: Any
    CheckBoxBrush: Any
    CheckBoxCornerRadius: Any
    CheckBoxDisabledBorderBrush: Any
    CheckBoxDisabledBrush: Any
    CheckBoxPointerOverBorderBrush: Any
    CheckBoxPointerOverBrush: Any
    CheckBoxPressedBorderBrush: Any
    CheckBoxPressedBrush: Any
    CheckBoxSelectedBrush: Any
    CheckBoxSelectedDisabledBrush: Any
    CheckBoxSelectedPointerOverBrush: Any
    CheckBoxSelectedPressedBrush: Any
    CheckBrush: Any
    CheckDisabledBrush: Any
    CheckHintBrush: Any
    CheckMode: Any
    CheckPressedBrush: Any
    CheckSelectingBrush: Any
    ContentMargin: Any
    DisabledOpacity: Any
    DragBackground: Any
    DragForeground: Any
    DragOpacity: Any
    FocusBorderBrush: Any
    FocusSecondaryBorderBrush: Any
    ListViewItemPresenterHorizontalContentAlignment: Any
    ListViewItemPresenterPadding: Any
    ListViewItemPresenterVerticalContentAlignment: Any
    PlaceholderBackground: Any
    PointerOverBackground: Any
    PointerOverBackgroundMargin: Any
    PointerOverBorderBrush: Any
    PointerOverForeground: Any
    PressedBackground: Any
    ReorderHintOffset: Any
    RevealBackground: Any
    RevealBackgroundShowsAboveContent: Any
    RevealBorderBrush: Any
    RevealBorderThickness: Any
    SelectedBackground: Any
    SelectedBorderBrush: Any
    SelectedBorderThickness: Any
    SelectedDisabledBackground: Any
    SelectedDisabledBorderBrush: Any
    SelectedForeground: Any
    SelectedInnerBorderBrush: Any
    SelectedPointerOverBackground: Any
    SelectedPointerOverBorderBrush: Any
    SelectedPressedBackground: Any
    SelectedPressedBorderBrush: Any
    SelectionCheckMarkVisualEnabled: Any
    SelectionIndicatorBrush: Any
    SelectionIndicatorCornerRadius: Any
    SelectionIndicatorDisabledBrush: Any
    SelectionIndicatorMode: Any
    SelectionIndicatorPointerOverBrush: Any
    SelectionIndicatorPressedBrush: Any
    SelectionIndicatorVisualEnabled: Any
    CheckBoxBorderBrushProperty: Any
    CheckBoxBrushProperty: Any
    CheckBoxCornerRadiusProperty: Any
    CheckBoxDisabledBorderBrushProperty: Any
    CheckBoxDisabledBrushProperty: Any
    CheckBoxPointerOverBorderBrushProperty: Any
    CheckBoxPointerOverBrushProperty: Any
    CheckBoxPressedBorderBrushProperty: Any
    CheckBoxPressedBrushProperty: Any
    CheckBoxSelectedBrushProperty: Any
    CheckBoxSelectedDisabledBrushProperty: Any
    CheckBoxSelectedPointerOverBrushProperty: Any
    CheckBoxSelectedPressedBrushProperty: Any
    CheckBrushProperty: Any
    CheckDisabledBrushProperty: Any
    CheckHintBrushProperty: Any
    CheckModeProperty: Any
    CheckPressedBrushProperty: Any
    CheckSelectingBrushProperty: Any
    ContentMarginProperty: Any
    DisabledOpacityProperty: Any
    DragBackgroundProperty: Any
    DragForegroundProperty: Any
    DragOpacityProperty: Any
    FocusBorderBrushProperty: Any
    FocusSecondaryBorderBrushProperty: Any
    ListViewItemPresenterHorizontalContentAlignmentProperty: Any
    ListViewItemPresenterPaddingProperty: Any
    ListViewItemPresenterVerticalContentAlignmentProperty: Any
    PlaceholderBackgroundProperty: Any
    PointerOverBackgroundMarginProperty: Any
    PointerOverBackgroundProperty: Any
    PointerOverBorderBrushProperty: Any
    PointerOverForegroundProperty: Any
    PressedBackgroundProperty: Any
    ReorderHintOffsetProperty: Any
    RevealBackgroundProperty: Any
    RevealBackgroundShowsAboveContentProperty: Any
    RevealBorderBrushProperty: Any
    RevealBorderThicknessProperty: Any
    SelectedBackgroundProperty: Any
    SelectedBorderBrushProperty: Any
    SelectedBorderThicknessProperty: Any
    SelectedDisabledBackgroundProperty: Any
    SelectedDisabledBorderBrushProperty: Any
    SelectedForegroundProperty: Any
    SelectedInnerBorderBrushProperty: Any
    SelectedPointerOverBackgroundProperty: Any
    SelectedPointerOverBorderBrushProperty: Any
    SelectedPressedBackgroundProperty: Any
    SelectedPressedBorderBrushProperty: Any
    SelectionCheckMarkVisualEnabledProperty: Any
    SelectionIndicatorBrushProperty: Any
    SelectionIndicatorCornerRadiusProperty: Any
    SelectionIndicatorDisabledBrushProperty: Any
    SelectionIndicatorModeProperty: Any
    SelectionIndicatorPointerOverBrushProperty: Any
    SelectionIndicatorPressedBrushProperty: Any
    SelectionIndicatorVisualEnabledProperty: Any

class ListViewItemPresenterCheckMode(int):
    Inline: int
    Overlay: int

class ListViewItemPresenterSelectionIndicatorMode(int):
    Inline: int
    Overlay: int

class ListViewItemTemplateSettings(DependencyObject):
    DragItemsCount: Any

class LoopingSelector(Control):
    ItemHeight: Any
    ItemTemplate: Any
    ItemWidth: Any
    Items: Any
    SelectedIndex: Any
    SelectedItem: Any
    ShouldLoop: Any
    SelectionChanged: Any
    ItemHeightProperty: Any
    ItemTemplateProperty: Any
    ItemWidthProperty: Any
    ItemsProperty: Any
    SelectedIndexProperty: Any
    SelectedItemProperty: Any
    ShouldLoopProperty: Any
    def add_SelectionChanged(self, _p0: Any = ...) -> Any: ...
    def remove_SelectionChanged(self, _p0: Any = ...) -> Any: ...

class LoopingSelectorItem(ContentControl):
    ...

class LoopingSelectorPanel(Canvas):
    AreHorizontalSnapPointsRegular: Any
    AreVerticalSnapPointsRegular: Any
    HorizontalSnapPointsChanged: Any
    VerticalSnapPointsChanged: Any
    def add_HorizontalSnapPointsChanged(self, _p0: Any = ...) -> Any: ...
    def remove_HorizontalSnapPointsChanged(self, _p0: Any = ...) -> Any: ...
    def add_VerticalSnapPointsChanged(self, _p0: Any = ...) -> Any: ...
    def remove_VerticalSnapPointsChanged(self, _p0: Any = ...) -> Any: ...
    def GetIrregularSnapPoints(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetRegularSnapPoints(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...

class MenuFlyoutItemTemplateSettings(DependencyObject):
    KeyboardAcceleratorTextMinWidth: Any

class MenuFlyoutPresenterTemplateSettings(DependencyObject):
    FlyoutContentMinWidth: Any

class MonochromaticOverlayPresenter(Grid):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    ReplacementColor: Any
    SourceElement: Any
    ReplacementColorProperty: Any
    SourceElementProperty: Any

class NavigationViewItemPresenter(ContentControl):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Icon: Any
    InfoBadge: Any
    TemplateSettings: Any
    IconProperty: Any
    InfoBadgeProperty: Any
    TemplateSettingsProperty: Any

class NavigationViewItemPresenterTemplateSettings(DependencyObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    IconWidth: Any
    SmallerIconWidth: Any
    IconWidthProperty: Any
    SmallerIconWidthProperty: Any

class OrientedVirtualizingPanel(VirtualizingPanel):
    AreHorizontalSnapPointsRegular: Any
    AreVerticalSnapPointsRegular: Any
    CanHorizontallyScroll: Any
    CanVerticallyScroll: Any
    ExtentHeight: Any
    ExtentWidth: Any
    HorizontalOffset: Any
    ScrollOwner: Any
    VerticalOffset: Any
    ViewportHeight: Any
    ViewportWidth: Any
    HorizontalSnapPointsChanged: Any
    VerticalSnapPointsChanged: Any
    def LineUp(self) -> Any: ...
    def LineDown(self) -> Any: ...
    def LineLeft(self) -> Any: ...
    def LineRight(self) -> Any: ...
    def PageUp(self) -> Any: ...
    def PageDown(self) -> Any: ...
    def PageLeft(self) -> Any: ...
    def PageRight(self) -> Any: ...
    def MouseWheelUp(self) -> Any: ...
    def MouseWheelDown(self) -> Any: ...
    def MouseWheelLeft(self) -> Any: ...
    def MouseWheelRight(self) -> Any: ...
    def SetHorizontalOffset(self, _p0: Any = ...) -> Any: ...
    def SetVerticalOffset(self, _p0: Any = ...) -> Any: ...
    def MakeVisible(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def add_HorizontalSnapPointsChanged(self, _p0: Any = ...) -> Any: ...
    def remove_HorizontalSnapPointsChanged(self, _p0: Any = ...) -> Any: ...
    def add_VerticalSnapPointsChanged(self, _p0: Any = ...) -> Any: ...
    def remove_VerticalSnapPointsChanged(self, _p0: Any = ...) -> Any: ...
    def GetIrregularSnapPoints(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetRegularSnapPoints(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def GetInsertionIndexes(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...

class PickerFlyoutBase(FlyoutBase):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    TitleProperty: Any
    def OnConfirmed(self) -> Any: ...
    def ShouldShowConfirmationButtons(self) -> Any: ...
    @classmethod
    def GetTitle(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def SetTitle(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class PivotHeaderItem(ContentControl):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class PivotHeaderPanel(Canvas):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class PivotPanel(Panel):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    AreHorizontalSnapPointsRegular: Any
    AreVerticalSnapPointsRegular: Any
    HorizontalSnapPointsChanged: Any
    VerticalSnapPointsChanged: Any
    def add_HorizontalSnapPointsChanged(self, _p0: Any = ...) -> Any: ...
    def remove_HorizontalSnapPointsChanged(self, _p0: Any = ...) -> Any: ...
    def add_VerticalSnapPointsChanged(self, _p0: Any = ...) -> Any: ...
    def remove_VerticalSnapPointsChanged(self, _p0: Any = ...) -> Any: ...
    def GetIrregularSnapPoints(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetRegularSnapPoints(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...

class PlacementMode(int):
    Bottom: int
    Left: int
    Mouse: int
    Right: int
    Top: int

class Popup(FrameworkElement):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    ActualPlacement: Any
    Child: Any
    ChildTransitions: Any
    DesiredPlacement: Any
    HorizontalOffset: Any
    IsConstrainedToRootBounds: Any
    IsLightDismissEnabled: Any
    IsOpen: Any
    LightDismissOverlayMode: Any
    PlacementTarget: Any
    ShouldConstrainToRootBounds: Any
    SystemBackdrop: Any
    VerticalOffset: Any
    ActualPlacementChanged: Any
    Closed: Any
    Opened: Any
    ChildProperty: Any
    ChildTransitionsProperty: Any
    DesiredPlacementProperty: Any
    HorizontalOffsetProperty: Any
    IsLightDismissEnabledProperty: Any
    IsOpenProperty: Any
    LightDismissOverlayModeProperty: Any
    PlacementTargetProperty: Any
    ShouldConstrainToRootBoundsProperty: Any
    SystemBackdropProperty: Any
    VerticalOffsetProperty: Any
    def add_Opened(self, _p0: Any = ...) -> Any: ...
    def remove_Opened(self, _p0: Any = ...) -> Any: ...
    def add_Closed(self, _p0: Any = ...) -> Any: ...
    def remove_Closed(self, _p0: Any = ...) -> Any: ...
    def add_ActualPlacementChanged(self, _p0: Any = ...) -> Any: ...
    def remove_ActualPlacementChanged(self, _p0: Any = ...) -> Any: ...

class PopupPlacementMode(int):
    Auto: int
    Top: int
    Bottom: int
    Left: int
    Right: int
    TopEdgeAlignedLeft: int
    TopEdgeAlignedRight: int
    BottomEdgeAlignedLeft: int
    BottomEdgeAlignedRight: int
    LeftEdgeAlignedTop: int
    LeftEdgeAlignedBottom: int
    RightEdgeAlignedTop: int
    RightEdgeAlignedBottom: int

class RangeBase(Control):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    LargeChange: Any
    Maximum: Any
    Minimum: Any
    SmallChange: Any
    Value: Any
    ValueChanged: Any
    LargeChangeProperty: Any
    MaximumProperty: Any
    MinimumProperty: Any
    SmallChangeProperty: Any
    ValueProperty: Any
    def add_ValueChanged(self, _p0: Any = ...) -> Any: ...
    def remove_ValueChanged(self, _p0: Any = ...) -> Any: ...
    def OnMinimumChanged(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def OnMaximumChanged(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def OnValueChanged(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class RangeBaseValueChangedEventArgs(RoutedEventArgs):
    NewValue: Any
    OldValue: Any

class RangeBaseValueChangedEventHandler:
    def Invoke(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class RepeatButton(ButtonBase):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Delay: Any
    Interval: Any
    DelayProperty: Any
    IntervalProperty: Any

class RepeatedScrollSnapPoint(ScrollSnapPointBase):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    End: Any
    Interval: Any
    Offset: Any
    Start: Any

class RepeatedZoomSnapPoint(ZoomSnapPointBase):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    End: Any
    Interval: Any
    Offset: Any
    Start: Any

class ScrollBar(RangeBase):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    IndicatorMode: Any
    Orientation: Any
    ViewportSize: Any
    Scroll: Any
    IndicatorModeProperty: Any
    OrientationProperty: Any
    ViewportSizeProperty: Any
    def add_Scroll(self, _p0: Any = ...) -> Any: ...
    def remove_Scroll(self, _p0: Any = ...) -> Any: ...

class ScrollControllerAddScrollVelocityRequestedEventArgs:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    CorrelationId: Any
    InertiaDecayRate: Any
    OffsetVelocity: Any

class ScrollControllerPanRequestedEventArgs:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Handled: Any
    PointerPoint: Any

class ScrollControllerScrollByRequestedEventArgs:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    CorrelationId: Any
    OffsetDelta: Any
    Options: Any

class ScrollControllerScrollToRequestedEventArgs:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    CorrelationId: Any
    Offset: Any
    Options: Any

class ScrollEventArgs(RoutedEventArgs):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    NewValue: Any
    ScrollEventType: Any

class ScrollEventHandler:
    def Invoke(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class ScrollEventType(int):
    SmallDecrement: int
    SmallIncrement: int
    LargeDecrement: int
    LargeIncrement: int
    ThumbPosition: int
    ThumbTrack: int
    First: int
    Last: int
    EndScroll: int

class ScrollPresenter(FrameworkElement):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Background: Any
    ComputedHorizontalScrollMode: Any
    ComputedVerticalScrollMode: Any
    Content: Any
    ContentOrientation: Any
    CurrentAnchor: Any
    ExpressionAnimationSources: Any
    ExtentHeight: Any
    ExtentWidth: Any
    HorizontalAnchorRatio: Any
    HorizontalOffset: Any
    HorizontalScrollChainMode: Any
    HorizontalScrollController: Any
    HorizontalScrollMode: Any
    HorizontalScrollRailMode: Any
    HorizontalSnapPoints: Any
    IgnoredInputKinds: Any
    MaxZoomFactor: Any
    MinZoomFactor: Any
    ScrollableHeight: Any
    ScrollableWidth: Any
    State: Any
    VerticalAnchorRatio: Any
    VerticalOffset: Any
    VerticalScrollChainMode: Any
    VerticalScrollController: Any
    VerticalScrollMode: Any
    VerticalScrollRailMode: Any
    VerticalSnapPoints: Any
    ViewportHeight: Any
    ViewportWidth: Any
    ZoomChainMode: Any
    ZoomFactor: Any
    ZoomMode: Any
    ZoomSnapPoints: Any
    AnchorRequested: Any
    BringingIntoView: Any
    ExtentChanged: Any
    ScrollAnimationStarting: Any
    ScrollCompleted: Any
    StateChanged: Any
    ViewChanged: Any
    ZoomAnimationStarting: Any
    ZoomCompleted: Any
    BackgroundProperty: Any
    ComputedHorizontalScrollModeProperty: Any
    ComputedVerticalScrollModeProperty: Any
    ContentOrientationProperty: Any
    ContentProperty: Any
    HorizontalAnchorRatioProperty: Any
    HorizontalScrollChainModeProperty: Any
    HorizontalScrollModeProperty: Any
    HorizontalScrollRailModeProperty: Any
    IgnoredInputKindsProperty: Any
    MaxZoomFactorProperty: Any
    MinZoomFactorProperty: Any
    VerticalAnchorRatioProperty: Any
    VerticalScrollChainModeProperty: Any
    VerticalScrollModeProperty: Any
    VerticalScrollRailModeProperty: Any
    ZoomChainModeProperty: Any
    ZoomModeProperty: Any
    def ScrollTo(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def ScrollToWithOptions(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def ScrollBy(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def ScrollByWithOptions(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def AddScrollVelocity(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def ZoomTo(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def ZoomToWithOptions(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def ZoomBy(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def ZoomByWithOptions(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def AddZoomVelocity(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def add_ExtentChanged(self, _p0: Any = ...) -> Any: ...
    def remove_ExtentChanged(self, _p0: Any = ...) -> Any: ...
    def add_StateChanged(self, _p0: Any = ...) -> Any: ...
    def remove_StateChanged(self, _p0: Any = ...) -> Any: ...
    def add_ViewChanged(self, _p0: Any = ...) -> Any: ...
    def remove_ViewChanged(self, _p0: Any = ...) -> Any: ...
    def add_ScrollAnimationStarting(self, _p0: Any = ...) -> Any: ...
    def remove_ScrollAnimationStarting(self, _p0: Any = ...) -> Any: ...
    def add_ZoomAnimationStarting(self, _p0: Any = ...) -> Any: ...
    def remove_ZoomAnimationStarting(self, _p0: Any = ...) -> Any: ...
    def add_ScrollCompleted(self, _p0: Any = ...) -> Any: ...
    def remove_ScrollCompleted(self, _p0: Any = ...) -> Any: ...
    def add_ZoomCompleted(self, _p0: Any = ...) -> Any: ...
    def remove_ZoomCompleted(self, _p0: Any = ...) -> Any: ...
    def add_BringingIntoView(self, _p0: Any = ...) -> Any: ...
    def remove_BringingIntoView(self, _p0: Any = ...) -> Any: ...
    def add_AnchorRequested(self, _p0: Any = ...) -> Any: ...
    def remove_AnchorRequested(self, _p0: Any = ...) -> Any: ...
    def RegisterAnchorCandidate(self, _p0: Any = ...) -> Any: ...
    def UnregisterAnchorCandidate(self, _p0: Any = ...) -> Any: ...

class ScrollSnapPoint(ScrollSnapPointBase):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Value: Any

class ScrollSnapPointBase(SnapPointBase):
    Alignment: Any

class ScrollSnapPointsAlignment(int):
    Near: int
    Center: int
    Far: int

class ScrollingIndicatorMode(int):
    None_: int
    TouchIndicator: int
    MouseIndicator: int

class Selector(ItemsControl):
    IsSynchronizedWithCurrentItem: Any
    SelectedIndex: Any
    SelectedItem: Any
    SelectedValue: Any
    SelectedValuePath: Any
    SelectionChanged: Any
    IsSynchronizedWithCurrentItemProperty: Any
    SelectedIndexProperty: Any
    SelectedItemProperty: Any
    SelectedValuePathProperty: Any
    SelectedValueProperty: Any
    def add_SelectionChanged(self, _p0: Any = ...) -> Any: ...
    def remove_SelectionChanged(self, _p0: Any = ...) -> Any: ...
    @classmethod
    def GetIsSelectionActive(cls, _p0: Any = ...) -> Any: ...

class SelectorItem(ContentControl):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    IsSelected: Any
    IsSelectedProperty: Any

class SliderSnapsTo(int):
    StepValues: int
    Ticks: int

class SnapPointBase:
    ...

class SnapPointsAlignment(int):
    Near: int
    Center: int
    Far: int

class SplitViewTemplateSettings(DependencyObject):
    CompactPaneGridLength: Any
    NegativeOpenPaneLength: Any
    NegativeOpenPaneLengthMinusCompactLength: Any
    OpenPaneGridLength: Any
    OpenPaneLength: Any
    OpenPaneLengthMinusCompactLength: Any

class TabViewListView(ListView):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class Thumb(Control):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    IsDragging: Any
    DragCompleted: Any
    DragDelta: Any
    DragStarted: Any
    IsDraggingProperty: Any
    def add_DragStarted(self, _p0: Any = ...) -> Any: ...
    def remove_DragStarted(self, _p0: Any = ...) -> Any: ...
    def add_DragDelta(self, _p0: Any = ...) -> Any: ...
    def remove_DragDelta(self, _p0: Any = ...) -> Any: ...
    def add_DragCompleted(self, _p0: Any = ...) -> Any: ...
    def remove_DragCompleted(self, _p0: Any = ...) -> Any: ...
    def CancelDrag(self) -> Any: ...

class TickBar(FrameworkElement):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Fill: Any
    FillProperty: Any

class TickPlacement(int):
    None_: int
    TopLeft: int
    BottomRight: int
    Outside: int
    Inline: int

class ToggleButton(ButtonBase):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    IsChecked: Any
    IsThreeState: Any
    Checked: Any
    Indeterminate: Any
    Unchecked: Any
    IsCheckedProperty: Any
    IsThreeStateProperty: Any
    def add_Checked(self, _p0: Any = ...) -> Any: ...
    def remove_Checked(self, _p0: Any = ...) -> Any: ...
    def add_Unchecked(self, _p0: Any = ...) -> Any: ...
    def remove_Unchecked(self, _p0: Any = ...) -> Any: ...
    def add_Indeterminate(self, _p0: Any = ...) -> Any: ...
    def remove_Indeterminate(self, _p0: Any = ...) -> Any: ...
    def OnToggle(self) -> Any: ...

class ToggleSwitchTemplateSettings(DependencyObject):
    CurtainCurrentToOffOffset: Any
    CurtainCurrentToOnOffset: Any
    CurtainOffToOnOffset: Any
    CurtainOnToOffOffset: Any
    KnobCurrentToOffOffset: Any
    KnobCurrentToOnOffset: Any
    KnobOffToOnOffset: Any
    KnobOnToOffOffset: Any

class ToolTipTemplateSettings(DependencyObject):
    FromHorizontalOffset: Any
    FromVerticalOffset: Any

class ZoomSnapPoint(ZoomSnapPointBase):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Value: Any

class ZoomSnapPointBase(SnapPointBase):
    ...
