# Auto-generated type stubs for win32more
# Generated by winui3/tools/generate_win32more_stubs.py
# Property types are typed as Any; the goal is attribute existence,
# not full type safety for win32more internals.

from typing import Any

from win32more.Microsoft.UI.Xaml.Media import ImageSource

class BitmapCreateOptions(int):
    None_: int
    IgnoreImageCache: int

class BitmapImage(BitmapSource):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    AutoPlay: Any
    CreateOptions: Any
    DecodePixelHeight: Any
    DecodePixelType: Any
    DecodePixelWidth: Any
    IsAnimatedBitmap: Any
    IsPlaying: Any
    UriSource: Any
    DownloadProgress: Any
    ImageFailed: Any
    ImageOpened: Any
    AutoPlayProperty: Any
    CreateOptionsProperty: Any
    DecodePixelHeightProperty: Any
    DecodePixelTypeProperty: Any
    DecodePixelWidthProperty: Any
    IsAnimatedBitmapProperty: Any
    IsPlayingProperty: Any
    UriSourceProperty: Any
    @classmethod
    def CreateInstanceWithUriSource(cls, _p0: Any = ...) -> Any: ...
    def add_DownloadProgress(self, _p0: Any = ...) -> Any: ...
    def remove_DownloadProgress(self, _p0: Any = ...) -> Any: ...
    def add_ImageOpened(self, _p0: Any = ...) -> Any: ...
    def remove_ImageOpened(self, _p0: Any = ...) -> Any: ...
    def add_ImageFailed(self, _p0: Any = ...) -> Any: ...
    def remove_ImageFailed(self, _p0: Any = ...) -> Any: ...
    def Play(self) -> Any: ...
    def Stop(self) -> Any: ...

class BitmapSource(ImageSource):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    PixelHeight: Any
    PixelWidth: Any
    PixelHeightProperty: Any
    PixelWidthProperty: Any
    def SetSource(self, _p0: Any = ...) -> Any: ...
    def SetSourceAsync(self, _p0: Any = ...) -> Any: ...

class DecodePixelType(int):
    Physical: int
    Logical: int

class DownloadProgressEventArgs:
    Progress: Any

class DownloadProgressEventHandler:
    def Invoke(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class IBitmapImage:
    AutoPlay: Any
    CreateOptions: Any
    DecodePixelHeight: Any
    DecodePixelType: Any
    DecodePixelWidth: Any
    IsAnimatedBitmap: Any
    IsPlaying: Any
    UriSource: Any
    DownloadProgress: Any
    ImageFailed: Any
    ImageOpened: Any
    def add_DownloadProgress(self, _p0: Any = ...) -> Any: ...
    def remove_DownloadProgress(self, _p0: Any = ...) -> Any: ...
    def add_ImageOpened(self, _p0: Any = ...) -> Any: ...
    def remove_ImageOpened(self, _p0: Any = ...) -> Any: ...
    def add_ImageFailed(self, _p0: Any = ...) -> Any: ...
    def remove_ImageFailed(self, _p0: Any = ...) -> Any: ...
    def Play(self) -> Any: ...
    def Stop(self) -> Any: ...

class IBitmapImageStatics:
    AutoPlayProperty: Any
    CreateOptionsProperty: Any
    DecodePixelHeightProperty: Any
    DecodePixelTypeProperty: Any
    DecodePixelWidthProperty: Any
    IsAnimatedBitmapProperty: Any
    IsPlayingProperty: Any
    UriSourceProperty: Any

class IBitmapSource:
    PixelHeight: Any
    PixelWidth: Any
    def SetSource(self, _p0: Any = ...) -> Any: ...
    def SetSourceAsync(self, _p0: Any = ...) -> Any: ...

class IBitmapSourceStatics:
    PixelHeightProperty: Any
    PixelWidthProperty: Any

class IDownloadProgressEventArgs:
    Progress: Any

class IRenderTargetBitmap:
    PixelHeight: Any
    PixelWidth: Any
    def RenderAsync(self, _p0: Any = ...) -> Any: ...
    def RenderToSizeAsync(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def GetPixelsAsync(self) -> Any: ...

class IRenderTargetBitmapStatics:
    PixelHeightProperty: Any
    PixelWidthProperty: Any

class ISvgImageSource:
    RasterizePixelHeight: Any
    RasterizePixelWidth: Any
    UriSource: Any
    OpenFailed: Any
    Opened: Any
    def add_Opened(self, _p0: Any = ...) -> Any: ...
    def remove_Opened(self, _p0: Any = ...) -> Any: ...
    def add_OpenFailed(self, _p0: Any = ...) -> Any: ...
    def remove_OpenFailed(self, _p0: Any = ...) -> Any: ...
    def SetSourceAsync(self, _p0: Any = ...) -> Any: ...

class ISvgImageSourceFailedEventArgs:
    Status: Any

class ISvgImageSourceStatics:
    RasterizePixelHeightProperty: Any
    RasterizePixelWidthProperty: Any
    UriSourceProperty: Any

class IWriteableBitmap:
    PixelBuffer: Any
    def Invalidate(self) -> Any: ...

class RenderTargetBitmap(ImageSource):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    PixelHeight: Any
    PixelWidth: Any
    PixelHeightProperty: Any
    PixelWidthProperty: Any
    def RenderAsync(self, _p0: Any = ...) -> Any: ...
    def RenderToSizeAsync(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def GetPixelsAsync(self) -> Any: ...

class SoftwareBitmapSource(ImageSource):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def SetBitmapAsync(self, _p0: Any = ...) -> Any: ...
    def Close(self) -> Any: ...

class SurfaceImageSource(ImageSource):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @classmethod
    def CreateInstanceWithDimensions(cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...) -> Any: ...
    @classmethod
    def CreateInstanceWithDimensionsAndOpacity(cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ..., _p4: Any = ...) -> Any: ...

class SvgImageSource(ImageSource):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    RasterizePixelHeight: Any
    RasterizePixelWidth: Any
    UriSource: Any
    OpenFailed: Any
    Opened: Any
    RasterizePixelHeightProperty: Any
    RasterizePixelWidthProperty: Any
    UriSourceProperty: Any
    @classmethod
    def CreateInstanceWithUriSource(cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def add_Opened(self, _p0: Any = ...) -> Any: ...
    def remove_Opened(self, _p0: Any = ...) -> Any: ...
    def add_OpenFailed(self, _p0: Any = ...) -> Any: ...
    def remove_OpenFailed(self, _p0: Any = ...) -> Any: ...
    def SetSourceAsync(self, _p0: Any = ...) -> Any: ...

class SvgImageSourceFailedEventArgs:
    Status: Any

class SvgImageSourceLoadStatus(int):
    Success: int
    NetworkError: int
    InvalidFormat: int
    Other: int

class SvgImageSourceOpenedEventArgs:
    ...

class VirtualSurfaceImageSource(SurfaceImageSource):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @classmethod
    def CreateInstanceWithDimensions(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def CreateInstanceWithDimensionsAndOpacity(cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...

class WriteableBitmap(BitmapSource):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    PixelBuffer: Any
    @classmethod
    def CreateInstanceWithDimensions(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def Invalidate(self) -> Any: ...

class XamlRenderingBackgroundTask:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def OnRun(self, _p0: Any = ...) -> Any: ...
