# Auto-generated type stubs for win32more
# Generated by winui3/tools/generate_win32more_stubs.py
# Property types are typed as Any; the goal is attribute existence,
# not full type safety for win32more internals.

from typing import Any

from win32more.Microsoft.UI.Xaml import DependencyObject, TriggerAction

class AddDeleteThemeTransition(Transition):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class BackEase(EasingFunctionBase):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Amplitude: Any
    AmplitudeProperty: Any

class BasicConnectedAnimationConfiguration(ConnectedAnimationConfiguration):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class BeginStoryboard(TriggerAction):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Storyboard: Any
    StoryboardProperty: Any

class BounceEase(EasingFunctionBase):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Bounces: Any
    Bounciness: Any
    BouncesProperty: Any
    BouncinessProperty: Any

class CircleEase(EasingFunctionBase):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class ClockState(int):
    Active: int
    Filling: int
    Stopped: int

class ColorAnimation(Timeline):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    By: Any
    EasingFunction: Any
    EnableDependentAnimation: Any
    From: Any
    To: Any
    ByProperty: Any
    EasingFunctionProperty: Any
    EnableDependentAnimationProperty: Any
    FromProperty: Any
    ToProperty: Any

class ColorAnimationUsingKeyFrames(Timeline):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    EnableDependentAnimation: Any
    KeyFrames: Any
    EnableDependentAnimationProperty: Any

class ColorKeyFrame(DependencyObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    KeyTime: Any
    Value: Any
    KeyTimeProperty: Any
    ValueProperty: Any

class ColorKeyFrameCollection:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any
    def GetAt(self, _p0: Any = ...) -> Any: ...
    def GetView(self) -> Any: ...
    def IndexOf(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def SetAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def InsertAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def RemoveAt(self, _p0: Any = ...) -> Any: ...
    def Append(self, _p0: Any = ...) -> Any: ...
    def RemoveAtEnd(self) -> Any: ...
    def Clear(self) -> Any: ...
    def GetMany(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def ReplaceAll(self, _p0: Any = ...) -> Any: ...
    def First(self) -> Any: ...

class CommonNavigationTransitionInfo(NavigationTransitionInfo):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    IsStaggeringEnabled: Any
    IsStaggerElementProperty: Any
    IsStaggeringEnabledProperty: Any
    @classmethod
    def GetIsStaggerElement(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def SetIsStaggerElement(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class ConnectedAnimation:
    Configuration: Any
    IsScaleAnimationEnabled: Any
    Completed: Any
    def add_Completed(self, _p0: Any = ...) -> Any: ...
    def remove_Completed(self, _p0: Any = ...) -> Any: ...
    def TryStart(self, _p0: Any = ...) -> Any: ...
    def TryStartWithCoordinatedElements(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def Cancel(self) -> Any: ...
    def SetAnimationComponent(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class ConnectedAnimationComponent(int):
    OffsetX: int
    OffsetY: int
    CrossFade: int
    Scale: int

class ConnectedAnimationConfiguration:
    ...

class ConnectedAnimationService:
    DefaultDuration: Any
    DefaultEasingFunction: Any
    def PrepareToAnimate(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetAnimation(self, _p0: Any = ...) -> Any: ...
    @classmethod
    def GetForCurrentView(cls) -> Any: ...

class ContentThemeTransition(Transition):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    HorizontalOffset: Any
    VerticalOffset: Any
    HorizontalOffsetProperty: Any
    VerticalOffsetProperty: Any

class ContinuumNavigationTransitionInfo(NavigationTransitionInfo):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    ExitElement: Any
    ExitElementContainerProperty: Any
    ExitElementProperty: Any
    IsEntranceElementProperty: Any
    IsExitElementProperty: Any
    @classmethod
    def GetIsEntranceElement(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def SetIsEntranceElement(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def GetIsExitElement(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def SetIsExitElement(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def GetExitElementContainer(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def SetExitElementContainer(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class CubicEase(EasingFunctionBase):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class DirectConnectedAnimationConfiguration(ConnectedAnimationConfiguration):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class DiscreteColorKeyFrame(ColorKeyFrame):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class DiscreteDoubleKeyFrame(DoubleKeyFrame):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class DiscreteObjectKeyFrame(ObjectKeyFrame):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class DiscretePointKeyFrame(PointKeyFrame):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class DoubleAnimation(Timeline):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    By: Any
    EasingFunction: Any
    EnableDependentAnimation: Any
    From: Any
    To: Any
    ByProperty: Any
    EasingFunctionProperty: Any
    EnableDependentAnimationProperty: Any
    FromProperty: Any
    ToProperty: Any

class DoubleAnimationUsingKeyFrames(Timeline):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    EnableDependentAnimation: Any
    KeyFrames: Any
    EnableDependentAnimationProperty: Any

class DoubleKeyFrame(DependencyObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    KeyTime: Any
    Value: Any
    KeyTimeProperty: Any
    ValueProperty: Any

class DoubleKeyFrameCollection:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any
    def GetAt(self, _p0: Any = ...) -> Any: ...
    def GetView(self) -> Any: ...
    def IndexOf(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def SetAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def InsertAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def RemoveAt(self, _p0: Any = ...) -> Any: ...
    def Append(self, _p0: Any = ...) -> Any: ...
    def RemoveAtEnd(self) -> Any: ...
    def Clear(self) -> Any: ...
    def GetMany(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def ReplaceAll(self, _p0: Any = ...) -> Any: ...
    def First(self) -> Any: ...

class DragItemThemeAnimation(Timeline):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    TargetName: Any
    TargetNameProperty: Any

class DragOverThemeAnimation(Timeline):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Direction: Any
    TargetName: Any
    ToOffset: Any
    DirectionProperty: Any
    TargetNameProperty: Any
    ToOffsetProperty: Any

class DrillInNavigationTransitionInfo(NavigationTransitionInfo):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class DrillInThemeAnimation(Timeline):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    EntranceTarget: Any
    EntranceTargetName: Any
    ExitTarget: Any
    ExitTargetName: Any
    EntranceTargetNameProperty: Any
    EntranceTargetProperty: Any
    ExitTargetNameProperty: Any
    ExitTargetProperty: Any

class DrillOutThemeAnimation(Timeline):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    EntranceTarget: Any
    EntranceTargetName: Any
    ExitTarget: Any
    ExitTargetName: Any
    EntranceTargetNameProperty: Any
    EntranceTargetProperty: Any
    ExitTargetNameProperty: Any
    ExitTargetProperty: Any

class DropTargetItemThemeAnimation(Timeline):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    TargetName: Any
    TargetNameProperty: Any

class EasingColorKeyFrame(ColorKeyFrame):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    EasingFunction: Any
    EasingFunctionProperty: Any

class EasingDoubleKeyFrame(DoubleKeyFrame):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    EasingFunction: Any
    EasingFunctionProperty: Any

class EasingFunctionBase(DependencyObject):
    EasingMode: Any
    EasingModeProperty: Any
    def Ease(self, _p0: Any = ...) -> Any: ...

class EasingMode(int):
    EaseOut: int
    EaseIn: int
    EaseInOut: int

class EasingPointKeyFrame(PointKeyFrame):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    EasingFunction: Any
    EasingFunctionProperty: Any

class EdgeUIThemeTransition(Transition):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Edge: Any
    EdgeProperty: Any

class ElasticEase(EasingFunctionBase):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Oscillations: Any
    Springiness: Any
    OscillationsProperty: Any
    SpringinessProperty: Any

class EntranceNavigationTransitionInfo(NavigationTransitionInfo):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    IsTargetElementProperty: Any
    @classmethod
    def GetIsTargetElement(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def SetIsTargetElement(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class EntranceThemeTransition(Transition):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    FromHorizontalOffset: Any
    FromVerticalOffset: Any
    IsStaggeringEnabled: Any
    FromHorizontalOffsetProperty: Any
    FromVerticalOffsetProperty: Any
    IsStaggeringEnabledProperty: Any

class ExponentialEase(EasingFunctionBase):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Exponent: Any
    ExponentProperty: Any

class FadeInThemeAnimation(Timeline):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    TargetName: Any
    TargetNameProperty: Any

class FadeOutThemeAnimation(Timeline):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    TargetName: Any
    TargetNameProperty: Any

class FillBehavior(int):
    HoldEnd: int
    Stop: int

class GravityConnectedAnimationConfiguration(ConnectedAnimationConfiguration):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    IsShadowEnabled: Any

class IBackEase:
    Amplitude: Any

class IBackEaseStatics:
    AmplitudeProperty: Any

class IBeginStoryboard:
    Storyboard: Any

class IBeginStoryboardStatics:
    StoryboardProperty: Any

class IBounceEase:
    Bounces: Any
    Bounciness: Any

class IBounceEaseStatics:
    BouncesProperty: Any
    BouncinessProperty: Any

class IColorAnimation:
    By: Any
    EasingFunction: Any
    EnableDependentAnimation: Any
    From: Any
    To: Any

class IColorAnimationStatics:
    ByProperty: Any
    EasingFunctionProperty: Any
    EnableDependentAnimationProperty: Any
    FromProperty: Any
    ToProperty: Any

class IColorAnimationUsingKeyFrames:
    EnableDependentAnimation: Any
    KeyFrames: Any

class IColorAnimationUsingKeyFramesStatics:
    EnableDependentAnimationProperty: Any

class IColorKeyFrame:
    KeyTime: Any
    Value: Any

class IColorKeyFrameStatics:
    KeyTimeProperty: Any
    ValueProperty: Any

class ICommonNavigationTransitionInfo:
    IsStaggeringEnabled: Any

class ICommonNavigationTransitionInfoStatics:
    IsStaggerElementProperty: Any
    IsStaggeringEnabledProperty: Any
    def GetIsStaggerElement(self, _p0: Any = ...) -> Any: ...
    def SetIsStaggerElement(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class IConnectedAnimation:
    Configuration: Any
    IsScaleAnimationEnabled: Any
    Completed: Any
    def add_Completed(self, _p0: Any = ...) -> Any: ...
    def remove_Completed(self, _p0: Any = ...) -> Any: ...
    def TryStart(self, _p0: Any = ...) -> Any: ...
    def TryStartWithCoordinatedElements(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def Cancel(self) -> Any: ...
    def SetAnimationComponent(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class IConnectedAnimationService:
    DefaultDuration: Any
    DefaultEasingFunction: Any
    def PrepareToAnimate(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetAnimation(self, _p0: Any = ...) -> Any: ...

class IContentThemeTransition:
    HorizontalOffset: Any
    VerticalOffset: Any

class IContentThemeTransitionStatics:
    HorizontalOffsetProperty: Any
    VerticalOffsetProperty: Any

class IContinuumNavigationTransitionInfo:
    ExitElement: Any

class IContinuumNavigationTransitionInfoStatics:
    ExitElementContainerProperty: Any
    ExitElementProperty: Any
    IsEntranceElementProperty: Any
    IsExitElementProperty: Any
    def GetIsEntranceElement(self, _p0: Any = ...) -> Any: ...
    def SetIsEntranceElement(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetIsExitElement(self, _p0: Any = ...) -> Any: ...
    def SetIsExitElement(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetExitElementContainer(self, _p0: Any = ...) -> Any: ...
    def SetExitElementContainer(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class IDoubleAnimation:
    By: Any
    EasingFunction: Any
    EnableDependentAnimation: Any
    From: Any
    To: Any

class IDoubleAnimationStatics:
    ByProperty: Any
    EasingFunctionProperty: Any
    EnableDependentAnimationProperty: Any
    FromProperty: Any
    ToProperty: Any

class IDoubleAnimationUsingKeyFrames:
    EnableDependentAnimation: Any
    KeyFrames: Any

class IDoubleAnimationUsingKeyFramesStatics:
    EnableDependentAnimationProperty: Any

class IDoubleKeyFrame:
    KeyTime: Any
    Value: Any

class IDoubleKeyFrameStatics:
    KeyTimeProperty: Any
    ValueProperty: Any

class IDragItemThemeAnimation:
    TargetName: Any

class IDragItemThemeAnimationStatics:
    TargetNameProperty: Any

class IDragOverThemeAnimation:
    Direction: Any
    TargetName: Any
    ToOffset: Any

class IDragOverThemeAnimationStatics:
    DirectionProperty: Any
    TargetNameProperty: Any
    ToOffsetProperty: Any

class IDrillInThemeAnimation:
    EntranceTarget: Any
    EntranceTargetName: Any
    ExitTarget: Any
    ExitTargetName: Any

class IDrillInThemeAnimationStatics:
    EntranceTargetNameProperty: Any
    EntranceTargetProperty: Any
    ExitTargetNameProperty: Any
    ExitTargetProperty: Any

class IDrillOutThemeAnimation:
    EntranceTarget: Any
    EntranceTargetName: Any
    ExitTarget: Any
    ExitTargetName: Any

class IDrillOutThemeAnimationStatics:
    EntranceTargetNameProperty: Any
    EntranceTargetProperty: Any
    ExitTargetNameProperty: Any
    ExitTargetProperty: Any

class IDropTargetItemThemeAnimation:
    TargetName: Any

class IDropTargetItemThemeAnimationStatics:
    TargetNameProperty: Any

class IEasingColorKeyFrame:
    EasingFunction: Any

class IEasingColorKeyFrameStatics:
    EasingFunctionProperty: Any

class IEasingDoubleKeyFrame:
    EasingFunction: Any

class IEasingDoubleKeyFrameStatics:
    EasingFunctionProperty: Any

class IEasingFunctionBase:
    EasingMode: Any
    def Ease(self, _p0: Any = ...) -> Any: ...

class IEasingFunctionBaseStatics:
    EasingModeProperty: Any

class IEasingPointKeyFrame:
    EasingFunction: Any

class IEasingPointKeyFrameStatics:
    EasingFunctionProperty: Any

class IEdgeUIThemeTransition:
    Edge: Any

class IEdgeUIThemeTransitionStatics:
    EdgeProperty: Any

class IElasticEase:
    Oscillations: Any
    Springiness: Any

class IElasticEaseStatics:
    OscillationsProperty: Any
    SpringinessProperty: Any

class IEntranceNavigationTransitionInfoStatics:
    IsTargetElementProperty: Any
    def GetIsTargetElement(self, _p0: Any = ...) -> Any: ...
    def SetIsTargetElement(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class IEntranceThemeTransition:
    FromHorizontalOffset: Any
    FromVerticalOffset: Any
    IsStaggeringEnabled: Any

class IEntranceThemeTransitionStatics:
    FromHorizontalOffsetProperty: Any
    FromVerticalOffsetProperty: Any
    IsStaggeringEnabledProperty: Any

class IExponentialEase:
    Exponent: Any

class IExponentialEaseStatics:
    ExponentProperty: Any

class IFadeInThemeAnimation:
    TargetName: Any

class IFadeInThemeAnimationStatics:
    TargetNameProperty: Any

class IFadeOutThemeAnimation:
    TargetName: Any

class IFadeOutThemeAnimationStatics:
    TargetNameProperty: Any

class IGravityConnectedAnimationConfiguration:
    IsShadowEnabled: Any

class IKeySpline:
    ControlPoint1: Any
    ControlPoint2: Any

class INavigationThemeTransition:
    DefaultNavigationTransitionInfo: Any

class INavigationThemeTransitionStatics:
    DefaultNavigationTransitionInfoProperty: Any

class IObjectAnimationUsingKeyFrames:
    EnableDependentAnimation: Any
    KeyFrames: Any

class IObjectAnimationUsingKeyFramesStatics:
    EnableDependentAnimationProperty: Any

class IObjectKeyFrame:
    KeyTime: Any
    Value: Any

class IObjectKeyFrameStatics:
    KeyTimeProperty: Any
    ValueProperty: Any

class IPaneThemeTransition:
    Edge: Any

class IPaneThemeTransitionStatics:
    EdgeProperty: Any

class IPointAnimation:
    By: Any
    EasingFunction: Any
    EnableDependentAnimation: Any
    From: Any
    To: Any

class IPointAnimationStatics:
    ByProperty: Any
    EasingFunctionProperty: Any
    EnableDependentAnimationProperty: Any
    FromProperty: Any
    ToProperty: Any

class IPointAnimationUsingKeyFrames:
    EnableDependentAnimation: Any
    KeyFrames: Any

class IPointAnimationUsingKeyFramesStatics:
    EnableDependentAnimationProperty: Any

class IPointKeyFrame:
    KeyTime: Any
    Value: Any

class IPointKeyFrameStatics:
    KeyTimeProperty: Any
    ValueProperty: Any

class IPointerDownThemeAnimation:
    TargetName: Any

class IPointerDownThemeAnimationStatics:
    TargetNameProperty: Any

class IPointerUpThemeAnimation:
    TargetName: Any

class IPointerUpThemeAnimationStatics:
    TargetNameProperty: Any

class IPopInThemeAnimation:
    FromHorizontalOffset: Any
    FromVerticalOffset: Any
    TargetName: Any

class IPopInThemeAnimationStatics:
    FromHorizontalOffsetProperty: Any
    FromVerticalOffsetProperty: Any
    TargetNameProperty: Any

class IPopOutThemeAnimation:
    TargetName: Any

class IPopOutThemeAnimationStatics:
    TargetNameProperty: Any

class IPopupThemeTransition:
    FromHorizontalOffset: Any
    FromVerticalOffset: Any

class IPopupThemeTransitionStatics:
    FromHorizontalOffsetProperty: Any
    FromVerticalOffsetProperty: Any

class IPowerEase:
    Power: Any

class IPowerEaseStatics:
    PowerProperty: Any

class IRepeatBehaviorHelperStatics:
    Forever: Any
    def FromCount(self, _p0: Any = ...) -> Any: ...
    def FromDuration(self, _p0: Any = ...) -> Any: ...
    def GetHasCount(self, _p0: Any = ...) -> Any: ...
    def GetHasDuration(self, _p0: Any = ...) -> Any: ...
    def Equals(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class IRepositionThemeAnimation:
    FromHorizontalOffset: Any
    FromVerticalOffset: Any
    TargetName: Any

class IRepositionThemeAnimationStatics:
    FromHorizontalOffsetProperty: Any
    FromVerticalOffsetProperty: Any
    TargetNameProperty: Any

class IRepositionThemeTransition:
    IsStaggeringEnabled: Any

class IRepositionThemeTransitionStatics:
    IsStaggeringEnabledProperty: Any

class ISlideNavigationTransitionInfo:
    Effect: Any

class ISlideNavigationTransitionInfoStatics:
    EffectProperty: Any

class ISplineColorKeyFrame:
    KeySpline: Any

class ISplineColorKeyFrameStatics:
    KeySplineProperty: Any

class ISplineDoubleKeyFrame:
    KeySpline: Any

class ISplineDoubleKeyFrameStatics:
    KeySplineProperty: Any

class ISplinePointKeyFrame:
    KeySpline: Any

class ISplinePointKeyFrameStatics:
    KeySplineProperty: Any

class ISplitCloseThemeAnimation:
    ClosedLength: Any
    ClosedTarget: Any
    ClosedTargetName: Any
    ContentTarget: Any
    ContentTargetName: Any
    ContentTranslationDirection: Any
    ContentTranslationOffset: Any
    OffsetFromCenter: Any
    OpenedLength: Any
    OpenedTarget: Any
    OpenedTargetName: Any

class ISplitCloseThemeAnimationStatics:
    ClosedLengthProperty: Any
    ClosedTargetNameProperty: Any
    ClosedTargetProperty: Any
    ContentTargetNameProperty: Any
    ContentTargetProperty: Any
    ContentTranslationDirectionProperty: Any
    ContentTranslationOffsetProperty: Any
    OffsetFromCenterProperty: Any
    OpenedLengthProperty: Any
    OpenedTargetNameProperty: Any
    OpenedTargetProperty: Any

class ISplitOpenThemeAnimation:
    ClosedLength: Any
    ClosedTarget: Any
    ClosedTargetName: Any
    ContentTarget: Any
    ContentTargetName: Any
    ContentTranslationDirection: Any
    ContentTranslationOffset: Any
    OffsetFromCenter: Any
    OpenedLength: Any
    OpenedTarget: Any
    OpenedTargetName: Any

class ISplitOpenThemeAnimationStatics:
    ClosedLengthProperty: Any
    ClosedTargetNameProperty: Any
    ClosedTargetProperty: Any
    ContentTargetNameProperty: Any
    ContentTargetProperty: Any
    ContentTranslationDirectionProperty: Any
    ContentTranslationOffsetProperty: Any
    OffsetFromCenterProperty: Any
    OpenedLengthProperty: Any
    OpenedTargetNameProperty: Any
    OpenedTargetProperty: Any

class IStoryboard:
    Children: Any
    def Seek(self, _p0: Any = ...) -> Any: ...
    def Stop(self) -> Any: ...
    def Begin(self) -> Any: ...
    def Pause(self) -> Any: ...
    def Resume(self) -> Any: ...
    def GetCurrentState(self) -> Any: ...
    def GetCurrentTime(self) -> Any: ...
    def SeekAlignedToLastTick(self, _p0: Any = ...) -> Any: ...
    def SkipToFill(self) -> Any: ...

class IStoryboardStatics:
    TargetNameProperty: Any
    TargetPropertyProperty: Any
    def GetTargetProperty(self, _p0: Any = ...) -> Any: ...
    def SetTargetProperty(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetTargetName(self, _p0: Any = ...) -> Any: ...
    def SetTargetName(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def SetTarget(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class ISwipeBackThemeAnimation:
    FromHorizontalOffset: Any
    FromVerticalOffset: Any
    TargetName: Any

class ISwipeBackThemeAnimationStatics:
    FromHorizontalOffsetProperty: Any
    FromVerticalOffsetProperty: Any
    TargetNameProperty: Any

class ISwipeHintThemeAnimation:
    TargetName: Any
    ToHorizontalOffset: Any
    ToVerticalOffset: Any

class ISwipeHintThemeAnimationStatics:
    TargetNameProperty: Any
    ToHorizontalOffsetProperty: Any
    ToVerticalOffsetProperty: Any

class ITimeline:
    AutoReverse: Any
    BeginTime: Any
    Duration: Any
    FillBehavior: Any
    RepeatBehavior: Any
    SpeedRatio: Any
    Completed: Any
    def add_Completed(self, _p0: Any = ...) -> Any: ...
    def remove_Completed(self, _p0: Any = ...) -> Any: ...

class ITimelineStatics:
    AllowDependentAnimations: Any
    AutoReverseProperty: Any
    BeginTimeProperty: Any
    DurationProperty: Any
    FillBehaviorProperty: Any
    RepeatBehaviorProperty: Any
    SpeedRatioProperty: Any

class KeySpline(DependencyObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    ControlPoint1: Any
    ControlPoint2: Any

class KeyTime:
    TimeSpan: Any

class KeyTimeHelper:
    @classmethod
    def FromTimeSpan(cls, _p0: Any = ...) -> Any: ...

class LinearColorKeyFrame(ColorKeyFrame):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class LinearDoubleKeyFrame(DoubleKeyFrame):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class LinearPointKeyFrame(PointKeyFrame):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class NavigationThemeTransition(Transition):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    DefaultNavigationTransitionInfo: Any
    DefaultNavigationTransitionInfoProperty: Any

class NavigationTransitionInfo(DependencyObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def GetNavigationStateCore(self) -> Any: ...
    def SetNavigationStateCore(self, _p0: Any = ...) -> Any: ...

class ObjectAnimationUsingKeyFrames(Timeline):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    EnableDependentAnimation: Any
    KeyFrames: Any
    EnableDependentAnimationProperty: Any

class ObjectKeyFrame(DependencyObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    KeyTime: Any
    Value: Any
    KeyTimeProperty: Any
    ValueProperty: Any

class ObjectKeyFrameCollection:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any
    def GetAt(self, _p0: Any = ...) -> Any: ...
    def GetView(self) -> Any: ...
    def IndexOf(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def SetAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def InsertAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def RemoveAt(self, _p0: Any = ...) -> Any: ...
    def Append(self, _p0: Any = ...) -> Any: ...
    def RemoveAtEnd(self) -> Any: ...
    def Clear(self) -> Any: ...
    def GetMany(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def ReplaceAll(self, _p0: Any = ...) -> Any: ...
    def First(self) -> Any: ...

class PaneThemeTransition(Transition):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Edge: Any
    EdgeProperty: Any

class PointAnimation(Timeline):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    By: Any
    EasingFunction: Any
    EnableDependentAnimation: Any
    From: Any
    To: Any
    ByProperty: Any
    EasingFunctionProperty: Any
    EnableDependentAnimationProperty: Any
    FromProperty: Any
    ToProperty: Any

class PointAnimationUsingKeyFrames(Timeline):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    EnableDependentAnimation: Any
    KeyFrames: Any
    EnableDependentAnimationProperty: Any

class PointKeyFrame(DependencyObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    KeyTime: Any
    Value: Any
    KeyTimeProperty: Any
    ValueProperty: Any

class PointKeyFrameCollection:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any
    def GetAt(self, _p0: Any = ...) -> Any: ...
    def GetView(self) -> Any: ...
    def IndexOf(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def SetAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def InsertAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def RemoveAt(self, _p0: Any = ...) -> Any: ...
    def Append(self, _p0: Any = ...) -> Any: ...
    def RemoveAtEnd(self) -> Any: ...
    def Clear(self) -> Any: ...
    def GetMany(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def ReplaceAll(self, _p0: Any = ...) -> Any: ...
    def First(self) -> Any: ...

class PointerDownThemeAnimation(Timeline):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    TargetName: Any
    TargetNameProperty: Any

class PointerUpThemeAnimation(Timeline):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    TargetName: Any
    TargetNameProperty: Any

class PopInThemeAnimation(Timeline):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    FromHorizontalOffset: Any
    FromVerticalOffset: Any
    TargetName: Any
    FromHorizontalOffsetProperty: Any
    FromVerticalOffsetProperty: Any
    TargetNameProperty: Any

class PopOutThemeAnimation(Timeline):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    TargetName: Any
    TargetNameProperty: Any

class PopupThemeTransition(Transition):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    FromHorizontalOffset: Any
    FromVerticalOffset: Any
    FromHorizontalOffsetProperty: Any
    FromVerticalOffsetProperty: Any

class PowerEase(EasingFunctionBase):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Power: Any
    PowerProperty: Any

class QuadraticEase(EasingFunctionBase):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class QuarticEase(EasingFunctionBase):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class QuinticEase(EasingFunctionBase):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class ReorderThemeTransition(Transition):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class RepeatBehavior:
    Count: Any
    Duration: Any
    Type: Any

class RepeatBehaviorHelper:
    Forever: Any
    @classmethod
    def FromCount(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def FromDuration(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def GetHasCount(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def GetHasDuration(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def Equals(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class RepeatBehaviorType(int):
    Count: int
    Duration: int
    Forever: int

class RepositionThemeAnimation(Timeline):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    FromHorizontalOffset: Any
    FromVerticalOffset: Any
    TargetName: Any
    FromHorizontalOffsetProperty: Any
    FromVerticalOffsetProperty: Any
    TargetNameProperty: Any

class RepositionThemeTransition(Transition):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    IsStaggeringEnabled: Any
    IsStaggeringEnabledProperty: Any

class SineEase(EasingFunctionBase):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class SlideNavigationTransitionEffect(int):
    FromBottom: int
    FromLeft: int
    FromRight: int

class SlideNavigationTransitionInfo(NavigationTransitionInfo):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Effect: Any
    EffectProperty: Any

class SplineColorKeyFrame(ColorKeyFrame):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    KeySpline: Any
    KeySplineProperty: Any

class SplineDoubleKeyFrame(DoubleKeyFrame):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    KeySpline: Any
    KeySplineProperty: Any

class SplinePointKeyFrame(PointKeyFrame):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    KeySpline: Any
    KeySplineProperty: Any

class SplitCloseThemeAnimation(Timeline):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    ClosedLength: Any
    ClosedTarget: Any
    ClosedTargetName: Any
    ContentTarget: Any
    ContentTargetName: Any
    ContentTranslationDirection: Any
    ContentTranslationOffset: Any
    OffsetFromCenter: Any
    OpenedLength: Any
    OpenedTarget: Any
    OpenedTargetName: Any
    ClosedLengthProperty: Any
    ClosedTargetNameProperty: Any
    ClosedTargetProperty: Any
    ContentTargetNameProperty: Any
    ContentTargetProperty: Any
    ContentTranslationDirectionProperty: Any
    ContentTranslationOffsetProperty: Any
    OffsetFromCenterProperty: Any
    OpenedLengthProperty: Any
    OpenedTargetNameProperty: Any
    OpenedTargetProperty: Any

class SplitOpenThemeAnimation(Timeline):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    ClosedLength: Any
    ClosedTarget: Any
    ClosedTargetName: Any
    ContentTarget: Any
    ContentTargetName: Any
    ContentTranslationDirection: Any
    ContentTranslationOffset: Any
    OffsetFromCenter: Any
    OpenedLength: Any
    OpenedTarget: Any
    OpenedTargetName: Any
    ClosedLengthProperty: Any
    ClosedTargetNameProperty: Any
    ClosedTargetProperty: Any
    ContentTargetNameProperty: Any
    ContentTargetProperty: Any
    ContentTranslationDirectionProperty: Any
    ContentTranslationOffsetProperty: Any
    OffsetFromCenterProperty: Any
    OpenedLengthProperty: Any
    OpenedTargetNameProperty: Any
    OpenedTargetProperty: Any

class Storyboard(Timeline):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Children: Any
    TargetNameProperty: Any
    TargetPropertyProperty: Any
    def Seek(self, _p0: Any = ...) -> Any: ...
    def Stop(self) -> Any: ...
    def Begin(self) -> Any: ...
    def Pause(self) -> Any: ...
    def Resume(self) -> Any: ...
    def GetCurrentState(self) -> Any: ...
    def GetCurrentTime(self) -> Any: ...
    def SeekAlignedToLastTick(self, _p0: Any = ...) -> Any: ...
    def SkipToFill(self) -> Any: ...
    @classmethod
    def GetTargetProperty(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def SetTargetProperty(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def GetTargetName(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def SetTargetName(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def SetTarget(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class SuppressNavigationTransitionInfo(NavigationTransitionInfo):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class SwipeBackThemeAnimation(Timeline):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    FromHorizontalOffset: Any
    FromVerticalOffset: Any
    TargetName: Any
    FromHorizontalOffsetProperty: Any
    FromVerticalOffsetProperty: Any
    TargetNameProperty: Any

class SwipeHintThemeAnimation(Timeline):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    TargetName: Any
    ToHorizontalOffset: Any
    ToVerticalOffset: Any
    TargetNameProperty: Any
    ToHorizontalOffsetProperty: Any
    ToVerticalOffsetProperty: Any

class Timeline(DependencyObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    AutoReverse: Any
    BeginTime: Any
    Duration: Any
    FillBehavior: Any
    RepeatBehavior: Any
    SpeedRatio: Any
    Completed: Any
    AllowDependentAnimations: Any
    AutoReverseProperty: Any
    BeginTimeProperty: Any
    DurationProperty: Any
    FillBehaviorProperty: Any
    RepeatBehaviorProperty: Any
    SpeedRatioProperty: Any
    def add_Completed(self, _p0: Any = ...) -> Any: ...
    def remove_Completed(self, _p0: Any = ...) -> Any: ...

class TimelineCollection:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any
    def GetAt(self, _p0: Any = ...) -> Any: ...
    def GetView(self) -> Any: ...
    def IndexOf(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def SetAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def InsertAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def RemoveAt(self, _p0: Any = ...) -> Any: ...
    def Append(self, _p0: Any = ...) -> Any: ...
    def RemoveAtEnd(self) -> Any: ...
    def Clear(self) -> Any: ...
    def GetMany(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def ReplaceAll(self, _p0: Any = ...) -> Any: ...
    def First(self) -> Any: ...

class Transition(DependencyObject):
    ...

class TransitionCollection:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any
    def GetAt(self, _p0: Any = ...) -> Any: ...
    def GetView(self) -> Any: ...
    def IndexOf(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def SetAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def InsertAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def RemoveAt(self, _p0: Any = ...) -> Any: ...
    def Append(self, _p0: Any = ...) -> Any: ...
    def RemoveAtEnd(self) -> Any: ...
    def Clear(self) -> Any: ...
    def GetMany(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def ReplaceAll(self, _p0: Any = ...) -> Any: ...
    def First(self) -> Any: ...
