# Auto-generated type stubs for win32more
# Generated by winui3/tools/generate_win32more_stubs.py
# Property types are typed as Any; the goal is attribute existence,
# not full type safety for win32more internals.

from typing import Any

from win32more.Microsoft.UI.Xaml import DependencyObject, RoutedEventArgs

class AccessKeyDisplayDismissedEventArgs:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class AccessKeyDisplayRequestedEventArgs:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    PressedKeys: Any

class AccessKeyInvokedEventArgs:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Handled: Any

class AccessKeyManager:
    AreKeyTipsEnabled: Any
    IsDisplayModeEnabled: Any
    @classmethod
    def EnterDisplayModeForXamlRoot(cls, _p0: Any = ...) -> Any: ...
    def add_IsDisplayModeEnabledChanged(self, _p0: Any = ...) -> Any: ...
    def remove_IsDisplayModeEnabledChanged(self, _p0: Any = ...) -> Any: ...
    @classmethod
    def ExitDisplayMode(cls) -> Any: ...

class CanExecuteRequestedEventArgs:
    CanExecute: Any
    Parameter: Any

class CharacterReceivedRoutedEventArgs(RoutedEventArgs):
    Character: Any
    Handled: Any
    KeyStatus: Any

class ContextRequestedEventArgs(RoutedEventArgs):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Handled: Any
    def TryGetPosition(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class DoubleTappedEventHandler:
    def Invoke(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class DoubleTappedRoutedEventArgs(RoutedEventArgs):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Handled: Any
    PointerDeviceType: Any
    def GetPosition(self, _p0: Any = ...) -> Any: ...

class ExecuteRequestedEventArgs:
    Parameter: Any

class FindNextElementOptions:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    ExclusionRect: Any
    HintRect: Any
    SearchRoot: Any
    XYFocusNavigationStrategyOverride: Any

class FocusInputDeviceKind(int):
    None_: int
    Mouse: int
    Touch: int
    Pen: int
    Keyboard: int
    GameController: int

class FocusManager:
    def add_GotFocus(self, _p0: Any = ...) -> Any: ...
    def remove_GotFocus(self, _p0: Any = ...) -> Any: ...
    def add_LostFocus(self, _p0: Any = ...) -> Any: ...
    def remove_LostFocus(self, _p0: Any = ...) -> Any: ...
    def add_GettingFocus(self, _p0: Any = ...) -> Any: ...
    def remove_GettingFocus(self, _p0: Any = ...) -> Any: ...
    def add_LosingFocus(self, _p0: Any = ...) -> Any: ...
    def remove_LosingFocus(self, _p0: Any = ...) -> Any: ...
    @classmethod
    def TryFocusAsync(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def TryMoveFocusAsync(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def TryMoveFocusWithOptionsAsync(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def TryMoveFocusWithOptions(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def FindNextElement(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def FindFirstFocusableElement(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def FindLastFocusableElement(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def FindNextElementWithOptions(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def FindNextFocusableElement(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def FindNextFocusableElementWithHint(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def TryMoveFocus(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def GetFocusedElement(cls) -> Any: ...
    @classmethod
    def GetFocusedElementWithRoot(cls, _p0: Any = ...) -> Any: ...

class FocusManagerGotFocusEventArgs:
    CorrelationId: Any
    NewFocusedElement: Any

class FocusManagerLostFocusEventArgs:
    CorrelationId: Any
    OldFocusedElement: Any

class FocusMovementResult:
    Succeeded: Any

class FocusNavigationDirection(int):
    Next: int
    Previous: int
    Up: int
    Down: int
    Left: int
    Right: int
    None_: int

class GettingFocusEventArgs(RoutedEventArgs):
    Cancel: Any
    CorrelationId: Any
    Direction: Any
    FocusState: Any
    Handled: Any
    InputDevice: Any
    NewFocusedElement: Any
    OldFocusedElement: Any
    def TryCancel(self) -> Any: ...
    def TrySetNewFocusedElement(self, _p0: Any = ...) -> Any: ...

class HoldingEventHandler:
    def Invoke(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class HoldingRoutedEventArgs(RoutedEventArgs):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Handled: Any
    HoldingState: Any
    PointerDeviceType: Any
    def GetPosition(self, _p0: Any = ...) -> Any: ...

class IAccessKeyDisplayRequestedEventArgs:
    PressedKeys: Any

class IAccessKeyInvokedEventArgs:
    Handled: Any

class IAccessKeyManagerStatics:
    AreKeyTipsEnabled: Any
    IsDisplayModeEnabled: Any
    IsDisplayModeEnabledChanged: Any
    def add_IsDisplayModeEnabledChanged(self, _p0: Any = ...) -> Any: ...
    def remove_IsDisplayModeEnabledChanged(self, _p0: Any = ...) -> Any: ...
    def ExitDisplayMode(self) -> Any: ...

class ICanExecuteRequestedEventArgs:
    CanExecute: Any
    Parameter: Any

class ICharacterReceivedRoutedEventArgs:
    Character: Any
    Handled: Any
    KeyStatus: Any

class IContextRequestedEventArgs:
    Handled: Any
    def TryGetPosition(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class IDoubleTappedRoutedEventArgs:
    Handled: Any
    PointerDeviceType: Any
    def GetPosition(self, _p0: Any = ...) -> Any: ...

class IExecuteRequestedEventArgs:
    Parameter: Any

class IFindNextElementOptions:
    ExclusionRect: Any
    HintRect: Any
    SearchRoot: Any
    XYFocusNavigationStrategyOverride: Any

class IFocusManagerGotFocusEventArgs:
    CorrelationId: Any
    NewFocusedElement: Any

class IFocusManagerLostFocusEventArgs:
    CorrelationId: Any
    OldFocusedElement: Any

class IFocusMovementResult:
    Succeeded: Any

class IGettingFocusEventArgs:
    Cancel: Any
    CorrelationId: Any
    Direction: Any
    FocusState: Any
    Handled: Any
    InputDevice: Any
    NewFocusedElement: Any
    OldFocusedElement: Any
    def TryCancel(self) -> Any: ...
    def TrySetNewFocusedElement(self, _p0: Any = ...) -> Any: ...

class IHoldingRoutedEventArgs:
    Handled: Any
    HoldingState: Any
    PointerDeviceType: Any
    def GetPosition(self, _p0: Any = ...) -> Any: ...

class IInertiaExpansionBehavior:
    DesiredDeceleration: Any
    DesiredExpansion: Any

class IInertiaRotationBehavior:
    DesiredDeceleration: Any
    DesiredRotation: Any

class IInertiaTranslationBehavior:
    DesiredDeceleration: Any
    DesiredDisplacement: Any

class IInputScope:
    Names: Any

class IInputScopeName:
    NameValue: Any

class IKeyRoutedEventArgs:
    DeviceId: Any
    Handled: Any
    Key: Any
    KeyStatus: Any
    OriginalKey: Any

class IKeyboardAccelerator:
    IsEnabled: Any
    Key: Any
    Modifiers: Any
    ScopeOwner: Any
    Invoked: Any
    def add_Invoked(self, _p0: Any = ...) -> Any: ...
    def remove_Invoked(self, _p0: Any = ...) -> Any: ...

class IKeyboardAcceleratorInvokedEventArgs:
    Element: Any
    Handled: Any
    KeyboardAccelerator: Any

class IKeyboardAcceleratorStatics:
    IsEnabledProperty: Any
    KeyProperty: Any
    ModifiersProperty: Any
    ScopeOwnerProperty: Any

class ILosingFocusEventArgs:
    Cancel: Any
    CorrelationId: Any
    Direction: Any
    FocusState: Any
    Handled: Any
    InputDevice: Any
    NewFocusedElement: Any
    OldFocusedElement: Any
    def TryCancel(self) -> Any: ...
    def TrySetNewFocusedElement(self, _p0: Any = ...) -> Any: ...

class IManipulationCompletedRoutedEventArgs:
    Container: Any
    Cumulative: Any
    Handled: Any
    IsInertial: Any
    PointerDeviceType: Any
    Position: Any
    Velocities: Any

class IManipulationDeltaRoutedEventArgs:
    Container: Any
    Cumulative: Any
    Delta: Any
    Handled: Any
    IsInertial: Any
    PointerDeviceType: Any
    Position: Any
    Velocities: Any
    def Complete(self) -> Any: ...

class IManipulationInertiaStartingRoutedEventArgs:
    Container: Any
    Cumulative: Any
    Delta: Any
    ExpansionBehavior: Any
    Handled: Any
    PointerDeviceType: Any
    RotationBehavior: Any
    TranslationBehavior: Any
    Velocities: Any

class IManipulationPivot:
    Center: Any
    Radius: Any

class IManipulationStartedRoutedEventArgs:
    Container: Any
    Cumulative: Any
    Handled: Any
    PointerDeviceType: Any
    Position: Any
    def Complete(self) -> Any: ...

class IManipulationStartingRoutedEventArgs:
    Container: Any
    Handled: Any
    Mode: Any
    Pivot: Any

class INoFocusCandidateFoundEventArgs:
    Direction: Any
    Handled: Any
    InputDevice: Any

class IPointer:
    IsInContact: Any
    IsInRange: Any
    PointerDeviceType: Any
    PointerId: Any

class IPointerRoutedEventArgs:
    Handled: Any
    IsGenerated: Any
    KeyModifiers: Any
    Pointer: Any
    def GetCurrentPoint(self, _p0: Any = ...) -> Any: ...
    def GetIntermediatePoints(self, _p0: Any = ...) -> Any: ...

class IProcessKeyboardAcceleratorEventArgs:
    Handled: Any
    Key: Any
    Modifiers: Any

class IRightTappedRoutedEventArgs:
    Handled: Any
    PointerDeviceType: Any
    def GetPosition(self, _p0: Any = ...) -> Any: ...

class IStandardUICommand:
    Kind: Any

class IStandardUICommandStatics:
    KindProperty: Any

class ITappedRoutedEventArgs:
    Handled: Any
    PointerDeviceType: Any
    def GetPosition(self, _p0: Any = ...) -> Any: ...

class IXamlUICommand:
    AccessKey: Any
    Command: Any
    Description: Any
    IconSource: Any
    KeyboardAccelerators: Any
    Label: Any
    CanExecuteRequested: Any
    ExecuteRequested: Any
    def add_ExecuteRequested(self, _p0: Any = ...) -> Any: ...
    def remove_ExecuteRequested(self, _p0: Any = ...) -> Any: ...
    def add_CanExecuteRequested(self, _p0: Any = ...) -> Any: ...
    def remove_CanExecuteRequested(self, _p0: Any = ...) -> Any: ...
    def NotifyCanExecuteChanged(self) -> Any: ...

class IXamlUICommandStatics:
    AccessKeyProperty: Any
    CommandProperty: Any
    DescriptionProperty: Any
    IconSourceProperty: Any
    KeyboardAcceleratorsProperty: Any
    LabelProperty: Any

class InertiaExpansionBehavior:
    DesiredDeceleration: Any
    DesiredExpansion: Any

class InertiaRotationBehavior:
    DesiredDeceleration: Any
    DesiredRotation: Any

class InertiaTranslationBehavior:
    DesiredDeceleration: Any
    DesiredDisplacement: Any

class InputScope(DependencyObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Names: Any

class InputScopeName(DependencyObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    NameValue: Any

class InputScopeNameValue(int):
    Default: int
    Url: int
    EmailSmtpAddress: int
    PersonalFullName: int
    CurrencyAmountAndSymbol: int
    CurrencyAmount: int
    DateMonthNumber: int
    DateDayNumber: int
    DateYear: int
    Digits: int
    Number: int
    Password: int
    TelephoneNumber: int
    TelephoneCountryCode: int
    TelephoneAreaCode: int
    TelephoneLocalNumber: int
    TimeHour: int
    TimeMinutesOrSeconds: int
    NumberFullWidth: int
    AlphanumericHalfWidth: int
    AlphanumericFullWidth: int
    Hiragana: int
    KatakanaHalfWidth: int
    KatakanaFullWidth: int
    Hanja: int
    HangulHalfWidth: int
    HangulFullWidth: int
    Search: int
    Formula: int
    SearchIncremental: int
    ChineseHalfWidth: int
    ChineseFullWidth: int
    NativeScript: int
    Text: int
    Chat: int
    NameOrPhoneNumber: int
    EmailNameOrAddress: int
    Maps: int
    NumericPassword: int
    NumericPin: int
    AlphanumericPin: int
    FormulaNumber: int
    ChatWithoutEmoji: int

class KeyEventHandler:
    def Invoke(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class KeyRoutedEventArgs(RoutedEventArgs):
    DeviceId: Any
    Handled: Any
    Key: Any
    KeyStatus: Any
    OriginalKey: Any

class KeyTipPlacementMode(int):
    Auto: int
    Bottom: int
    Top: int
    Left: int
    Right: int
    Center: int
    Hidden: int

class KeyboardAccelerator(DependencyObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    IsEnabled: Any
    Key: Any
    Modifiers: Any
    ScopeOwner: Any
    Invoked: Any
    IsEnabledProperty: Any
    KeyProperty: Any
    ModifiersProperty: Any
    ScopeOwnerProperty: Any
    def add_Invoked(self, _p0: Any = ...) -> Any: ...
    def remove_Invoked(self, _p0: Any = ...) -> Any: ...

class KeyboardAcceleratorInvokedEventArgs:
    Element: Any
    Handled: Any
    KeyboardAccelerator: Any

class KeyboardAcceleratorPlacementMode(int):
    Auto: int
    Hidden: int

class KeyboardNavigationMode(int):
    Local: int
    Cycle: int
    Once: int

class LosingFocusEventArgs(RoutedEventArgs):
    Cancel: Any
    CorrelationId: Any
    Direction: Any
    FocusState: Any
    Handled: Any
    InputDevice: Any
    NewFocusedElement: Any
    OldFocusedElement: Any
    def TryCancel(self) -> Any: ...
    def TrySetNewFocusedElement(self, _p0: Any = ...) -> Any: ...

class ManipulationCompletedEventHandler:
    def Invoke(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class ManipulationCompletedRoutedEventArgs(RoutedEventArgs):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Container: Any
    Cumulative: Any
    Handled: Any
    IsInertial: Any
    PointerDeviceType: Any
    Position: Any
    Velocities: Any

class ManipulationDeltaEventHandler:
    def Invoke(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class ManipulationDeltaRoutedEventArgs(RoutedEventArgs):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Container: Any
    Cumulative: Any
    Delta: Any
    Handled: Any
    IsInertial: Any
    PointerDeviceType: Any
    Position: Any
    Velocities: Any
    def Complete(self) -> Any: ...

class ManipulationInertiaStartingEventHandler:
    def Invoke(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class ManipulationInertiaStartingRoutedEventArgs(RoutedEventArgs):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Container: Any
    Cumulative: Any
    Delta: Any
    ExpansionBehavior: Any
    Handled: Any
    PointerDeviceType: Any
    RotationBehavior: Any
    TranslationBehavior: Any
    Velocities: Any

class ManipulationModes(int):
    None_: int
    TranslateX: int
    TranslateY: int
    TranslateRailsX: int
    TranslateRailsY: int
    Rotate: int
    Scale: int
    TranslateInertia: int
    RotateInertia: int
    ScaleInertia: int
    All: int
    System: int

class ManipulationPivot:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Center: Any
    Radius: Any
    @classmethod
    def CreateInstanceWithCenterAndRadius(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class ManipulationStartedEventHandler:
    def Invoke(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class ManipulationStartedRoutedEventArgs(RoutedEventArgs):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Container: Any
    Cumulative: Any
    Handled: Any
    PointerDeviceType: Any
    Position: Any
    def Complete(self) -> Any: ...

class ManipulationStartingEventHandler:
    def Invoke(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class ManipulationStartingRoutedEventArgs(RoutedEventArgs):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Container: Any
    Handled: Any
    Mode: Any
    Pivot: Any

class NoFocusCandidateFoundEventArgs(RoutedEventArgs):
    Direction: Any
    Handled: Any
    InputDevice: Any

class Pointer:
    IsInContact: Any
    IsInRange: Any
    PointerDeviceType: Any
    PointerId: Any

class PointerEventHandler:
    def Invoke(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class PointerRoutedEventArgs(RoutedEventArgs):
    Handled: Any
    IsGenerated: Any
    KeyModifiers: Any
    Pointer: Any
    def GetCurrentPoint(self, _p0: Any = ...) -> Any: ...
    def GetIntermediatePoints(self, _p0: Any = ...) -> Any: ...

class ProcessKeyboardAcceleratorEventArgs:
    Handled: Any
    Key: Any
    Modifiers: Any

class RightTappedEventHandler:
    def Invoke(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class RightTappedRoutedEventArgs(RoutedEventArgs):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Handled: Any
    PointerDeviceType: Any
    def GetPosition(self, _p0: Any = ...) -> Any: ...

class StandardUICommand(XamlUICommand):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Kind: Any
    KindProperty: Any
    @classmethod
    def CreateInstanceWithKind(cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...

class StandardUICommandKind(int):
    None_: int
    Cut: int
    Copy: int
    Paste: int
    SelectAll: int
    Delete: int
    Share: int
    Save: int
    Open: int
    Close: int
    Pause: int
    Play: int
    Stop: int
    Forward: int
    Backward: int
    Undo: int
    Redo: int

class TappedEventHandler:
    def Invoke(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class TappedRoutedEventArgs(RoutedEventArgs):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Handled: Any
    PointerDeviceType: Any
    def GetPosition(self, _p0: Any = ...) -> Any: ...

class XYFocusKeyboardNavigationMode(int):
    Auto: int
    Enabled: int
    Disabled: int

class XYFocusNavigationStrategy(int):
    Auto: int
    Projection: int
    NavigationDirectionDistance: int
    RectilinearDistance: int

class XYFocusNavigationStrategyOverride(int):
    None_: int
    Auto: int
    Projection: int
    NavigationDirectionDistance: int
    RectilinearDistance: int

class XamlUICommand(DependencyObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    AccessKey: Any
    Command: Any
    Description: Any
    IconSource: Any
    KeyboardAccelerators: Any
    Label: Any
    CanExecuteChanged: Any
    CanExecuteRequested: Any
    ExecuteRequested: Any
    AccessKeyProperty: Any
    CommandProperty: Any
    DescriptionProperty: Any
    IconSourceProperty: Any
    KeyboardAcceleratorsProperty: Any
    LabelProperty: Any
    def add_ExecuteRequested(self, _p0: Any = ...) -> Any: ...
    def remove_ExecuteRequested(self, _p0: Any = ...) -> Any: ...
    def add_CanExecuteRequested(self, _p0: Any = ...) -> Any: ...
    def remove_CanExecuteRequested(self, _p0: Any = ...) -> Any: ...
    def NotifyCanExecuteChanged(self) -> Any: ...
    def add_CanExecuteChanged(self, _p0: Any = ...) -> Any: ...
    def remove_CanExecuteChanged(self, _p0: Any = ...) -> Any: ...
    def CanExecute(self, _p0: Any = ...) -> Any: ...
    def Execute(self, _p0: Any = ...) -> Any: ...
