# Auto-generated type stubs for win32more
# Generated by winui3/tools/generate_win32more_stubs.py
# Property types are typed as Any; the goal is attribute existence,
# not full type safety for win32more internals.

from typing import Any

class CaretType(int):
    Normal: int
    Null: int

class ContentLinkInfo:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    DisplayText: Any
    Id: Any
    LinkContentKind: Any
    SecondaryText: Any
    Uri: Any

class FindOptions(int):
    None_: int
    Word: int
    Case: int

class FontStretch(int):
    Undefined: int
    UltraCondensed: int
    ExtraCondensed: int
    Condensed: int
    SemiCondensed: int
    Normal: int
    SemiExpanded: int
    Expanded: int
    ExtraExpanded: int
    UltraExpanded: int

class FontStyle(int):
    Normal: int
    Oblique: int
    Italic: int

class FontWeight:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Weight: Any

class FontWeights:
    Black: Any
    Bold: Any
    ExtraBlack: Any
    ExtraBold: Any
    ExtraLight: Any
    Light: Any
    Medium: Any
    Normal: Any
    SemiBold: Any
    SemiLight: Any
    Thin: Any

class FormatEffect(int):
    Off: int
    On: int
    Toggle: int
    Undefined: int

class HorizontalCharacterAlignment(int):
    Left: int
    Right: int
    Center: int

class IContentLinkInfo:
    DisplayText: Any
    Id: Any
    LinkContentKind: Any
    SecondaryText: Any
    Uri: Any

class IFontWeightsStatics:
    Black: Any
    Bold: Any
    ExtraBlack: Any
    ExtraBold: Any
    ExtraLight: Any
    Light: Any
    Medium: Any
    Normal: Any
    SemiBold: Any
    SemiLight: Any
    Thin: Any

class IRichEditTextRange:
    ContentLinkInfo: Any

class ITextCharacterFormat:
    AllCaps: Any
    BackgroundColor: Any
    Bold: Any
    FontStretch: Any
    FontStyle: Any
    ForegroundColor: Any
    Hidden: Any
    Italic: Any
    Kerning: Any
    LanguageTag: Any
    LinkType: Any
    Name: Any
    Outline: Any
    Position: Any
    ProtectedText: Any
    Size: Any
    SmallCaps: Any
    Spacing: Any
    Strikethrough: Any
    Subscript: Any
    Superscript: Any
    TextScript: Any
    Underline: Any
    Weight: Any
    def SetClone(self, _p0: Any = ...) -> Any: ...
    def GetClone(self) -> Any: ...
    def IsEqual(self, _p0: Any = ...) -> Any: ...

class ITextConstantsStatics:
    AutoColor: Any
    MaxUnitCount: Any
    MinUnitCount: Any
    UndefinedColor: Any
    UndefinedFloatValue: Any
    UndefinedFontStretch: Any
    UndefinedFontStyle: Any
    UndefinedInt32Value: Any

class ITextDocument:
    CaretType: Any
    DefaultTabStop: Any
    Selection: Any
    UndoLimit: Any
    def CanCopy(self) -> Any: ...
    def CanPaste(self) -> Any: ...
    def CanRedo(self) -> Any: ...
    def CanUndo(self) -> Any: ...
    def ApplyDisplayUpdates(self) -> Any: ...
    def BatchDisplayUpdates(self) -> Any: ...
    def BeginUndoGroup(self) -> Any: ...
    def EndUndoGroup(self) -> Any: ...
    def GetDefaultCharacterFormat(self) -> Any: ...
    def GetDefaultParagraphFormat(self) -> Any: ...
    def GetRange(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetRangeFromPoint(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetText(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def LoadFromStream(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def Redo(self) -> Any: ...
    def SaveToStream(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def SetDefaultCharacterFormat(self, _p0: Any = ...) -> Any: ...
    def SetDefaultParagraphFormat(self, _p0: Any = ...) -> Any: ...
    def SetText(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def Undo(self) -> Any: ...

class ITextDocument2:
    AlignmentIncludesTrailingWhitespace: Any
    IgnoreTrailingCharacterSpacing: Any

class ITextParagraphFormat:
    Alignment: Any
    FirstLineIndent: Any
    KeepTogether: Any
    KeepWithNext: Any
    LeftIndent: Any
    LineSpacing: Any
    LineSpacingRule: Any
    ListAlignment: Any
    ListLevelIndex: Any
    ListStart: Any
    ListStyle: Any
    ListTab: Any
    ListType: Any
    NoLineNumber: Any
    PageBreakBefore: Any
    RightIndent: Any
    RightToLeft: Any
    SpaceAfter: Any
    SpaceBefore: Any
    Style: Any
    TabCount: Any
    WidowControl: Any
    def AddTab(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def ClearAllTabs(self) -> Any: ...
    def DeleteTab(self, _p0: Any = ...) -> Any: ...
    def GetClone(self) -> Any: ...
    def GetTab(
        self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...
    ) -> Any: ...
    def IsEqual(self, _p0: Any = ...) -> Any: ...
    def SetClone(self, _p0: Any = ...) -> Any: ...
    def SetIndents(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def SetLineSpacing(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class ITextRange:
    Character: Any
    CharacterFormat: Any
    EndPosition: Any
    FormattedText: Any
    Gravity: Any
    Length: Any
    Link: Any
    ParagraphFormat: Any
    StartPosition: Any
    StoryLength: Any
    Text: Any
    def CanPaste(self, _p0: Any = ...) -> Any: ...
    def ChangeCase(self, _p0: Any = ...) -> Any: ...
    def Collapse(self, _p0: Any = ...) -> Any: ...
    def Copy(self) -> Any: ...
    def Cut(self) -> Any: ...
    def Delete(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def EndOf(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def Expand(self, _p0: Any = ...) -> Any: ...
    def FindText(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def GetCharacterUtf32(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetClone(self) -> Any: ...
    def GetIndex(self, _p0: Any = ...) -> Any: ...
    def GetPoint(
        self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...
    ) -> Any: ...
    def GetRect(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def GetText(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetTextViaStream(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def InRange(self, _p0: Any = ...) -> Any: ...
    def InsertImage(
        self,
        _p0: Any = ...,
        _p1: Any = ...,
        _p2: Any = ...,
        _p3: Any = ...,
        _p4: Any = ...,
        _p5: Any = ...,
    ) -> Any: ...
    def InStory(self, _p0: Any = ...) -> Any: ...
    def IsEqual(self, _p0: Any = ...) -> Any: ...
    def Move(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def MoveEnd(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def MoveStart(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def Paste(self, _p0: Any = ...) -> Any: ...
    def ScrollIntoView(self, _p0: Any = ...) -> Any: ...
    def MatchSelection(self) -> Any: ...
    def SetIndex(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def SetPoint(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def SetRange(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def SetText(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def SetTextViaStream(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def StartOf(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class ITextSelection:
    Options: Any
    Type: Any
    def EndKey(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def HomeKey(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def MoveDown(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def MoveLeft(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def MoveRight(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def MoveUp(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def TypeText(self, _p0: Any = ...) -> Any: ...

class LetterCase(int):
    Lower: int
    Upper: int

class LineSpacingRule(int):
    Undefined: int
    Single: int
    OneAndHalf: int
    Double: int
    AtLeast: int
    Exactly: int
    Multiple: int
    Percent: int

class LinkType(int):
    Undefined: int
    NotALink: int
    ClientLink: int
    FriendlyLinkName: int
    FriendlyLinkAddress: int
    AutoLink: int
    AutoLinkEmail: int
    AutoLinkPhone: int
    AutoLinkPath: int

class MarkerAlignment(int):
    Undefined: int
    Left: int
    Center: int
    Right: int

class MarkerStyle(int):
    Undefined: int
    Parenthesis: int
    Parentheses: int
    Period: int
    Plain: int
    Minus: int
    NoNumber: int

class MarkerType(int):
    Undefined: int
    None_: int
    Bullet: int
    Arabic: int
    LowercaseEnglishLetter: int
    UppercaseEnglishLetter: int
    LowercaseRoman: int
    UppercaseRoman: int
    UnicodeSequence: int
    CircledNumber: int
    BlackCircleWingding: int
    WhiteCircleWingding: int
    ArabicWide: int
    SimplifiedChinese: int
    TraditionalChinese: int
    JapanSimplifiedChinese: int
    JapanKorea: int
    ArabicDictionary: int
    ArabicAbjad: int
    Hebrew: int
    ThaiAlphabetic: int
    ThaiNumeric: int
    DevanagariVowel: int
    DevanagariConsonant: int
    DevanagariNumeric: int

class ParagraphAlignment(int):
    Undefined: int
    Left: int
    Center: int
    Right: int
    Justify: int

class ParagraphStyle(int):
    Undefined: int
    None_: int
    Normal: int
    Heading1: int
    Heading2: int
    Heading3: int
    Heading4: int
    Heading5: int
    Heading6: int
    Heading7: int
    Heading8: int
    Heading9: int

class PointOptions(int):
    None_: int
    IncludeInset: int
    Start: int
    ClientCoordinates: int
    AllowOffClient: int
    Transform: int
    NoHorizontalScroll: int
    NoVerticalScroll: int

class RangeGravity(int):
    UIBehavior: int
    Backward: int
    Forward: int
    Inward: int
    Outward: int

class RichEditMathMode(int):
    NoMath: int
    MathOnly: int

class RichEditTextDocument:
    AlignmentIncludesTrailingWhitespace: Any
    CaretType: Any
    DefaultTabStop: Any
    IgnoreTrailingCharacterSpacing: Any
    Selection: Any
    UndoLimit: Any
    def ClearUndoRedoHistory(self) -> Any: ...
    def SetMath(self, _p0: Any = ...) -> Any: ...
    def GetMath(self, _p0: Any = ...) -> Any: ...
    def SetMathMode(self, _p0: Any = ...) -> Any: ...
    def CanCopy(self) -> Any: ...
    def CanPaste(self) -> Any: ...
    def CanRedo(self) -> Any: ...
    def CanUndo(self) -> Any: ...
    def ApplyDisplayUpdates(self) -> Any: ...
    def BatchDisplayUpdates(self) -> Any: ...
    def BeginUndoGroup(self) -> Any: ...
    def EndUndoGroup(self) -> Any: ...
    def GetDefaultCharacterFormat(self) -> Any: ...
    def GetDefaultParagraphFormat(self) -> Any: ...
    def GetRange(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetRangeFromPoint(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetText(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def LoadFromStream(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def Redo(self) -> Any: ...
    def SaveToStream(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def SetDefaultCharacterFormat(self, _p0: Any = ...) -> Any: ...
    def SetDefaultParagraphFormat(self, _p0: Any = ...) -> Any: ...
    def SetText(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def Undo(self) -> Any: ...

class RichEditTextRange:
    Character: Any
    CharacterFormat: Any
    ContentLinkInfo: Any
    EndPosition: Any
    FormattedText: Any
    Gravity: Any
    Length: Any
    Link: Any
    ParagraphFormat: Any
    StartPosition: Any
    StoryLength: Any
    Text: Any
    def CanPaste(self, _p0: Any = ...) -> Any: ...
    def ChangeCase(self, _p0: Any = ...) -> Any: ...
    def Collapse(self, _p0: Any = ...) -> Any: ...
    def Copy(self) -> Any: ...
    def Cut(self) -> Any: ...
    def Delete(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def EndOf(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def Expand(self, _p0: Any = ...) -> Any: ...
    def FindText(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def GetCharacterUtf32(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetClone(self) -> Any: ...
    def GetIndex(self, _p0: Any = ...) -> Any: ...
    def GetPoint(
        self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...
    ) -> Any: ...
    def GetRect(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def GetText(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetTextViaStream(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def InRange(self, _p0: Any = ...) -> Any: ...
    def InsertImage(
        self,
        _p0: Any = ...,
        _p1: Any = ...,
        _p2: Any = ...,
        _p3: Any = ...,
        _p4: Any = ...,
        _p5: Any = ...,
    ) -> Any: ...
    def InStory(self, _p0: Any = ...) -> Any: ...
    def IsEqual(self, _p0: Any = ...) -> Any: ...
    def Move(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def MoveEnd(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def MoveStart(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def Paste(self, _p0: Any = ...) -> Any: ...
    def ScrollIntoView(self, _p0: Any = ...) -> Any: ...
    def MatchSelection(self) -> Any: ...
    def SetIndex(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def SetPoint(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def SetRange(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def SetText(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def SetTextViaStream(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def StartOf(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class SelectionOptions(int):
    StartActive: int
    AtEndOfLine: int
    Overtype: int
    Active: int
    Replace: int

class SelectionType(int):
    None_: int
    InsertionPoint: int
    Normal: int
    InlineShape: int
    Shape: int

class TabAlignment(int):
    Left: int
    Center: int
    Right: int
    Decimal: int
    Bar: int

class TabLeader(int):
    Spaces: int
    Dots: int
    Dashes: int
    Lines: int
    ThickLines: int
    Equals: int

class TextConstants:
    AutoColor: Any
    MaxUnitCount: Any
    MinUnitCount: Any
    UndefinedColor: Any
    UndefinedFloatValue: Any
    UndefinedFontStretch: Any
    UndefinedFontStyle: Any
    UndefinedInt32Value: Any

class TextDecorations(int):
    None_: int
    Underline: int
    Strikethrough: int

class TextGetOptions(int):
    None_: int
    AdjustCrlf: int
    UseCrlf: int
    UseObjectText: int
    AllowFinalEop: int
    NoHidden: int
    IncludeNumbering: int
    FormatRtf: int
    UseLf: int

class TextRangeUnit(int):
    Character: int
    Word: int
    Sentence: int
    Paragraph: int
    Line: int
    Story: int
    Screen: int
    Section: int
    Window: int
    CharacterFormat: int
    ParagraphFormat: int
    Object: int
    HardParagraph: int
    Cluster: int
    Bold: int
    Italic: int
    Underline: int
    Strikethrough: int
    ProtectedText: int
    Link: int
    SmallCaps: int
    AllCaps: int
    Hidden: int
    Outline: int
    Shadow: int
    Imprint: int
    Disabled: int
    Revised: int
    Subscript: int
    Superscript: int
    FontBound: int
    LinkProtected: int
    ContentLink: int

class TextScript(int):
    Undefined: int
    Ansi: int
    EastEurope: int
    Cyrillic: int
    Greek: int
    Turkish: int
    Hebrew: int
    Arabic: int
    Baltic: int
    Vietnamese: int
    Default: int
    Symbol: int
    Thai: int
    ShiftJis: int
    GB2312: int
    Hangul: int
    Big5: int
    PC437: int
    Oem: int
    Mac: int
    Armenian: int
    Syriac: int
    Thaana: int
    Devanagari: int
    Bengali: int
    Gurmukhi: int
    Gujarati: int
    Oriya: int
    Tamil: int
    Telugu: int
    Kannada: int
    Malayalam: int
    Sinhala: int
    Lao: int
    Tibetan: int
    Myanmar: int
    Georgian: int
    Jamo: int
    Ethiopic: int
    Cherokee: int
    Aboriginal: int
    Ogham: int
    Runic: int
    Khmer: int
    Mongolian: int
    Braille: int
    Yi: int
    Limbu: int
    TaiLe: int
    NewTaiLue: int
    SylotiNagri: int
    Kharoshthi: int
    Kayahli: int
    UnicodeSymbol: int
    Emoji: int
    Glagolitic: int
    Lisu: int
    Vai: int
    NKo: int
    Osmanya: int
    PhagsPa: int
    Gothic: int
    Deseret: int
    Tifinagh: int

class TextSetOptions(int):
    None_: int
    UnicodeBidi: int
    Unlink: int
    Unhide: int
    CheckTextLimit: int
    FormatRtf: int
    ApplyRtfDocumentDefaults: int

class UnderlineType(int):
    Undefined: int
    None_: int
    Single: int
    Words: int
    Double: int
    Dotted: int
    Dash: int
    DashDot: int
    DashDotDot: int
    Wave: int
    Thick: int
    Thin: int
    DoubleWave: int
    HeavyWave: int
    LongDash: int
    ThickDash: int
    ThickDashDot: int
    ThickDashDotDot: int
    ThickDotted: int
    ThickLongDash: int

class VerticalCharacterAlignment(int):
    Top: int
    Baseline: int
    Bottom: int
