class Font:
    def __init__(*args, **kwargs): ...

    def load_predefined_system_font(self): ...

    def load_user_registered_font(self): ...

    def load_arbitrary_system_font(self): ...

    @staticmethod
    def installed_families():
        raise NotImplementedError("Font enumeration is not supported on textual")
