# Auto-generated type stubs for win32more
# Generated by winui3/tools/generate_win32more_stubs.py
# Property types are typed as Any; the goal is attribute existence,
# not full type safety for win32more internals.

from typing import Any

class CanvasAnalyzedBidi:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    ExplicitLevel: Any
    ResolvedLevel: Any

class CanvasAnalyzedBreakpoint:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    BreakBefore: Any
    BreakAfter: Any
    IsWhitespace: Any
    IsSoftHyphen: Any

class CanvasAnalyzedGlyphOrientation:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GlyphOrientation: Any
    AdjustedBidiLevel: Any
    IsSideways: Any
    IsRightToLeft: Any

class CanvasAnalyzedScript:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    ScriptIdentifier: Any
    Shape: Any

class CanvasCharacterRange:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    CharacterIndex: Any
    CharacterCount: Any

class CanvasClusterMetrics:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    CharacterCount: Any
    Width: Any
    Properties: Any

class CanvasClusterProperties(int):
    None_: int
    CanWrapLineAfter: int
    Whitespace: int
    Newline: int
    SoftHyphen: int
    RightToLeft: int

class CanvasDrawTextOptions(int):
    Default: int
    NoPixelSnap: int
    Clip: int
    EnableColorFont: int

class CanvasFontFace:
    Ascent: Any
    CapHeight: Any
    CaretOffset: Any
    CaretSlopeRise: Any
    CaretSlopeRun: Any
    Descent: Any
    FaceNames: Any
    FamilyNames: Any
    FileFormatType: Any
    GlyphBox: Any
    GlyphCount: Any
    HasTypographicMetrics: Any
    HasVerticalGlyphVariants: Any
    IsMonospaced: Any
    IsSymbolFont: Any
    LineGap: Any
    LowercaseLetterHeight: Any
    Panose: Any
    Simulations: Any
    Stretch: Any
    StrikethroughPosition: Any
    StrikethroughThickness: Any
    Style: Any
    SubscriptPosition: Any
    SubscriptSize: Any
    SuperscriptPosition: Any
    SuperscriptSize: Any
    UnderlinePosition: Any
    UnderlineThickness: Any
    UnicodeRanges: Any
    Weight: Any
    def GetRecommendedRenderingMode(
        self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...
    ) -> Any: ...
    def GetRecommendedRenderingModeWithAllOptions(
        self,
        _p0: Any = ...,
        _p1: Any = ...,
        _p2: Any = ...,
        _p3: Any = ...,
        _p4: Any = ...,
        _p5: Any = ...,
        _p6: Any = ...,
    ) -> Any: ...
    def GetRecommendedGridFit(
        self,
        _p0: Any = ...,
        _p1: Any = ...,
        _p2: Any = ...,
        _p3: Any = ...,
        _p4: Any = ...,
        _p5: Any = ...,
        _p6: Any = ...,
    ) -> Any: ...
    def GetVerticalGlyphVariants(self, _p0: Any = ...) -> Any: ...
    def GetGlyphIndices(self, _p0: Any = ...) -> Any: ...
    def GetGlyphMetrics(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetGdiCompatibleGlyphMetrics(
        self,
        _p0: Any = ...,
        _p1: Any = ...,
        _p2: Any = ...,
        _p3: Any = ...,
        _p4: Any = ...,
        _p5: Any = ...,
    ) -> Any: ...
    def GetInformationalStrings(self, _p0: Any = ...) -> Any: ...
    def HasCharacter(self, _p0: Any = ...) -> Any: ...
    def GetGlyphRunBounds(
        self,
        _p0: Any = ...,
        _p1: Any = ...,
        _p2: Any = ...,
        _p3: Any = ...,
        _p4: Any = ...,
        _p5: Any = ...,
    ) -> Any: ...
    def GetGlyphRunBoundsWithMeasuringMode(
        self,
        _p0: Any = ...,
        _p1: Any = ...,
        _p2: Any = ...,
        _p3: Any = ...,
        _p4: Any = ...,
        _p5: Any = ...,
        _p6: Any = ...,
    ) -> Any: ...
    def GetSupportedTypographicFeatureNames(self, _p0: Any = ...) -> Any: ...
    def GetSupportedTypographicFeatureNamesWithLocale(
        self, _p0: Any = ..., _p1: Any = ...
    ) -> Any: ...
    def GetTypographicFeatureGlyphSupport(
        self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...
    ) -> Any: ...
    def GetTypographicFeatureGlyphSupportWithLocale(
        self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...
    ) -> Any: ...
    def Close(self) -> Any: ...

class CanvasFontFileFormatType(int):
    Cff: int
    TrueType: int
    TrueTypeCollection: int
    Type1: int
    Vector: int
    Bitmap: int
    Unknown: int
    RawCff: int

class CanvasFontInformation(int):
    None_: int
    CopyrightNotice: int
    VersionStrings: int
    Trademark: int
    Manufacturer: int
    Designer: int
    DesignerUrl: int
    Description: int
    FontVendorUrl: int
    LicenseDescription: int
    LicenseInfoUrl: int
    Win32FamilyNames: int
    Win32SubfamilyNames: int
    PreferredFamilyNames: int
    PreferredSubfamilyNames: int
    SampleText: int
    FullName: int
    PostscriptName: int
    PostscriptCidName: int
    WwsFamilyName: int
    DesignScriptLanguageTag: int
    SupportedScriptLanguageTag: int

class CanvasFontProperty:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Identifier: Any
    Value: Any
    Locale: Any

class CanvasFontPropertyIdentifier(int):
    None_: int
    FamilyName: int
    PreferredFamilyName: int
    FaceName: int
    FullName: int
    Win32FamilyName: int
    PostscriptName: int
    DesignScriptLanguageTag: int
    SupportedScriptLanguageTag: int
    SemanticTag: int
    Weight: int
    Stretch: int
    Style: int
    Total: int

class CanvasFontSet:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Fonts: Any
    @classmethod
    def Create(cls, _p0: Any = ...) -> Any: ...
    def TryFindFontFace(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetMatchingFontsFromProperties(self, _p0: Any = ...) -> Any: ...
    def GetMatchingFontsFromWwsFamily(
        self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...
    ) -> Any: ...
    def CountFontsMatchingProperty(self, _p0: Any = ...) -> Any: ...
    def GetPropertyValuesFromIndex(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetPropertyValuesFromIdentifier(
        self, _p0: Any = ..., _p1: Any = ...
    ) -> Any: ...
    def GetPropertyValues(self, _p0: Any = ...) -> Any: ...
    def Close(self) -> Any: ...
    @classmethod
    def GetSystemFontSet(cls) -> Any: ...

class CanvasFontSimulations(int):
    None_: int
    Bold: int
    Oblique: int

class CanvasGlyph:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Index: Any
    Advance: Any
    AdvanceOffset: Any
    AscenderOffset: Any

class CanvasGlyphJustification(int):
    None_: int
    ArabicBlank: int
    Character: int
    Blank: int
    ArabicNormal: int
    ArabicKashida: int
    ArabicAlef: int
    ArabicHa: int
    ArabicRa: int
    ArabicBa: int
    ArabicBara: int
    ArabicSeen: int
    ArabicSeenM: int

class CanvasGlyphMetrics:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    LeftSideBearing: Any
    AdvanceWidth: Any
    RightSideBearing: Any
    TopSideBearing: Any
    AdvanceHeight: Any
    BottomSideBearing: Any
    VerticalOrigin: Any
    DrawBounds: Any

class CanvasGlyphOrientation(int):
    Upright: int
    Clockwise90Degrees: int
    Clockwise180Degrees: int
    Clockwise270Degrees: int

class CanvasGlyphShaping:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Justification: Any
    IsClusterStart: Any
    IsDiacritic: Any
    IsZeroWidthSpace: Any

class CanvasHorizontalAlignment(int):
    Left: int
    Right: int
    Center: int
    Justified: int

class CanvasJustificationOpportunity:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    ExpansionMinimum: Any
    ExpansionMaximum: Any
    CompressionMaximum: Any
    ExpansionPriority: Any
    CompressionPriority: Any
    AllowResidualExpansion: Any
    AllowResidualCompression: Any
    ApplyToLeadingEdge: Any
    ApplyToTrailingEdge: Any

class CanvasLineBreakCondition(int):
    Neutral: int
    CanBreak: int
    CannotBreak: int
    MustBreak: int

class CanvasLineMetrics:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    CharacterCount: Any
    TrailingWhitespaceCount: Any
    TerminalNewlineCount: Any
    Height: Any
    Baseline: Any
    IsTrimmed: Any
    LeadingWhitespaceBefore: Any
    LeadingWhitespaceAfter: Any

class CanvasLineSpacingMode(int):
    Default: int
    Uniform: int
    Proportional: int

class CanvasNumberSubstitution:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @classmethod
    def Create(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def CreateWithLocaleAndIgnoreOverrides(
        cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...
    ) -> Any: ...
    def Close(self) -> Any: ...

class CanvasNumberSubstitutionMethod(int):
    FromCulture: int
    Contextual: int
    Disabled: int
    National: int
    Traditional: int

class CanvasOpticalAlignment(int):
    Default: int
    NoSideBearings: int

class CanvasScaledFont:
    FontFace: Any
    ScaleFactor: Any

class CanvasScriptProperties:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    IsoScriptCode: Any
    IsoScriptNumber: Any
    ClusterLookahead: Any
    JustificationCharacter: Any
    RestrictCaretToClusters: Any
    UsesWordDividers: Any
    IsDiscreteWriting: Any
    IsBlockWriting: Any
    IsDistributedWithinCluster: Any
    IsConnectedWriting: Any
    IsCursiveWriting: Any

class CanvasScriptShape(int):
    Default: int
    NoVisual: int

class CanvasTextAnalyzer:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @classmethod
    def Create(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def CreateWithOptions(
        cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...
    ) -> Any: ...
    @classmethod
    def CreateWithNumberSubstitutionAndVerticalGlyphOrientationAndBidiLevel(
        cls,
        _p0: Any = ...,
        _p1: Any = ...,
        _p2: Any = ...,
        _p3: Any = ...,
        _p4: Any = ...,
    ) -> Any: ...
    def GetFontsUsingSystemFontSet(self, _p0: Any = ...) -> Any: ...
    def GetFonts(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetBidi(self) -> Any: ...
    def GetBidiWithLocale(self, _p0: Any = ...) -> Any: ...
    def GetBreakpoints(self) -> Any: ...
    def GetBreakpointsWithLocale(self, _p0: Any = ...) -> Any: ...
    def GetNumberSubstitutions(self) -> Any: ...
    def GetScript(self) -> Any: ...
    def GetScriptWithLocale(self, _p0: Any = ...) -> Any: ...
    def GetGlyphOrientations(self) -> Any: ...
    def GetGlyphOrientationsWithLocale(self, _p0: Any = ...) -> Any: ...
    def GetScriptProperties(self, _p0: Any = ...) -> Any: ...
    def GetGlyphs(
        self,
        _p0: Any = ...,
        _p1: Any = ...,
        _p2: Any = ...,
        _p3: Any = ...,
        _p4: Any = ...,
        _p5: Any = ...,
    ) -> Any: ...
    def GetGlyphsWithAllOptions(
        self,
        _p0: Any = ...,
        _p1: Any = ...,
        _p2: Any = ...,
        _p3: Any = ...,
        _p4: Any = ...,
        _p5: Any = ...,
        _p6: Any = ...,
        _p7: Any = ...,
        _p8: Any = ...,
        _p9: Any = ...,
        _p10: Any = ...,
        _p11: Any = ...,
    ) -> Any: ...
    def GetJustificationOpportunities(
        self,
        _p0: Any = ...,
        _p1: Any = ...,
        _p2: Any = ...,
        _p3: Any = ...,
        _p4: Any = ...,
        _p5: Any = ...,
    ) -> Any: ...
    def ApplyJustificationOpportunities(
        self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...
    ) -> Any: ...
    def AddGlyphsAfterJustification(
        self,
        _p0: Any = ...,
        _p1: Any = ...,
        _p2: Any = ...,
        _p3: Any = ...,
        _p4: Any = ...,
        _p5: Any = ...,
        _p6: Any = ...,
    ) -> Any: ...
    def AddGlyphsAfterJustificationWithClusterMap(
        self,
        _p0: Any = ...,
        _p1: Any = ...,
        _p2: Any = ...,
        _p3: Any = ...,
        _p4: Any = ...,
        _p5: Any = ...,
        _p6: Any = ...,
        _p7: Any = ...,
    ) -> Any: ...
    def Close(self) -> Any: ...

class CanvasTextAntialiasing(int):
    Auto: int
    ClearType: int
    Grayscale: int
    Aliased: int

class CanvasTextDirection(int):
    LeftToRightThenTopToBottom: int
    RightToLeftThenTopToBottom: int
    LeftToRightThenBottomToTop: int
    RightToLeftThenBottomToTop: int
    TopToBottomThenLeftToRight: int
    BottomToTopThenLeftToRight: int
    TopToBottomThenRightToLeft: int
    BottomToTopThenRightToLeft: int

class CanvasTextFormat:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    CustomTrimmingSign: Any
    Direction: Any
    FontFamily: Any
    FontSize: Any
    FontStretch: Any
    FontStyle: Any
    FontWeight: Any
    HorizontalAlignment: Any
    IncrementalTabStop: Any
    LastLineWrapping: Any
    LineSpacing: Any
    LineSpacingBaseline: Any
    LineSpacingMode: Any
    LocaleName: Any
    OpticalAlignment: Any
    Options: Any
    TrimmingDelimiter: Any
    TrimmingDelimiterCount: Any
    TrimmingGranularity: Any
    TrimmingSign: Any
    VerticalAlignment: Any
    VerticalGlyphOrientation: Any
    WordWrapping: Any
    def Close(self) -> Any: ...
    @classmethod
    def GetSystemFontFamilies(cls) -> Any: ...
    @classmethod
    def GetSystemFontFamiliesFromLocaleList(cls, _p0: Any = ...) -> Any: ...

class CanvasTextGridFit(int):
    Default: int
    Disable: int
    Enable: int

class CanvasTextLayout:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    ClusterMetrics: Any
    CustomTrimmingSign: Any
    DefaultFontFamily: Any
    DefaultFontSize: Any
    DefaultFontStretch: Any
    DefaultFontStyle: Any
    DefaultFontWeight: Any
    DefaultLocaleName: Any
    Device: Any
    Direction: Any
    DrawBounds: Any
    HorizontalAlignment: Any
    IncrementalTabStop: Any
    LastLineWrapping: Any
    LayoutBounds: Any
    LayoutBoundsIncludingTrailingWhitespace: Any
    LineCount: Any
    LineMetrics: Any
    LineSpacing: Any
    LineSpacingBaseline: Any
    LineSpacingMode: Any
    MaximumBidiReorderingDepth: Any
    OpticalAlignment: Any
    Options: Any
    RequestedSize: Any
    TrimmingDelimiter: Any
    TrimmingDelimiterCount: Any
    TrimmingGranularity: Any
    TrimmingSign: Any
    VerticalAlignment: Any
    VerticalGlyphOrientation: Any
    WordWrapping: Any
    @classmethod
    def Create(
        cls,
        _p0: Any = ...,
        _p1: Any = ...,
        _p2: Any = ...,
        _p3: Any = ...,
        _p4: Any = ...,
    ) -> Any: ...
    def GetFormatChangeIndices(self) -> Any: ...
    def GetMinimumLineLength(self) -> Any: ...
    def GetBrush(self, _p0: Any = ...) -> Any: ...
    def GetCustomBrush(self, _p0: Any = ...) -> Any: ...
    def GetFontFamily(self, _p0: Any = ...) -> Any: ...
    def GetFontSize(self, _p0: Any = ...) -> Any: ...
    def GetFontStretch(self, _p0: Any = ...) -> Any: ...
    def GetFontStyle(self, _p0: Any = ...) -> Any: ...
    def GetFontWeight(self, _p0: Any = ...) -> Any: ...
    def GetLocaleName(self, _p0: Any = ...) -> Any: ...
    def GetStrikethrough(self, _p0: Any = ...) -> Any: ...
    def GetUnderline(self, _p0: Any = ...) -> Any: ...
    def GetInlineObject(self, _p0: Any = ...) -> Any: ...
    def SetColor(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def SetBrush(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def SetCustomBrush(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def SetFontFamily(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def SetFontSize(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def SetFontStretch(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def SetFontStyle(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def SetFontWeight(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def SetLocaleName(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def SetStrikethrough(
        self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...
    ) -> Any: ...
    def SetUnderline(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def SetInlineObject(
        self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...
    ) -> Any: ...
    def DrawToTextRenderer(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def DrawToTextRendererWithCoords(
        self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...
    ) -> Any: ...
    def SetTypography(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def GetTypography(self, _p0: Any = ...) -> Any: ...
    def HitTest(self, _p0: Any = ...) -> Any: ...
    def HitTestWithCoords(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def HitTestWithDescription(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def HitTestWithDescriptionAndCoords(
        self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...
    ) -> Any: ...
    def HitTestWithDescriptionAndTrailingSide(
        self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...
    ) -> Any: ...
    def HitTestWithDescriptionAndCoordsAndTrailingSide(
        self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...
    ) -> Any: ...
    def GetCaretPosition(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetCaretPositionWithDescription(
        self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...
    ) -> Any: ...
    def GetCharacterRegions(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetPairKerning(self, _p0: Any = ...) -> Any: ...
    def SetPairKerning(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def GetLeadingCharacterSpacing(self, _p0: Any = ...) -> Any: ...
    def GetTrailingCharacterSpacing(self, _p0: Any = ...) -> Any: ...
    def GetMinimumCharacterAdvance(self, _p0: Any = ...) -> Any: ...
    def SetCharacterSpacing(
        self,
        _p0: Any = ...,
        _p1: Any = ...,
        _p2: Any = ...,
        _p3: Any = ...,
        _p4: Any = ...,
    ) -> Any: ...
    def Close(self) -> Any: ...
    @classmethod
    def GetGlyphOrientationTransform(
        cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...
    ) -> Any: ...

class CanvasTextLayoutRegion:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    CharacterIndex: Any
    CharacterCount: Any
    LayoutBounds: Any

class CanvasTextMeasuringMode(int):
    Natural: int
    GdiClassic: int
    GdiNatural: int

class CanvasTextRenderingMode(int):
    Default: int
    Aliased: int
    GdiClassic: int
    GdiNatural: int
    Natural: int
    NaturalSymmetric: int
    Outline: int
    NaturalSymmetricDownsampled: int

class CanvasTextRenderingParameters:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GridFit: Any
    RenderingMode: Any
    @classmethod
    def Create(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class CanvasTextTrimmingGranularity(int):
    None_: int
    Character: int
    Word: int

class CanvasTrimmingSign(int):
    None_: int
    Ellipsis: int

class CanvasTypography:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def AddFeature(self, _p0: Any = ...) -> Any: ...
    def AddFeatureWithNameAndParameter(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetFeatures(self) -> Any: ...
    def Close(self) -> Any: ...

class CanvasTypographyFeature:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Name: Any
    Parameter: Any

class CanvasTypographyFeatureName(int):
    None_: int
    Default: int
    VerticalWriting: int
    VerticalAlternatesAndRotation: int
    AlternativeFractions: int
    PetiteCapitalsFromCapitals: int
    SmallCapitalsFromCapitals: int
    ContextualAlternates: int
    CaseSensitiveForms: int
    GlyphCompositionDecomposition: int
    ContextualLigatures: int
    CapitalSpacing: int
    ContextualSwash: int
    CursivePositioning: int
    DiscretionaryLigatures: int
    ExpertForms: int
    Fractions: int
    FullWidth: int
    HalfForms: int
    HalantForms: int
    AlternateHalfWidth: int
    HistoricalForms: int
    HorizontalKanaAlternates: int
    HistoricalLigatures: int
    HalfWidth: int
    HojoKanjiForms: int
    Jis04Forms: int
    Jis78Forms: int
    Jis83Forms: int
    Jis90Forms: int
    Kerning: int
    StandardLigatures: int
    LiningFigures: int
    LocalizedForms: int
    MarkPositioning: int
    MathematicalGreek: int
    MarkToMarkPositioning: int
    AlternateAnnotationForms: int
    NlcKanjiForms: int
    OldStyleFigures: int
    Ordinals: int
    ProportionalAlternateWidth: int
    PetiteCapitals: int
    ProportionalFigures: int
    ProportionalWidths: int
    QuarterWidths: int
    RequiredLigatures: int
    RubyNotationForms: int
    StylisticAlternates: int
    ScientificInferiors: int
    SmallCapitals: int
    SimplifiedForms: int
    StylisticSet1: int
    StylisticSet2: int
    StylisticSet3: int
    StylisticSet4: int
    StylisticSet5: int
    StylisticSet6: int
    StylisticSet7: int
    StylisticSet8: int
    StylisticSet9: int
    StylisticSet10: int
    StylisticSet11: int
    StylisticSet12: int
    StylisticSet13: int
    StylisticSet14: int
    StylisticSet15: int
    StylisticSet16: int
    StylisticSet17: int
    StylisticSet18: int
    StylisticSet19: int
    StylisticSet20: int
    Subscript: int
    Superscript: int
    Swash: int
    Titling: int
    TraditionalNameForms: int
    TabularFigures: int
    TraditionalForms: int
    ThirdWidths: int
    Unicase: int
    SlashedZero: int

class CanvasUnicodeRange:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    First: Any
    Last: Any

class CanvasVerticalAlignment(int):
    Top: int
    Bottom: int
    Center: int

class CanvasVerticalGlyphOrientation(int):
    Default: int
    Stacked: int

class CanvasWordWrapping(int):
    Wrap: int
    NoWrap: int
    EmergencyBreak: int
    WholeWord: int
    Character: int

class ICanvasFontFace:
    Ascent: Any
    CapHeight: Any
    CaretOffset: Any
    CaretSlopeRise: Any
    CaretSlopeRun: Any
    Descent: Any
    FaceNames: Any
    FamilyNames: Any
    FileFormatType: Any
    GlyphBox: Any
    GlyphCount: Any
    HasTypographicMetrics: Any
    HasVerticalGlyphVariants: Any
    IsMonospaced: Any
    IsSymbolFont: Any
    LineGap: Any
    LowercaseLetterHeight: Any
    Panose: Any
    Simulations: Any
    Stretch: Any
    StrikethroughPosition: Any
    StrikethroughThickness: Any
    Style: Any
    SubscriptPosition: Any
    SubscriptSize: Any
    SuperscriptPosition: Any
    SuperscriptSize: Any
    UnderlinePosition: Any
    UnderlineThickness: Any
    UnicodeRanges: Any
    Weight: Any
    def GetRecommendedRenderingMode(
        self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...
    ) -> Any: ...
    def GetRecommendedRenderingModeWithAllOptions(
        self,
        _p0: Any = ...,
        _p1: Any = ...,
        _p2: Any = ...,
        _p3: Any = ...,
        _p4: Any = ...,
        _p5: Any = ...,
        _p6: Any = ...,
    ) -> Any: ...
    def GetRecommendedGridFit(
        self,
        _p0: Any = ...,
        _p1: Any = ...,
        _p2: Any = ...,
        _p3: Any = ...,
        _p4: Any = ...,
        _p5: Any = ...,
        _p6: Any = ...,
    ) -> Any: ...
    def GetVerticalGlyphVariants(self, _p0: Any = ...) -> Any: ...
    def GetGlyphIndices(self, _p0: Any = ...) -> Any: ...
    def GetGlyphMetrics(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetGdiCompatibleGlyphMetrics(
        self,
        _p0: Any = ...,
        _p1: Any = ...,
        _p2: Any = ...,
        _p3: Any = ...,
        _p4: Any = ...,
        _p5: Any = ...,
    ) -> Any: ...
    def GetInformationalStrings(self, _p0: Any = ...) -> Any: ...
    def HasCharacter(self, _p0: Any = ...) -> Any: ...
    def GetGlyphRunBounds(
        self,
        _p0: Any = ...,
        _p1: Any = ...,
        _p2: Any = ...,
        _p3: Any = ...,
        _p4: Any = ...,
        _p5: Any = ...,
    ) -> Any: ...
    def GetGlyphRunBoundsWithMeasuringMode(
        self,
        _p0: Any = ...,
        _p1: Any = ...,
        _p2: Any = ...,
        _p3: Any = ...,
        _p4: Any = ...,
        _p5: Any = ...,
        _p6: Any = ...,
    ) -> Any: ...
    def GetSupportedTypographicFeatureNames(self, _p0: Any = ...) -> Any: ...
    def GetSupportedTypographicFeatureNamesWithLocale(
        self, _p0: Any = ..., _p1: Any = ...
    ) -> Any: ...
    def GetTypographicFeatureGlyphSupport(
        self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...
    ) -> Any: ...
    def GetTypographicFeatureGlyphSupportWithLocale(
        self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...
    ) -> Any: ...

class ICanvasFontSet:
    Fonts: Any
    def TryFindFontFace(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetMatchingFontsFromProperties(self, _p0: Any = ...) -> Any: ...
    def GetMatchingFontsFromWwsFamily(
        self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...
    ) -> Any: ...
    def CountFontsMatchingProperty(self, _p0: Any = ...) -> Any: ...
    def GetPropertyValuesFromIndex(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetPropertyValuesFromIdentifier(
        self, _p0: Any = ..., _p1: Any = ...
    ) -> Any: ...
    def GetPropertyValues(self, _p0: Any = ...) -> Any: ...

class ICanvasScaledFont:
    FontFace: Any
    ScaleFactor: Any

class ICanvasTextFormat:
    CustomTrimmingSign: Any
    Direction: Any
    FontFamily: Any
    FontSize: Any
    FontStretch: Any
    FontStyle: Any
    FontWeight: Any
    HorizontalAlignment: Any
    IncrementalTabStop: Any
    LastLineWrapping: Any
    LineSpacing: Any
    LineSpacingBaseline: Any
    LineSpacingMode: Any
    LocaleName: Any
    OpticalAlignment: Any
    Options: Any
    TrimmingDelimiter: Any
    TrimmingDelimiterCount: Any
    TrimmingGranularity: Any
    TrimmingSign: Any
    VerticalAlignment: Any
    VerticalGlyphOrientation: Any
    WordWrapping: Any

class ICanvasTextInlineObject:
    Baseline: Any
    BreakAfter: Any
    BreakBefore: Any
    DrawBounds: Any
    Size: Any
    SupportsSideways: Any
    def Draw(
        self,
        _p0: Any = ...,
        _p1: Any = ...,
        _p2: Any = ...,
        _p3: Any = ...,
        _p4: Any = ...,
    ) -> Any: ...

class ICanvasTextLayout:
    ClusterMetrics: Any
    CustomTrimmingSign: Any
    DefaultFontFamily: Any
    DefaultFontSize: Any
    DefaultFontStretch: Any
    DefaultFontStyle: Any
    DefaultFontWeight: Any
    DefaultLocaleName: Any
    Device: Any
    Direction: Any
    DrawBounds: Any
    HorizontalAlignment: Any
    IncrementalTabStop: Any
    LastLineWrapping: Any
    LayoutBounds: Any
    LayoutBoundsIncludingTrailingWhitespace: Any
    LineCount: Any
    LineMetrics: Any
    LineSpacing: Any
    LineSpacingBaseline: Any
    LineSpacingMode: Any
    MaximumBidiReorderingDepth: Any
    OpticalAlignment: Any
    Options: Any
    RequestedSize: Any
    TrimmingDelimiter: Any
    TrimmingDelimiterCount: Any
    TrimmingGranularity: Any
    TrimmingSign: Any
    VerticalAlignment: Any
    VerticalGlyphOrientation: Any
    WordWrapping: Any
    def GetFormatChangeIndices(self) -> Any: ...
    def GetMinimumLineLength(self) -> Any: ...
    def GetBrush(self, _p0: Any = ...) -> Any: ...
    def GetCustomBrush(self, _p0: Any = ...) -> Any: ...
    def GetFontFamily(self, _p0: Any = ...) -> Any: ...
    def GetFontSize(self, _p0: Any = ...) -> Any: ...
    def GetFontStretch(self, _p0: Any = ...) -> Any: ...
    def GetFontStyle(self, _p0: Any = ...) -> Any: ...
    def GetFontWeight(self, _p0: Any = ...) -> Any: ...
    def GetLocaleName(self, _p0: Any = ...) -> Any: ...
    def GetStrikethrough(self, _p0: Any = ...) -> Any: ...
    def GetUnderline(self, _p0: Any = ...) -> Any: ...
    def GetInlineObject(self, _p0: Any = ...) -> Any: ...
    def SetColor(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def SetBrush(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def SetCustomBrush(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def SetFontFamily(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def SetFontSize(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def SetFontStretch(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def SetFontStyle(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def SetFontWeight(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def SetLocaleName(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def SetStrikethrough(
        self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...
    ) -> Any: ...
    def SetUnderline(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def SetInlineObject(
        self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...
    ) -> Any: ...
    def DrawToTextRenderer(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def DrawToTextRendererWithCoords(
        self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...
    ) -> Any: ...
    def SetTypography(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def GetTypography(self, _p0: Any = ...) -> Any: ...
    def HitTest(self, _p0: Any = ...) -> Any: ...
    def HitTestWithCoords(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def HitTestWithDescription(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def HitTestWithDescriptionAndCoords(
        self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...
    ) -> Any: ...
    def HitTestWithDescriptionAndTrailingSide(
        self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...
    ) -> Any: ...
    def HitTestWithDescriptionAndCoordsAndTrailingSide(
        self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...
    ) -> Any: ...
    def GetCaretPosition(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetCaretPositionWithDescription(
        self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...
    ) -> Any: ...
    def GetCharacterRegions(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetPairKerning(self, _p0: Any = ...) -> Any: ...
    def SetPairKerning(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def GetLeadingCharacterSpacing(self, _p0: Any = ...) -> Any: ...
    def GetTrailingCharacterSpacing(self, _p0: Any = ...) -> Any: ...
    def GetMinimumCharacterAdvance(self, _p0: Any = ...) -> Any: ...
    def SetCharacterSpacing(
        self,
        _p0: Any = ...,
        _p1: Any = ...,
        _p2: Any = ...,
        _p3: Any = ...,
        _p4: Any = ...,
    ) -> Any: ...

class ICanvasTextRenderer:
    Dpi: Any
    PixelSnappingDisabled: Any
    Transform: Any
    def DrawGlyphRun(
        self,
        _p0: Any = ...,
        _p1: Any = ...,
        _p2: Any = ...,
        _p3: Any = ...,
        _p4: Any = ...,
        _p5: Any = ...,
        _p6: Any = ...,
        _p7: Any = ...,
        _p8: Any = ...,
        _p9: Any = ...,
        _p10: Any = ...,
        _p11: Any = ...,
        _p12: Any = ...,
    ) -> Any: ...
    def DrawStrikethrough(
        self,
        _p0: Any = ...,
        _p1: Any = ...,
        _p2: Any = ...,
        _p3: Any = ...,
        _p4: Any = ...,
        _p5: Any = ...,
        _p6: Any = ...,
        _p7: Any = ...,
        _p8: Any = ...,
    ) -> Any: ...
    def DrawUnderline(
        self,
        _p0: Any = ...,
        _p1: Any = ...,
        _p2: Any = ...,
        _p3: Any = ...,
        _p4: Any = ...,
        _p5: Any = ...,
        _p6: Any = ...,
        _p7: Any = ...,
        _p8: Any = ...,
        _p9: Any = ...,
    ) -> Any: ...
    def DrawInlineObject(
        self,
        _p0: Any = ...,
        _p1: Any = ...,
        _p2: Any = ...,
        _p3: Any = ...,
        _p4: Any = ...,
        _p5: Any = ...,
    ) -> Any: ...

class ICanvasTextRenderingParameters:
    GridFit: Any
    RenderingMode: Any
