# Auto-generated type stubs for win32more
# Generated by winui3/tools/generate_win32more_stubs.py
# Property types are typed as Any; the goal is attribute existence,
# not full type safety for win32more internals.

from typing import Any

class AdaptiveTrigger(StateTriggerBase):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    MinWindowHeight: Any
    MinWindowWidth: Any
    MinWindowHeightProperty: Any
    MinWindowWidthProperty: Any

class Application:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    DebugSettings: Any
    DispatcherShutdownMode: Any
    FocusVisualKind: Any
    HighContrastAdjustment: Any
    RequestedTheme: Any
    Resources: Any
    ResourceManagerRequested: Any
    UnhandledException: Any
    Current: Any
    def add_UnhandledException(self, _p0: Any = ...) -> Any: ...
    def remove_UnhandledException(self, _p0: Any = ...) -> Any: ...
    def Exit(self) -> Any: ...
    def add_ResourceManagerRequested(self, _p0: Any = ...) -> Any: ...
    def remove_ResourceManagerRequested(self, _p0: Any = ...) -> Any: ...
    def OnLaunched(self, _p0: Any = ...) -> Any: ...
    @classmethod
    def Start(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def LoadComponent(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def LoadComponentWithResourceLocation(
        cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...
    ) -> Any: ...

class ApplicationHighContrastAdjustment(int):
    None_: int
    Auto: int

class ApplicationInitializationCallback:
    def Invoke(self, _p0: Any = ...) -> Any: ...

class ApplicationInitializationCallbackParams: ...

class ApplicationRequiresPointerMode(int):
    Auto: int
    WhenRequested: int

class ApplicationTheme(int):
    Light: int
    Dark: int

class AutomationTextAttributesEnum(int):
    AnimationStyleAttribute: int
    BackgroundColorAttribute: int
    BulletStyleAttribute: int
    CapStyleAttribute: int
    CultureAttribute: int
    FontNameAttribute: int
    FontSizeAttribute: int
    FontWeightAttribute: int
    ForegroundColorAttribute: int
    HorizontalTextAlignmentAttribute: int
    IndentationFirstLineAttribute: int
    IndentationLeadingAttribute: int
    IndentationTrailingAttribute: int
    IsHiddenAttribute: int
    IsItalicAttribute: int
    IsReadOnlyAttribute: int
    IsSubscriptAttribute: int
    IsSuperscriptAttribute: int
    MarginBottomAttribute: int
    MarginLeadingAttribute: int
    MarginTopAttribute: int
    MarginTrailingAttribute: int
    OutlineStylesAttribute: int
    OverlineColorAttribute: int
    OverlineStyleAttribute: int
    StrikethroughColorAttribute: int
    StrikethroughStyleAttribute: int
    TabsAttribute: int
    TextFlowDirectionsAttribute: int
    UnderlineColorAttribute: int
    UnderlineStyleAttribute: int
    AnnotationTypesAttribute: int
    AnnotationObjectsAttribute: int
    StyleNameAttribute: int
    StyleIdAttribute: int
    LinkAttribute: int
    IsActiveAttribute: int
    SelectionActiveEndAttribute: int
    CaretPositionAttribute: int
    CaretBidiModeAttribute: int

class BindingFailedEventArgs:
    Message: Any

class BindingFailedEventHandler:
    def Invoke(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class BringIntoViewOptions:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    AnimationDesired: Any
    HorizontalAlignmentRatio: Any
    HorizontalOffset: Any
    TargetRect: Any
    VerticalAlignmentRatio: Any
    VerticalOffset: Any

class BringIntoViewRequestedEventArgs(RoutedEventArgs):
    AnimationDesired: Any
    Handled: Any
    HorizontalAlignmentRatio: Any
    HorizontalOffset: Any
    TargetElement: Any
    TargetRect: Any
    VerticalAlignmentRatio: Any
    VerticalOffset: Any

class BrushTransition:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Duration: Any

class ColorPaletteResources(ResourceDictionary):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Accent: Any
    AltHigh: Any
    AltLow: Any
    AltMedium: Any
    AltMediumHigh: Any
    AltMediumLow: Any
    BaseHigh: Any
    BaseLow: Any
    BaseMedium: Any
    BaseMediumHigh: Any
    BaseMediumLow: Any
    ChromeAltLow: Any
    ChromeBlackHigh: Any
    ChromeBlackLow: Any
    ChromeBlackMedium: Any
    ChromeBlackMediumLow: Any
    ChromeDisabledHigh: Any
    ChromeDisabledLow: Any
    ChromeGray: Any
    ChromeHigh: Any
    ChromeLow: Any
    ChromeMedium: Any
    ChromeMediumLow: Any
    ChromeWhite: Any
    ErrorText: Any
    ListLow: Any
    ListMedium: Any

class CornerRadius:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    TopLeft: Any
    TopRight: Any
    BottomRight: Any
    BottomLeft: Any

class CornerRadiusHelper:
    @classmethod
    def FromRadii(
        cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...
    ) -> Any: ...
    @classmethod
    def FromUniformRadius(cls, _p0: Any = ...) -> Any: ...

class CreateDefaultValueCallback:
    def Invoke(self) -> Any: ...

class DataContextChangedEventArgs:
    Handled: Any
    NewValue: Any

class DataTemplate(FrameworkTemplate):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    ExtensionInstanceProperty: Any
    def LoadContent(self) -> Any: ...
    def GetElement(self, _p0: Any = ...) -> Any: ...
    def RecycleElement(self, _p0: Any = ...) -> Any: ...
    @classmethod
    def GetExtensionInstance(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def SetExtensionInstance(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class DataTemplateKey:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    DataType: Any
    @classmethod
    def CreateInstanceWithType(
        cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...
    ) -> Any: ...

class DebugSettings:
    EnableFrameRateCounter: Any
    FailFastOnErrors: Any
    IsBindingTracingEnabled: Any
    IsTextPerformanceVisualizationEnabled: Any
    IsXamlResourceReferenceTracingEnabled: Any
    LayoutCycleDebugBreakLevel: Any
    LayoutCycleTracingLevel: Any
    BindingFailed: Any
    XamlResourceReferenceFailed: Any
    def add_BindingFailed(self, _p0: Any = ...) -> Any: ...
    def remove_BindingFailed(self, _p0: Any = ...) -> Any: ...
    def add_XamlResourceReferenceFailed(self, _p0: Any = ...) -> Any: ...
    def remove_XamlResourceReferenceFailed(self, _p0: Any = ...) -> Any: ...

class DependencyObject:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Dispatcher: Any
    DispatcherQueue: Any
    def GetValue(self, _p0: Any = ...) -> Any: ...
    def SetValue(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def ClearValue(self, _p0: Any = ...) -> Any: ...
    def ReadLocalValue(self, _p0: Any = ...) -> Any: ...
    def GetAnimationBaseValue(self, _p0: Any = ...) -> Any: ...
    def RegisterPropertyChangedCallback(
        self, _p0: Any = ..., _p1: Any = ...
    ) -> Any: ...
    def UnregisterPropertyChangedCallback(
        self, _p0: Any = ..., _p1: Any = ...
    ) -> Any: ...

class DependencyObjectCollection(DependencyObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any
    VectorChanged: Any
    def add_VectorChanged(self, _p0: Any = ...) -> Any: ...
    def remove_VectorChanged(self, _p0: Any = ...) -> Any: ...
    def GetAt(self, _p0: Any = ...) -> Any: ...
    def GetView(self) -> Any: ...
    def IndexOf(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def SetAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def InsertAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def RemoveAt(self, _p0: Any = ...) -> Any: ...
    def Append(self, _p0: Any = ...) -> Any: ...
    def RemoveAtEnd(self) -> Any: ...
    def Clear(self) -> Any: ...
    def GetMany(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def ReplaceAll(self, _p0: Any = ...) -> Any: ...
    def First(self) -> Any: ...

class DependencyProperty:
    UnsetValue: Any
    def GetMetadata(self, _p0: Any = ...) -> Any: ...
    @classmethod
    def Register(
        cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...
    ) -> Any: ...
    @classmethod
    def RegisterAttached(
        cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...
    ) -> Any: ...

class DependencyPropertyChangedCallback:
    def Invoke(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class DependencyPropertyChangedEventArgs:
    NewValue: Any
    OldValue: Any
    Property: Any

class DependencyPropertyChangedEventHandler:
    def Invoke(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class DispatcherShutdownMode(int):
    OnLastWindowClose: int
    OnExplicitShutdown: int

class DispatcherTimer:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Interval: Any
    IsEnabled: Any
    Tick: Any
    def add_Tick(self, _p0: Any = ...) -> Any: ...
    def remove_Tick(self, _p0: Any = ...) -> Any: ...
    def Start(self) -> Any: ...
    def Stop(self) -> Any: ...

class DragEventArgs(RoutedEventArgs):
    AcceptedOperation: Any
    AllowedOperations: Any
    Data: Any
    DataView: Any
    DragUIOverride: Any
    Handled: Any
    Modifiers: Any
    def GetDeferral(self) -> Any: ...
    def GetPosition(self, _p0: Any = ...) -> Any: ...

class DragEventHandler:
    def Invoke(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class DragOperationDeferral:
    def Complete(self) -> Any: ...

class DragStartingEventArgs(RoutedEventArgs):
    AllowedOperations: Any
    Cancel: Any
    Data: Any
    DragUI: Any
    def GetDeferral(self) -> Any: ...
    def GetPosition(self, _p0: Any = ...) -> Any: ...

class DragUI:
    def SetContentFromBitmapImage(self, _p0: Any = ...) -> Any: ...
    def SetContentFromBitmapImageWithAnchorPoint(
        self, _p0: Any = ..., _p1: Any = ...
    ) -> Any: ...
    def SetContentFromSoftwareBitmap(self, _p0: Any = ...) -> Any: ...
    def SetContentFromSoftwareBitmapWithAnchorPoint(
        self, _p0: Any = ..., _p1: Any = ...
    ) -> Any: ...
    def SetContentFromDataPackage(self) -> Any: ...

class DragUIOverride:
    Caption: Any
    IsCaptionVisible: Any
    IsContentVisible: Any
    IsGlyphVisible: Any
    def Clear(self) -> Any: ...
    def SetContentFromBitmapImage(self, _p0: Any = ...) -> Any: ...
    def SetContentFromBitmapImageWithAnchorPoint(
        self, _p0: Any = ..., _p1: Any = ...
    ) -> Any: ...
    def SetContentFromSoftwareBitmap(self, _p0: Any = ...) -> Any: ...
    def SetContentFromSoftwareBitmapWithAnchorPoint(
        self, _p0: Any = ..., _p1: Any = ...
    ) -> Any: ...

class DropCompletedEventArgs(RoutedEventArgs):
    DropResult: Any

class Duration:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    TimeSpan: Any
    Type: Any

class DurationHelper:
    Automatic: Any
    Forever: Any
    @classmethod
    def Compare(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def FromTimeSpan(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def GetHasTimeSpan(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def Add(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def Equals(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def Subtract(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class DurationType(int):
    Automatic: int
    TimeSpan: int
    Forever: int

class EffectiveViewportChangedEventArgs:
    BringIntoViewDistanceX: Any
    BringIntoViewDistanceY: Any
    EffectiveViewport: Any
    MaxViewport: Any

class ElementFactoryGetArgs:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Data: Any
    Parent: Any

class ElementFactoryRecycleArgs:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Element: Any
    Parent: Any

class ElementHighContrastAdjustment(int):
    None_: int
    Application: int
    Auto: int

class ElementSoundKind(int):
    Focus: int
    Invoke: int
    Show: int
    Hide: int
    MovePrevious: int
    MoveNext: int
    GoBack: int

class ElementSoundMode(int):
    Default: int
    FocusOnly: int
    Off: int

class ElementSoundPlayer:
    SpatialAudioMode: Any
    State: Any
    Volume: Any
    @classmethod
    def Play(cls, _p0: Any = ...) -> Any: ...

class ElementSoundPlayerState(int):
    Auto: int
    Off: int
    On: int

class ElementSpatialAudioMode(int):
    Auto: int
    Off: int
    On: int

class ElementTheme(int):
    Default: int
    Light: int
    Dark: int

class EnteredBackgroundEventHandler:
    def Invoke(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class EventTrigger(TriggerBase):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Actions: Any
    RoutedEvent: Any

class ExceptionRoutedEventArgs(RoutedEventArgs):
    ErrorMessage: Any

class ExceptionRoutedEventHandler:
    def Invoke(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class FlowDirection(int):
    LeftToRight: int
    RightToLeft: int

class FocusState(int):
    Unfocused: int
    Pointer: int
    Keyboard: int
    Programmatic: int

class FocusVisualKind(int):
    DottedLine: int
    HighVisibility: int
    Reveal: int

class FontCapitals(int):
    Normal: int
    AllSmallCaps: int
    SmallCaps: int
    AllPetiteCaps: int
    PetiteCaps: int
    Unicase: int
    Titling: int

class FontEastAsianLanguage(int):
    Normal: int
    HojoKanji: int
    Jis04: int
    Jis78: int
    Jis83: int
    Jis90: int
    NlcKanji: int
    Simplified: int
    Traditional: int
    TraditionalNames: int

class FontEastAsianWidths(int):
    Normal: int
    Full: int
    Half: int
    Proportional: int
    Quarter: int
    Third: int

class FontFraction(int):
    Normal: int
    Stacked: int
    Slashed: int

class FontNumeralAlignment(int):
    Normal: int
    Proportional: int
    Tabular: int

class FontNumeralStyle(int):
    Normal: int
    Lining: int
    OldStyle: int

class FontVariants(int):
    Normal: int
    Superscript: int
    Subscript: int
    Ordinal: int
    Inferior: int
    Ruby: int

class FrameworkElement(UIElement):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    ActualHeight: Any
    ActualTheme: Any
    ActualWidth: Any
    AllowFocusOnInteraction: Any
    AllowFocusWhenDisabled: Any
    BaseUri: Any
    DataContext: Any
    FlowDirection: Any
    FocusVisualMargin: Any
    FocusVisualPrimaryBrush: Any
    FocusVisualPrimaryThickness: Any
    FocusVisualSecondaryBrush: Any
    FocusVisualSecondaryThickness: Any
    Height: Any
    HorizontalAlignment: Any
    IsLoaded: Any
    Language: Any
    Margin: Any
    MaxHeight: Any
    MaxWidth: Any
    MinHeight: Any
    MinWidth: Any
    Name: Any
    Parent: Any
    RequestedTheme: Any
    Resources: Any
    Style: Any
    Tag: Any
    Triggers: Any
    VerticalAlignment: Any
    Width: Any
    ActualThemeChanged: Any
    DataContextChanged: Any
    EffectiveViewportChanged: Any
    LayoutUpdated: Any
    Loaded: Any
    Loading: Any
    SizeChanged: Any
    Unloaded: Any
    ActualHeightProperty: Any
    ActualThemeProperty: Any
    ActualWidthProperty: Any
    AllowFocusOnInteractionProperty: Any
    AllowFocusWhenDisabledProperty: Any
    DataContextProperty: Any
    FlowDirectionProperty: Any
    FocusVisualMarginProperty: Any
    FocusVisualPrimaryBrushProperty: Any
    FocusVisualPrimaryThicknessProperty: Any
    FocusVisualSecondaryBrushProperty: Any
    FocusVisualSecondaryThicknessProperty: Any
    HeightProperty: Any
    HorizontalAlignmentProperty: Any
    LanguageProperty: Any
    MarginProperty: Any
    MaxHeightProperty: Any
    MaxWidthProperty: Any
    MinHeightProperty: Any
    MinWidthProperty: Any
    NameProperty: Any
    RequestedThemeProperty: Any
    StyleProperty: Any
    TagProperty: Any
    VerticalAlignmentProperty: Any
    WidthProperty: Any
    def add_Loaded(self, _p0: Any = ...) -> Any: ...
    def remove_Loaded(self, _p0: Any = ...) -> Any: ...
    def add_Unloaded(self, _p0: Any = ...) -> Any: ...
    def remove_Unloaded(self, _p0: Any = ...) -> Any: ...
    def add_DataContextChanged(self, _p0: Any = ...) -> Any: ...
    def remove_DataContextChanged(self, _p0: Any = ...) -> Any: ...
    def add_SizeChanged(self, _p0: Any = ...) -> Any: ...
    def remove_SizeChanged(self, _p0: Any = ...) -> Any: ...
    def add_LayoutUpdated(self, _p0: Any = ...) -> Any: ...
    def remove_LayoutUpdated(self, _p0: Any = ...) -> Any: ...
    def add_Loading(self, _p0: Any = ...) -> Any: ...
    def remove_Loading(self, _p0: Any = ...) -> Any: ...
    def add_ActualThemeChanged(self, _p0: Any = ...) -> Any: ...
    def remove_ActualThemeChanged(self, _p0: Any = ...) -> Any: ...
    def add_EffectiveViewportChanged(self, _p0: Any = ...) -> Any: ...
    def remove_EffectiveViewportChanged(self, _p0: Any = ...) -> Any: ...
    def FindName(self, _p0: Any = ...) -> Any: ...
    def SetBinding(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetBindingExpression(self, _p0: Any = ...) -> Any: ...
    def InvalidateViewport(self) -> Any: ...
    def MeasureOverride(self, _p0: Any = ...) -> Any: ...
    def ArrangeOverride(self, _p0: Any = ...) -> Any: ...
    def OnApplyTemplate(self) -> Any: ...
    def GoToElementStateCore(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def DeferTree(cls, _p0: Any = ...) -> Any: ...

class FrameworkTemplate(DependencyObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class FrameworkView:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def Initialize(self, _p0: Any = ...) -> Any: ...
    def SetWindow(self, _p0: Any = ...) -> Any: ...
    def Load(self, _p0: Any = ...) -> Any: ...
    def Run(self) -> Any: ...
    def Uninitialize(self) -> Any: ...

class FrameworkViewSource:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def CreateView(self) -> Any: ...

class GridLength:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Value: Any
    GridUnitType: Any

class GridLengthHelper:
    Auto: Any
    @classmethod
    def FromPixels(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def FromValueAndType(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def GetIsAbsolute(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def GetIsAuto(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def GetIsStar(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def Equals(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class GridUnitType(int):
    Auto: int
    Pixel: int
    Star: int

class HorizontalAlignment(int):
    Left: int
    Center: int
    Right: int
    Stretch: int

class IAdaptiveTrigger:
    MinWindowHeight: Any
    MinWindowWidth: Any

class IAdaptiveTriggerStatics:
    MinWindowHeightProperty: Any
    MinWindowWidthProperty: Any

class IApplication:
    DebugSettings: Any
    FocusVisualKind: Any
    HighContrastAdjustment: Any
    RequestedTheme: Any
    Resources: Any
    UnhandledException: Any
    def add_UnhandledException(self, _p0: Any = ...) -> Any: ...
    def remove_UnhandledException(self, _p0: Any = ...) -> Any: ...
    def Exit(self) -> Any: ...

class IApplication3:
    DispatcherShutdownMode: Any

class IApplicationStatics:
    Current: Any
    def Start(self, _p0: Any = ...) -> Any: ...
    def LoadComponent(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def LoadComponentWithResourceLocation(
        self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...
    ) -> Any: ...

class IBindingFailedEventArgs:
    Message: Any

class IBringIntoViewOptions:
    AnimationDesired: Any
    HorizontalAlignmentRatio: Any
    HorizontalOffset: Any
    TargetRect: Any
    VerticalAlignmentRatio: Any
    VerticalOffset: Any

class IBringIntoViewRequestedEventArgs:
    AnimationDesired: Any
    Handled: Any
    HorizontalAlignmentRatio: Any
    HorizontalOffset: Any
    TargetElement: Any
    TargetRect: Any
    VerticalAlignmentRatio: Any
    VerticalOffset: Any

class IBrushTransition:
    Duration: Any

class IColorPaletteResources:
    Accent: Any
    AltHigh: Any
    AltLow: Any
    AltMedium: Any
    AltMediumHigh: Any
    AltMediumLow: Any
    BaseHigh: Any
    BaseLow: Any
    BaseMedium: Any
    BaseMediumHigh: Any
    BaseMediumLow: Any
    ChromeAltLow: Any
    ChromeBlackHigh: Any
    ChromeBlackLow: Any
    ChromeBlackMedium: Any
    ChromeBlackMediumLow: Any
    ChromeDisabledHigh: Any
    ChromeDisabledLow: Any
    ChromeGray: Any
    ChromeHigh: Any
    ChromeLow: Any
    ChromeMedium: Any
    ChromeMediumLow: Any
    ChromeWhite: Any
    ErrorText: Any
    ListLow: Any
    ListMedium: Any

class IDataContextChangedEventArgs:
    Handled: Any
    NewValue: Any

class IDataTemplateKey:
    DataType: Any

class IDataTemplateStatics:
    ExtensionInstanceProperty: Any
    def GetExtensionInstance(self, _p0: Any = ...) -> Any: ...
    def SetExtensionInstance(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class IDebugSettings:
    EnableFrameRateCounter: Any
    FailFastOnErrors: Any
    IsBindingTracingEnabled: Any
    IsTextPerformanceVisualizationEnabled: Any
    BindingFailed: Any
    def add_BindingFailed(self, _p0: Any = ...) -> Any: ...
    def remove_BindingFailed(self, _p0: Any = ...) -> Any: ...

class IDebugSettings2:
    IsXamlResourceReferenceTracingEnabled: Any
    XamlResourceReferenceFailed: Any
    def add_XamlResourceReferenceFailed(self, _p0: Any = ...) -> Any: ...
    def remove_XamlResourceReferenceFailed(self, _p0: Any = ...) -> Any: ...

class IDebugSettings3:
    LayoutCycleDebugBreakLevel: Any
    LayoutCycleTracingLevel: Any

class IDependencyObject:
    Dispatcher: Any
    DispatcherQueue: Any
    def GetValue(self, _p0: Any = ...) -> Any: ...
    def SetValue(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def ClearValue(self, _p0: Any = ...) -> Any: ...
    def ReadLocalValue(self, _p0: Any = ...) -> Any: ...
    def GetAnimationBaseValue(self, _p0: Any = ...) -> Any: ...
    def RegisterPropertyChangedCallback(
        self, _p0: Any = ..., _p1: Any = ...
    ) -> Any: ...
    def UnregisterPropertyChangedCallback(
        self, _p0: Any = ..., _p1: Any = ...
    ) -> Any: ...

class IDependencyPropertyChangedEventArgs:
    NewValue: Any
    OldValue: Any
    Property: Any

class IDependencyPropertyStatics:
    UnsetValue: Any
    def Register(
        self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...
    ) -> Any: ...
    def RegisterAttached(
        self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...
    ) -> Any: ...

class IDispatcherTimer:
    Interval: Any
    IsEnabled: Any
    Tick: Any
    def add_Tick(self, _p0: Any = ...) -> Any: ...
    def remove_Tick(self, _p0: Any = ...) -> Any: ...
    def Start(self) -> Any: ...
    def Stop(self) -> Any: ...

class IDragEventArgs:
    AcceptedOperation: Any
    AllowedOperations: Any
    Data: Any
    DataView: Any
    DragUIOverride: Any
    Handled: Any
    Modifiers: Any
    def GetDeferral(self) -> Any: ...
    def GetPosition(self, _p0: Any = ...) -> Any: ...

class IDragStartingEventArgs:
    AllowedOperations: Any
    Cancel: Any
    Data: Any
    DragUI: Any
    def GetDeferral(self) -> Any: ...
    def GetPosition(self, _p0: Any = ...) -> Any: ...

class IDragUIOverride:
    Caption: Any
    IsCaptionVisible: Any
    IsContentVisible: Any
    IsGlyphVisible: Any
    def Clear(self) -> Any: ...
    def SetContentFromBitmapImage(self, _p0: Any = ...) -> Any: ...
    def SetContentFromBitmapImageWithAnchorPoint(
        self, _p0: Any = ..., _p1: Any = ...
    ) -> Any: ...
    def SetContentFromSoftwareBitmap(self, _p0: Any = ...) -> Any: ...
    def SetContentFromSoftwareBitmapWithAnchorPoint(
        self, _p0: Any = ..., _p1: Any = ...
    ) -> Any: ...

class IDropCompletedEventArgs:
    DropResult: Any

class IDurationHelperStatics:
    Automatic: Any
    Forever: Any
    def Compare(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def FromTimeSpan(self, _p0: Any = ...) -> Any: ...
    def GetHasTimeSpan(self, _p0: Any = ...) -> Any: ...
    def Add(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def Equals(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def Subtract(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class IEffectiveViewportChangedEventArgs:
    BringIntoViewDistanceX: Any
    BringIntoViewDistanceY: Any
    EffectiveViewport: Any
    MaxViewport: Any

class IElementFactoryGetArgs:
    Data: Any
    Parent: Any

class IElementFactoryRecycleArgs:
    Element: Any
    Parent: Any

class IElementSoundPlayerStatics:
    SpatialAudioMode: Any
    State: Any
    Volume: Any
    def Play(self, _p0: Any = ...) -> Any: ...

class IEventTrigger:
    Actions: Any
    RoutedEvent: Any

class IExceptionRoutedEventArgs:
    ErrorMessage: Any

class IFrameworkElement:
    ActualHeight: Any
    ActualTheme: Any
    ActualWidth: Any
    AllowFocusOnInteraction: Any
    AllowFocusWhenDisabled: Any
    BaseUri: Any
    DataContext: Any
    FlowDirection: Any
    FocusVisualMargin: Any
    FocusVisualPrimaryBrush: Any
    FocusVisualPrimaryThickness: Any
    FocusVisualSecondaryBrush: Any
    FocusVisualSecondaryThickness: Any
    Height: Any
    HorizontalAlignment: Any
    IsLoaded: Any
    Language: Any
    Margin: Any
    MaxHeight: Any
    MaxWidth: Any
    MinHeight: Any
    MinWidth: Any
    Name: Any
    Parent: Any
    RequestedTheme: Any
    Resources: Any
    Style: Any
    Tag: Any
    Triggers: Any
    VerticalAlignment: Any
    Width: Any
    ActualThemeChanged: Any
    DataContextChanged: Any
    EffectiveViewportChanged: Any
    LayoutUpdated: Any
    Loaded: Any
    Loading: Any
    SizeChanged: Any
    Unloaded: Any
    def add_Loaded(self, _p0: Any = ...) -> Any: ...
    def remove_Loaded(self, _p0: Any = ...) -> Any: ...
    def add_Unloaded(self, _p0: Any = ...) -> Any: ...
    def remove_Unloaded(self, _p0: Any = ...) -> Any: ...
    def add_DataContextChanged(self, _p0: Any = ...) -> Any: ...
    def remove_DataContextChanged(self, _p0: Any = ...) -> Any: ...
    def add_SizeChanged(self, _p0: Any = ...) -> Any: ...
    def remove_SizeChanged(self, _p0: Any = ...) -> Any: ...
    def add_LayoutUpdated(self, _p0: Any = ...) -> Any: ...
    def remove_LayoutUpdated(self, _p0: Any = ...) -> Any: ...
    def add_Loading(self, _p0: Any = ...) -> Any: ...
    def remove_Loading(self, _p0: Any = ...) -> Any: ...
    def add_ActualThemeChanged(self, _p0: Any = ...) -> Any: ...
    def remove_ActualThemeChanged(self, _p0: Any = ...) -> Any: ...
    def add_EffectiveViewportChanged(self, _p0: Any = ...) -> Any: ...
    def remove_EffectiveViewportChanged(self, _p0: Any = ...) -> Any: ...
    def FindName(self, _p0: Any = ...) -> Any: ...
    def SetBinding(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetBindingExpression(self, _p0: Any = ...) -> Any: ...

class IFrameworkElementStatics:
    ActualHeightProperty: Any
    ActualThemeProperty: Any
    ActualWidthProperty: Any
    AllowFocusOnInteractionProperty: Any
    AllowFocusWhenDisabledProperty: Any
    DataContextProperty: Any
    FlowDirectionProperty: Any
    FocusVisualMarginProperty: Any
    FocusVisualPrimaryBrushProperty: Any
    FocusVisualPrimaryThicknessProperty: Any
    FocusVisualSecondaryBrushProperty: Any
    FocusVisualSecondaryThicknessProperty: Any
    HeightProperty: Any
    HorizontalAlignmentProperty: Any
    LanguageProperty: Any
    MarginProperty: Any
    MaxHeightProperty: Any
    MaxWidthProperty: Any
    MinHeightProperty: Any
    MinWidthProperty: Any
    NameProperty: Any
    RequestedThemeProperty: Any
    StyleProperty: Any
    TagProperty: Any
    VerticalAlignmentProperty: Any
    WidthProperty: Any
    def DeferTree(self, _p0: Any = ...) -> Any: ...

class IGridLengthHelperStatics:
    Auto: Any
    def FromPixels(self, _p0: Any = ...) -> Any: ...
    def FromValueAndType(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetIsAbsolute(self, _p0: Any = ...) -> Any: ...
    def GetIsAuto(self, _p0: Any = ...) -> Any: ...
    def GetIsStar(self, _p0: Any = ...) -> Any: ...
    def Equals(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class ILaunchActivatedEventArgs:
    Arguments: Any
    UWPLaunchActivatedEventArgs: Any

class IMediaFailedRoutedEventArgs:
    ErrorTrace: Any

class IPropertyMetadata:
    CreateDefaultValueCallback: Any
    DefaultValue: Any

class IPropertyPath:
    Path: Any

class IRectHelperStatics:
    Empty: Any
    def FromCoordinatesAndDimensions(
        self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...
    ) -> Any: ...
    def FromPoints(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def FromLocationAndSize(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetIsEmpty(self, _p0: Any = ...) -> Any: ...
    def GetBottom(self, _p0: Any = ...) -> Any: ...
    def GetLeft(self, _p0: Any = ...) -> Any: ...
    def GetRight(self, _p0: Any = ...) -> Any: ...
    def GetTop(self, _p0: Any = ...) -> Any: ...
    def Contains(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def Equals(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def Intersect(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def UnionWithPoint(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def UnionWithRect(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class IResourceDictionary:
    MergedDictionaries: Any
    Source: Any
    ThemeDictionaries: Any

class IResourceManagerRequestedEventArgs:
    CustomResourceManager: Any

class IRoutedEventArgs:
    OriginalSource: Any

class IScalarTransition:
    Duration: Any

class ISetter:
    Property: Any
    Target: Any
    Value: Any

class ISetterBase:
    IsSealed: Any

class ISetterBaseCollection:
    IsSealed: Any

class ISizeChangedEventArgs:
    NewSize: Any
    PreviousSize: Any

class ISizeHelperStatics:
    Empty: Any
    def FromDimensions(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetIsEmpty(self, _p0: Any = ...) -> Any: ...
    def Equals(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class IStateTrigger:
    IsActive: Any

class IStateTriggerStatics:
    IsActiveProperty: Any

class IStyle:
    BasedOn: Any
    IsSealed: Any
    Setters: Any
    TargetType: Any
    def Seal(self) -> Any: ...

class ITargetPropertyPath:
    Path: Any
    Target: Any

class IUIElement:
    AccessKey: Any
    AccessKeyScopeOwner: Any
    ActualOffset: Any
    ActualSize: Any
    AllowDrop: Any
    CacheMode: Any
    CanBeScrollAnchor: Any
    CanDrag: Any
    CenterPoint: Any
    Clip: Any
    CompositeMode: Any
    ContextFlyout: Any
    DesiredSize: Any
    ExitDisplayModeOnAccessKeyInvoked: Any
    FocusState: Any
    HighContrastAdjustment: Any
    IsAccessKeyScope: Any
    IsDoubleTapEnabled: Any
    IsHitTestVisible: Any
    IsHoldingEnabled: Any
    IsRightTapEnabled: Any
    IsTabStop: Any
    IsTapEnabled: Any
    KeyTipHorizontalOffset: Any
    KeyTipPlacementMode: Any
    KeyTipTarget: Any
    KeyTipVerticalOffset: Any
    KeyboardAcceleratorPlacementMode: Any
    KeyboardAcceleratorPlacementTarget: Any
    KeyboardAccelerators: Any
    Lights: Any
    ManipulationMode: Any
    Opacity: Any
    OpacityTransition: Any
    PointerCaptures: Any
    Projection: Any
    RasterizationScale: Any
    RenderSize: Any
    RenderTransform: Any
    RenderTransformOrigin: Any
    Rotation: Any
    RotationAxis: Any
    RotationTransition: Any
    Scale: Any
    ScaleTransition: Any
    Shadow: Any
    TabFocusNavigation: Any
    TabIndex: Any
    Transform3D: Any
    TransformMatrix: Any
    Transitions: Any
    Translation: Any
    TranslationTransition: Any
    UseLayoutRounding: Any
    UseSystemFocusVisuals: Any
    Visibility: Any
    XYFocusDown: Any
    XYFocusDownNavigationStrategy: Any
    XYFocusKeyboardNavigation: Any
    XYFocusLeft: Any
    XYFocusLeftNavigationStrategy: Any
    XYFocusRight: Any
    XYFocusRightNavigationStrategy: Any
    XYFocusUp: Any
    XYFocusUpNavigationStrategy: Any
    XamlRoot: Any
    AccessKeyDisplayDismissed: Any
    AccessKeyDisplayRequested: Any
    AccessKeyInvoked: Any
    BringIntoViewRequested: Any
    CharacterReceived: Any
    ContextCanceled: Any
    ContextRequested: Any
    DoubleTapped: Any
    DragEnter: Any
    DragLeave: Any
    DragOver: Any
    DragStarting: Any
    Drop: Any
    DropCompleted: Any
    GettingFocus: Any
    GotFocus: Any
    Holding: Any
    KeyDown: Any
    KeyUp: Any
    LosingFocus: Any
    LostFocus: Any
    ManipulationCompleted: Any
    ManipulationDelta: Any
    ManipulationInertiaStarting: Any
    ManipulationStarted: Any
    ManipulationStarting: Any
    NoFocusCandidateFound: Any
    PointerCanceled: Any
    PointerCaptureLost: Any
    PointerEntered: Any
    PointerExited: Any
    PointerMoved: Any
    PointerPressed: Any
    PointerReleased: Any
    PointerWheelChanged: Any
    PreviewKeyDown: Any
    PreviewKeyUp: Any
    ProcessKeyboardAccelerators: Any
    RightTapped: Any
    Tapped: Any
    def add_KeyUp(self, _p0: Any = ...) -> Any: ...
    def remove_KeyUp(self, _p0: Any = ...) -> Any: ...
    def add_KeyDown(self, _p0: Any = ...) -> Any: ...
    def remove_KeyDown(self, _p0: Any = ...) -> Any: ...
    def add_GotFocus(self, _p0: Any = ...) -> Any: ...
    def remove_GotFocus(self, _p0: Any = ...) -> Any: ...
    def add_LostFocus(self, _p0: Any = ...) -> Any: ...
    def remove_LostFocus(self, _p0: Any = ...) -> Any: ...
    def add_DragStarting(self, _p0: Any = ...) -> Any: ...
    def remove_DragStarting(self, _p0: Any = ...) -> Any: ...
    def add_DropCompleted(self, _p0: Any = ...) -> Any: ...
    def remove_DropCompleted(self, _p0: Any = ...) -> Any: ...
    def add_CharacterReceived(self, _p0: Any = ...) -> Any: ...
    def remove_CharacterReceived(self, _p0: Any = ...) -> Any: ...
    def add_DragEnter(self, _p0: Any = ...) -> Any: ...
    def remove_DragEnter(self, _p0: Any = ...) -> Any: ...
    def add_DragLeave(self, _p0: Any = ...) -> Any: ...
    def remove_DragLeave(self, _p0: Any = ...) -> Any: ...
    def add_DragOver(self, _p0: Any = ...) -> Any: ...
    def remove_DragOver(self, _p0: Any = ...) -> Any: ...
    def add_Drop(self, _p0: Any = ...) -> Any: ...
    def remove_Drop(self, _p0: Any = ...) -> Any: ...
    def add_PointerPressed(self, _p0: Any = ...) -> Any: ...
    def remove_PointerPressed(self, _p0: Any = ...) -> Any: ...
    def add_PointerMoved(self, _p0: Any = ...) -> Any: ...
    def remove_PointerMoved(self, _p0: Any = ...) -> Any: ...
    def add_PointerReleased(self, _p0: Any = ...) -> Any: ...
    def remove_PointerReleased(self, _p0: Any = ...) -> Any: ...
    def add_PointerEntered(self, _p0: Any = ...) -> Any: ...
    def remove_PointerEntered(self, _p0: Any = ...) -> Any: ...
    def add_PointerExited(self, _p0: Any = ...) -> Any: ...
    def remove_PointerExited(self, _p0: Any = ...) -> Any: ...
    def add_PointerCaptureLost(self, _p0: Any = ...) -> Any: ...
    def remove_PointerCaptureLost(self, _p0: Any = ...) -> Any: ...
    def add_PointerCanceled(self, _p0: Any = ...) -> Any: ...
    def remove_PointerCanceled(self, _p0: Any = ...) -> Any: ...
    def add_PointerWheelChanged(self, _p0: Any = ...) -> Any: ...
    def remove_PointerWheelChanged(self, _p0: Any = ...) -> Any: ...
    def add_Tapped(self, _p0: Any = ...) -> Any: ...
    def remove_Tapped(self, _p0: Any = ...) -> Any: ...
    def add_DoubleTapped(self, _p0: Any = ...) -> Any: ...
    def remove_DoubleTapped(self, _p0: Any = ...) -> Any: ...
    def add_Holding(self, _p0: Any = ...) -> Any: ...
    def remove_Holding(self, _p0: Any = ...) -> Any: ...
    def add_ContextRequested(self, _p0: Any = ...) -> Any: ...
    def remove_ContextRequested(self, _p0: Any = ...) -> Any: ...
    def add_ContextCanceled(self, _p0: Any = ...) -> Any: ...
    def remove_ContextCanceled(self, _p0: Any = ...) -> Any: ...
    def add_RightTapped(self, _p0: Any = ...) -> Any: ...
    def remove_RightTapped(self, _p0: Any = ...) -> Any: ...
    def add_ManipulationStarting(self, _p0: Any = ...) -> Any: ...
    def remove_ManipulationStarting(self, _p0: Any = ...) -> Any: ...
    def add_ManipulationInertiaStarting(self, _p0: Any = ...) -> Any: ...
    def remove_ManipulationInertiaStarting(self, _p0: Any = ...) -> Any: ...
    def add_ManipulationStarted(self, _p0: Any = ...) -> Any: ...
    def remove_ManipulationStarted(self, _p0: Any = ...) -> Any: ...
    def add_ManipulationDelta(self, _p0: Any = ...) -> Any: ...
    def remove_ManipulationDelta(self, _p0: Any = ...) -> Any: ...
    def add_ManipulationCompleted(self, _p0: Any = ...) -> Any: ...
    def remove_ManipulationCompleted(self, _p0: Any = ...) -> Any: ...
    def add_AccessKeyDisplayRequested(self, _p0: Any = ...) -> Any: ...
    def remove_AccessKeyDisplayRequested(self, _p0: Any = ...) -> Any: ...
    def add_AccessKeyDisplayDismissed(self, _p0: Any = ...) -> Any: ...
    def remove_AccessKeyDisplayDismissed(self, _p0: Any = ...) -> Any: ...
    def add_AccessKeyInvoked(self, _p0: Any = ...) -> Any: ...
    def remove_AccessKeyInvoked(self, _p0: Any = ...) -> Any: ...
    def add_ProcessKeyboardAccelerators(self, _p0: Any = ...) -> Any: ...
    def remove_ProcessKeyboardAccelerators(self, _p0: Any = ...) -> Any: ...
    def add_GettingFocus(self, _p0: Any = ...) -> Any: ...
    def remove_GettingFocus(self, _p0: Any = ...) -> Any: ...
    def add_LosingFocus(self, _p0: Any = ...) -> Any: ...
    def remove_LosingFocus(self, _p0: Any = ...) -> Any: ...
    def add_NoFocusCandidateFound(self, _p0: Any = ...) -> Any: ...
    def remove_NoFocusCandidateFound(self, _p0: Any = ...) -> Any: ...
    def add_PreviewKeyDown(self, _p0: Any = ...) -> Any: ...
    def remove_PreviewKeyDown(self, _p0: Any = ...) -> Any: ...
    def add_PreviewKeyUp(self, _p0: Any = ...) -> Any: ...
    def remove_PreviewKeyUp(self, _p0: Any = ...) -> Any: ...
    def add_BringIntoViewRequested(self, _p0: Any = ...) -> Any: ...
    def remove_BringIntoViewRequested(self, _p0: Any = ...) -> Any: ...
    def Measure(self, _p0: Any = ...) -> Any: ...
    def Arrange(self, _p0: Any = ...) -> Any: ...
    def CapturePointer(self, _p0: Any = ...) -> Any: ...
    def ReleasePointerCapture(self, _p0: Any = ...) -> Any: ...
    def ReleasePointerCaptures(self) -> Any: ...
    def AddHandler(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def RemoveHandler(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def TransformToVisual(self, _p0: Any = ...) -> Any: ...
    def InvalidateMeasure(self) -> Any: ...
    def InvalidateArrange(self) -> Any: ...
    def UpdateLayout(self) -> Any: ...
    def CancelDirectManipulations(self) -> Any: ...
    def StartDragAsync(self, _p0: Any = ...) -> Any: ...
    def StartBringIntoView(self) -> Any: ...
    def StartBringIntoViewWithOptions(self, _p0: Any = ...) -> Any: ...
    def TryInvokeKeyboardAccelerator(self, _p0: Any = ...) -> Any: ...
    def Focus(self, _p0: Any = ...) -> Any: ...
    def StartAnimation(self, _p0: Any = ...) -> Any: ...
    def StopAnimation(self, _p0: Any = ...) -> Any: ...

class IUIElementProtected:
    ProtectedCursor: Any

class IUIElementStatics:
    AccessKeyProperty: Any
    AccessKeyScopeOwnerProperty: Any
    AllowDropProperty: Any
    BringIntoViewRequestedEvent: Any
    CacheModeProperty: Any
    CanBeScrollAnchorProperty: Any
    CanDragProperty: Any
    CharacterReceivedEvent: Any
    ClipProperty: Any
    CompositeModeProperty: Any
    ContextFlyoutProperty: Any
    ContextRequestedEvent: Any
    DoubleTappedEvent: Any
    DragEnterEvent: Any
    DragLeaveEvent: Any
    DragOverEvent: Any
    DropEvent: Any
    ExitDisplayModeOnAccessKeyInvokedProperty: Any
    FocusStateProperty: Any
    GettingFocusEvent: Any
    HighContrastAdjustmentProperty: Any
    HoldingEvent: Any
    IsAccessKeyScopeProperty: Any
    IsDoubleTapEnabledProperty: Any
    IsHitTestVisibleProperty: Any
    IsHoldingEnabledProperty: Any
    IsRightTapEnabledProperty: Any
    IsTabStopProperty: Any
    IsTapEnabledProperty: Any
    KeyDownEvent: Any
    KeyTipHorizontalOffsetProperty: Any
    KeyTipPlacementModeProperty: Any
    KeyTipTargetProperty: Any
    KeyTipVerticalOffsetProperty: Any
    KeyUpEvent: Any
    KeyboardAcceleratorPlacementModeProperty: Any
    KeyboardAcceleratorPlacementTargetProperty: Any
    LightsProperty: Any
    LosingFocusEvent: Any
    ManipulationCompletedEvent: Any
    ManipulationDeltaEvent: Any
    ManipulationInertiaStartingEvent: Any
    ManipulationModeProperty: Any
    ManipulationStartedEvent: Any
    ManipulationStartingEvent: Any
    NoFocusCandidateFoundEvent: Any
    OpacityProperty: Any
    PointerCanceledEvent: Any
    PointerCaptureLostEvent: Any
    PointerCapturesProperty: Any
    PointerEnteredEvent: Any
    PointerExitedEvent: Any
    PointerMovedEvent: Any
    PointerPressedEvent: Any
    PointerReleasedEvent: Any
    PointerWheelChangedEvent: Any
    PreviewKeyDownEvent: Any
    PreviewKeyUpEvent: Any
    ProjectionProperty: Any
    RenderTransformOriginProperty: Any
    RenderTransformProperty: Any
    RightTappedEvent: Any
    ShadowProperty: Any
    TabFocusNavigationProperty: Any
    TabIndexProperty: Any
    TappedEvent: Any
    Transform3DProperty: Any
    TransitionsProperty: Any
    UseLayoutRoundingProperty: Any
    UseSystemFocusVisualsProperty: Any
    VisibilityProperty: Any
    XYFocusDownNavigationStrategyProperty: Any
    XYFocusDownProperty: Any
    XYFocusKeyboardNavigationProperty: Any
    XYFocusLeftNavigationStrategyProperty: Any
    XYFocusLeftProperty: Any
    XYFocusRightNavigationStrategyProperty: Any
    XYFocusRightProperty: Any
    XYFocusUpNavigationStrategyProperty: Any
    XYFocusUpProperty: Any
    def TryStartDirectManipulation(self, _p0: Any = ...) -> Any: ...
    def RegisterAsScrollPort(self, _p0: Any = ...) -> Any: ...

class IUnhandledExceptionEventArgs:
    Exception: Any
    Handled: Any
    Message: Any

class IVector3Transition:
    Components: Any
    Duration: Any

class IVisualState:
    Name: Any
    Setters: Any
    StateTriggers: Any
    Storyboard: Any

class IVisualStateChangedEventArgs:
    Control: Any
    NewState: Any
    OldState: Any

class IVisualStateGroup:
    CurrentState: Any
    Name: Any
    States: Any
    Transitions: Any
    CurrentStateChanged: Any
    CurrentStateChanging: Any
    def add_CurrentStateChanged(self, _p0: Any = ...) -> Any: ...
    def remove_CurrentStateChanged(self, _p0: Any = ...) -> Any: ...
    def add_CurrentStateChanging(self, _p0: Any = ...) -> Any: ...
    def remove_CurrentStateChanging(self, _p0: Any = ...) -> Any: ...

class IVisualStateManagerStatics:
    CustomVisualStateManagerProperty: Any
    def GetVisualStateGroups(self, _p0: Any = ...) -> Any: ...
    def GetCustomVisualStateManager(self, _p0: Any = ...) -> Any: ...
    def SetCustomVisualStateManager(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GoToState(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...

class IVisualTransition:
    From: Any
    GeneratedDuration: Any
    GeneratedEasingFunction: Any
    Storyboard: Any
    To: Any

class IWindow:
    Bounds: Any
    Compositor: Any
    Content: Any
    CoreWindow: Any
    Dispatcher: Any
    DispatcherQueue: Any
    ExtendsContentIntoTitleBar: Any
    Title: Any
    Visible: Any
    Activated: Any
    Closed: Any
    SizeChanged: Any
    VisibilityChanged: Any
    def add_Activated(self, _p0: Any = ...) -> Any: ...
    def remove_Activated(self, _p0: Any = ...) -> Any: ...
    def add_Closed(self, _p0: Any = ...) -> Any: ...
    def remove_Closed(self, _p0: Any = ...) -> Any: ...
    def add_SizeChanged(self, _p0: Any = ...) -> Any: ...
    def remove_SizeChanged(self, _p0: Any = ...) -> Any: ...
    def add_VisibilityChanged(self, _p0: Any = ...) -> Any: ...
    def remove_VisibilityChanged(self, _p0: Any = ...) -> Any: ...
    def Activate(self) -> Any: ...
    def Close(self) -> Any: ...
    def SetTitleBar(self, _p0: Any = ...) -> Any: ...

class IWindow2:
    AppWindow: Any
    SystemBackdrop: Any

class IWindowActivatedEventArgs:
    Handled: Any
    WindowActivationState: Any

class IWindowEventArgs:
    Handled: Any

class IWindowSizeChangedEventArgs:
    Handled: Any
    Size: Any

class IWindowStatics:
    Current: Any

class IWindowVisibilityChangedEventArgs:
    Handled: Any
    Visible: Any

class IXamlIsland:
    Content: Any
    ContentIsland: Any
    SystemBackdrop: Any

class IXamlResourceReferenceFailedEventArgs:
    Message: Any

class IXamlRoot:
    Content: Any
    IsHostVisible: Any
    RasterizationScale: Any
    Size: Any
    Changed: Any
    def add_Changed(self, _p0: Any = ...) -> Any: ...
    def remove_Changed(self, _p0: Any = ...) -> Any: ...

class IXamlRoot2:
    ContentIslandEnvironment: Any

class IXamlRoot3:
    CoordinateConverter: Any

class IXamlRoot4:
    ContentIsland: Any

class LaunchActivatedEventArgs:
    Arguments: Any
    UWPLaunchActivatedEventArgs: Any

class LayoutCycleDebugBreakLevel(int):
    None_: int
    Low: int
    High: int

class LayoutCycleTracingLevel(int):
    None_: int
    Low: int
    High: int

class LeavingBackgroundEventHandler:
    def Invoke(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class LineStackingStrategy(int):
    MaxHeight: int
    BlockLineHeight: int
    BaselineToBaseline: int

class MediaFailedRoutedEventArgs(ExceptionRoutedEventArgs):
    ErrorTrace: Any

class OpticalMarginAlignment(int):
    None_: int
    TrimSideBearings: int

class PointHelper:
    @classmethod
    def FromCoordinates(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class PropertyChangedCallback:
    def Invoke(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class PropertyMetadata:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    CreateDefaultValueCallback: Any
    DefaultValue: Any
    @classmethod
    def CreateInstanceWithDefaultValue(
        cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...
    ) -> Any: ...
    @classmethod
    def CreateInstanceWithDefaultValueAndCallback(
        cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...
    ) -> Any: ...
    @classmethod
    def CreateWithDefaultValue(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def CreateWithDefaultValueAndCallback(
        cls, _p0: Any = ..., _p1: Any = ...
    ) -> Any: ...
    @classmethod
    def CreateWithFactory(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def CreateWithFactoryAndCallback(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class PropertyPath(DependencyObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Path: Any

class RectHelper:
    Empty: Any
    @classmethod
    def FromCoordinatesAndDimensions(
        cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...
    ) -> Any: ...
    @classmethod
    def FromPoints(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def FromLocationAndSize(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def GetIsEmpty(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def GetBottom(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def GetLeft(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def GetRight(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def GetTop(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def Contains(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def Equals(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def Intersect(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def UnionWithPoint(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def UnionWithRect(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class ResourceDictionary(DependencyObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    MergedDictionaries: Any
    Size: Any
    Source: Any
    ThemeDictionaries: Any
    def Lookup(self, _p0: Any = ...) -> Any: ...
    def HasKey(self, _p0: Any = ...) -> Any: ...
    def GetView(self) -> Any: ...
    def Insert(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def Remove(self, _p0: Any = ...) -> Any: ...
    def Clear(self) -> Any: ...
    def First(self) -> Any: ...

class ResourceManagerRequestedEventArgs:
    CustomResourceManager: Any

class RoutedEvent: ...

class RoutedEventArgs:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    OriginalSource: Any

class RoutedEventHandler:
    def Invoke(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class ScalarTransition:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Duration: Any

class Setter(SetterBase):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Property: Any
    Target: Any
    Value: Any

class SetterBase(DependencyObject):
    IsSealed: Any

class SetterBaseCollection:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    IsSealed: Any
    Size: Any
    def GetAt(self, _p0: Any = ...) -> Any: ...
    def GetView(self) -> Any: ...
    def IndexOf(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def SetAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def InsertAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def RemoveAt(self, _p0: Any = ...) -> Any: ...
    def Append(self, _p0: Any = ...) -> Any: ...
    def RemoveAtEnd(self) -> Any: ...
    def Clear(self) -> Any: ...
    def GetMany(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def ReplaceAll(self, _p0: Any = ...) -> Any: ...
    def First(self) -> Any: ...

class SizeChangedEventArgs(RoutedEventArgs):
    NewSize: Any
    PreviousSize: Any

class SizeChangedEventHandler:
    def Invoke(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class SizeHelper:
    Empty: Any
    @classmethod
    def FromDimensions(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def GetIsEmpty(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def Equals(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class StateTrigger(StateTriggerBase):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    IsActive: Any
    IsActiveProperty: Any

class StateTriggerBase(DependencyObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def SetActive(self, _p0: Any = ...) -> Any: ...

class Style(DependencyObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    BasedOn: Any
    IsSealed: Any
    Setters: Any
    TargetType: Any
    def Seal(self) -> Any: ...

class SuspendingEventHandler:
    def Invoke(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class TargetPropertyPath:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Path: Any
    Target: Any

class TextAlignment(int):
    Center: int
    Left: int
    Start: int
    Right: int
    End: int
    Justify: int
    DetectFromContent: int

class TextLineBounds(int):
    Full: int
    TrimToCapHeight: int
    TrimToBaseline: int
    Tight: int

class TextReadingOrder(int):
    Default: int
    UseFlowDirection: int
    DetectFromContent: int

class TextTrimming(int):
    None_: int
    CharacterEllipsis: int
    WordEllipsis: int
    Clip: int

class TextWrapping(int):
    NoWrap: int
    Wrap: int
    WrapWholeWords: int

class Thickness:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Left: Any
    Top: Any
    Right: Any
    Bottom: Any

class ThicknessHelper:
    @classmethod
    def FromLengths(
        cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...
    ) -> Any: ...
    @classmethod
    def FromUniformLength(cls, _p0: Any = ...) -> Any: ...

class TriggerAction(DependencyObject): ...

class TriggerActionCollection:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any
    def GetAt(self, _p0: Any = ...) -> Any: ...
    def GetView(self) -> Any: ...
    def IndexOf(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def SetAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def InsertAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def RemoveAt(self, _p0: Any = ...) -> Any: ...
    def Append(self, _p0: Any = ...) -> Any: ...
    def RemoveAtEnd(self) -> Any: ...
    def Clear(self) -> Any: ...
    def GetMany(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def ReplaceAll(self, _p0: Any = ...) -> Any: ...
    def First(self) -> Any: ...

class TriggerBase(DependencyObject): ...

class TriggerCollection:
    Size: Any
    def GetAt(self, _p0: Any = ...) -> Any: ...
    def GetView(self) -> Any: ...
    def IndexOf(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def SetAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def InsertAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def RemoveAt(self, _p0: Any = ...) -> Any: ...
    def Append(self, _p0: Any = ...) -> Any: ...
    def RemoveAtEnd(self) -> Any: ...
    def Clear(self) -> Any: ...
    def GetMany(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def ReplaceAll(self, _p0: Any = ...) -> Any: ...
    def First(self) -> Any: ...

class UIElement(DependencyObject):
    AccessKey: Any
    AccessKeyScopeOwner: Any
    ActualOffset: Any
    ActualSize: Any
    AllowDrop: Any
    CacheMode: Any
    CanBeScrollAnchor: Any
    CanDrag: Any
    CenterPoint: Any
    Clip: Any
    CompositeMode: Any
    ContextFlyout: Any
    DesiredSize: Any
    ExitDisplayModeOnAccessKeyInvoked: Any
    FocusState: Any
    HighContrastAdjustment: Any
    IsAccessKeyScope: Any
    IsDoubleTapEnabled: Any
    IsHitTestVisible: Any
    IsHoldingEnabled: Any
    IsRightTapEnabled: Any
    IsTabStop: Any
    IsTapEnabled: Any
    KeyTipHorizontalOffset: Any
    KeyTipPlacementMode: Any
    KeyTipTarget: Any
    KeyTipVerticalOffset: Any
    KeyboardAcceleratorPlacementMode: Any
    KeyboardAcceleratorPlacementTarget: Any
    KeyboardAccelerators: Any
    Lights: Any
    ManipulationMode: Any
    Opacity: Any
    OpacityTransition: Any
    PointerCaptures: Any
    Projection: Any
    ProtectedCursor: Any
    RasterizationScale: Any
    RenderSize: Any
    RenderTransform: Any
    RenderTransformOrigin: Any
    Rotation: Any
    RotationAxis: Any
    RotationTransition: Any
    Scale: Any
    ScaleTransition: Any
    Shadow: Any
    TabFocusNavigation: Any
    TabIndex: Any
    Transform3D: Any
    TransformMatrix: Any
    Transitions: Any
    Translation: Any
    TranslationTransition: Any
    UseLayoutRounding: Any
    UseSystemFocusVisuals: Any
    Visibility: Any
    XYFocusDown: Any
    XYFocusDownNavigationStrategy: Any
    XYFocusKeyboardNavigation: Any
    XYFocusLeft: Any
    XYFocusLeftNavigationStrategy: Any
    XYFocusRight: Any
    XYFocusRightNavigationStrategy: Any
    XYFocusUp: Any
    XYFocusUpNavigationStrategy: Any
    XamlRoot: Any
    AccessKeyDisplayDismissed: Any
    AccessKeyDisplayRequested: Any
    AccessKeyInvoked: Any
    BringIntoViewRequested: Any
    CharacterReceived: Any
    ContextCanceled: Any
    ContextRequested: Any
    DoubleTapped: Any
    DragEnter: Any
    DragLeave: Any
    DragOver: Any
    DragStarting: Any
    Drop: Any
    DropCompleted: Any
    GettingFocus: Any
    GotFocus: Any
    Holding: Any
    KeyDown: Any
    KeyUp: Any
    LosingFocus: Any
    LostFocus: Any
    ManipulationCompleted: Any
    ManipulationDelta: Any
    ManipulationInertiaStarting: Any
    ManipulationStarted: Any
    ManipulationStarting: Any
    NoFocusCandidateFound: Any
    PointerCanceled: Any
    PointerCaptureLost: Any
    PointerEntered: Any
    PointerExited: Any
    PointerMoved: Any
    PointerPressed: Any
    PointerReleased: Any
    PointerWheelChanged: Any
    PreviewKeyDown: Any
    PreviewKeyUp: Any
    ProcessKeyboardAccelerators: Any
    RightTapped: Any
    Tapped: Any
    AccessKeyProperty: Any
    AccessKeyScopeOwnerProperty: Any
    AllowDropProperty: Any
    BringIntoViewRequestedEvent: Any
    CacheModeProperty: Any
    CanBeScrollAnchorProperty: Any
    CanDragProperty: Any
    CharacterReceivedEvent: Any
    ClipProperty: Any
    CompositeModeProperty: Any
    ContextFlyoutProperty: Any
    ContextRequestedEvent: Any
    DoubleTappedEvent: Any
    DragEnterEvent: Any
    DragLeaveEvent: Any
    DragOverEvent: Any
    DropEvent: Any
    ExitDisplayModeOnAccessKeyInvokedProperty: Any
    FocusStateProperty: Any
    GettingFocusEvent: Any
    HighContrastAdjustmentProperty: Any
    HoldingEvent: Any
    IsAccessKeyScopeProperty: Any
    IsDoubleTapEnabledProperty: Any
    IsHitTestVisibleProperty: Any
    IsHoldingEnabledProperty: Any
    IsRightTapEnabledProperty: Any
    IsTabStopProperty: Any
    IsTapEnabledProperty: Any
    KeyDownEvent: Any
    KeyTipHorizontalOffsetProperty: Any
    KeyTipPlacementModeProperty: Any
    KeyTipTargetProperty: Any
    KeyTipVerticalOffsetProperty: Any
    KeyUpEvent: Any
    KeyboardAcceleratorPlacementModeProperty: Any
    KeyboardAcceleratorPlacementTargetProperty: Any
    LightsProperty: Any
    LosingFocusEvent: Any
    ManipulationCompletedEvent: Any
    ManipulationDeltaEvent: Any
    ManipulationInertiaStartingEvent: Any
    ManipulationModeProperty: Any
    ManipulationStartedEvent: Any
    ManipulationStartingEvent: Any
    NoFocusCandidateFoundEvent: Any
    OpacityProperty: Any
    PointerCanceledEvent: Any
    PointerCaptureLostEvent: Any
    PointerCapturesProperty: Any
    PointerEnteredEvent: Any
    PointerExitedEvent: Any
    PointerMovedEvent: Any
    PointerPressedEvent: Any
    PointerReleasedEvent: Any
    PointerWheelChangedEvent: Any
    PreviewKeyDownEvent: Any
    PreviewKeyUpEvent: Any
    ProjectionProperty: Any
    RenderTransformOriginProperty: Any
    RenderTransformProperty: Any
    RightTappedEvent: Any
    ShadowProperty: Any
    TabFocusNavigationProperty: Any
    TabIndexProperty: Any
    TappedEvent: Any
    Transform3DProperty: Any
    TransitionsProperty: Any
    UseLayoutRoundingProperty: Any
    UseSystemFocusVisualsProperty: Any
    VisibilityProperty: Any
    XYFocusDownNavigationStrategyProperty: Any
    XYFocusDownProperty: Any
    XYFocusKeyboardNavigationProperty: Any
    XYFocusLeftNavigationStrategyProperty: Any
    XYFocusLeftProperty: Any
    XYFocusRightNavigationStrategyProperty: Any
    XYFocusRightProperty: Any
    XYFocusUpNavigationStrategyProperty: Any
    XYFocusUpProperty: Any
    def add_KeyUp(self, _p0: Any = ...) -> Any: ...
    def remove_KeyUp(self, _p0: Any = ...) -> Any: ...
    def add_KeyDown(self, _p0: Any = ...) -> Any: ...
    def remove_KeyDown(self, _p0: Any = ...) -> Any: ...
    def add_GotFocus(self, _p0: Any = ...) -> Any: ...
    def remove_GotFocus(self, _p0: Any = ...) -> Any: ...
    def add_LostFocus(self, _p0: Any = ...) -> Any: ...
    def remove_LostFocus(self, _p0: Any = ...) -> Any: ...
    def add_DragStarting(self, _p0: Any = ...) -> Any: ...
    def remove_DragStarting(self, _p0: Any = ...) -> Any: ...
    def add_DropCompleted(self, _p0: Any = ...) -> Any: ...
    def remove_DropCompleted(self, _p0: Any = ...) -> Any: ...
    def add_CharacterReceived(self, _p0: Any = ...) -> Any: ...
    def remove_CharacterReceived(self, _p0: Any = ...) -> Any: ...
    def add_DragEnter(self, _p0: Any = ...) -> Any: ...
    def remove_DragEnter(self, _p0: Any = ...) -> Any: ...
    def add_DragLeave(self, _p0: Any = ...) -> Any: ...
    def remove_DragLeave(self, _p0: Any = ...) -> Any: ...
    def add_DragOver(self, _p0: Any = ...) -> Any: ...
    def remove_DragOver(self, _p0: Any = ...) -> Any: ...
    def add_Drop(self, _p0: Any = ...) -> Any: ...
    def remove_Drop(self, _p0: Any = ...) -> Any: ...
    def add_PointerPressed(self, _p0: Any = ...) -> Any: ...
    def remove_PointerPressed(self, _p0: Any = ...) -> Any: ...
    def add_PointerMoved(self, _p0: Any = ...) -> Any: ...
    def remove_PointerMoved(self, _p0: Any = ...) -> Any: ...
    def add_PointerReleased(self, _p0: Any = ...) -> Any: ...
    def remove_PointerReleased(self, _p0: Any = ...) -> Any: ...
    def add_PointerEntered(self, _p0: Any = ...) -> Any: ...
    def remove_PointerEntered(self, _p0: Any = ...) -> Any: ...
    def add_PointerExited(self, _p0: Any = ...) -> Any: ...
    def remove_PointerExited(self, _p0: Any = ...) -> Any: ...
    def add_PointerCaptureLost(self, _p0: Any = ...) -> Any: ...
    def remove_PointerCaptureLost(self, _p0: Any = ...) -> Any: ...
    def add_PointerCanceled(self, _p0: Any = ...) -> Any: ...
    def remove_PointerCanceled(self, _p0: Any = ...) -> Any: ...
    def add_PointerWheelChanged(self, _p0: Any = ...) -> Any: ...
    def remove_PointerWheelChanged(self, _p0: Any = ...) -> Any: ...
    def add_Tapped(self, _p0: Any = ...) -> Any: ...
    def remove_Tapped(self, _p0: Any = ...) -> Any: ...
    def add_DoubleTapped(self, _p0: Any = ...) -> Any: ...
    def remove_DoubleTapped(self, _p0: Any = ...) -> Any: ...
    def add_Holding(self, _p0: Any = ...) -> Any: ...
    def remove_Holding(self, _p0: Any = ...) -> Any: ...
    def add_ContextRequested(self, _p0: Any = ...) -> Any: ...
    def remove_ContextRequested(self, _p0: Any = ...) -> Any: ...
    def add_ContextCanceled(self, _p0: Any = ...) -> Any: ...
    def remove_ContextCanceled(self, _p0: Any = ...) -> Any: ...
    def add_RightTapped(self, _p0: Any = ...) -> Any: ...
    def remove_RightTapped(self, _p0: Any = ...) -> Any: ...
    def add_ManipulationStarting(self, _p0: Any = ...) -> Any: ...
    def remove_ManipulationStarting(self, _p0: Any = ...) -> Any: ...
    def add_ManipulationInertiaStarting(self, _p0: Any = ...) -> Any: ...
    def remove_ManipulationInertiaStarting(self, _p0: Any = ...) -> Any: ...
    def add_ManipulationStarted(self, _p0: Any = ...) -> Any: ...
    def remove_ManipulationStarted(self, _p0: Any = ...) -> Any: ...
    def add_ManipulationDelta(self, _p0: Any = ...) -> Any: ...
    def remove_ManipulationDelta(self, _p0: Any = ...) -> Any: ...
    def add_ManipulationCompleted(self, _p0: Any = ...) -> Any: ...
    def remove_ManipulationCompleted(self, _p0: Any = ...) -> Any: ...
    def add_AccessKeyDisplayRequested(self, _p0: Any = ...) -> Any: ...
    def remove_AccessKeyDisplayRequested(self, _p0: Any = ...) -> Any: ...
    def add_AccessKeyDisplayDismissed(self, _p0: Any = ...) -> Any: ...
    def remove_AccessKeyDisplayDismissed(self, _p0: Any = ...) -> Any: ...
    def add_AccessKeyInvoked(self, _p0: Any = ...) -> Any: ...
    def remove_AccessKeyInvoked(self, _p0: Any = ...) -> Any: ...
    def add_ProcessKeyboardAccelerators(self, _p0: Any = ...) -> Any: ...
    def remove_ProcessKeyboardAccelerators(self, _p0: Any = ...) -> Any: ...
    def add_GettingFocus(self, _p0: Any = ...) -> Any: ...
    def remove_GettingFocus(self, _p0: Any = ...) -> Any: ...
    def add_LosingFocus(self, _p0: Any = ...) -> Any: ...
    def remove_LosingFocus(self, _p0: Any = ...) -> Any: ...
    def add_NoFocusCandidateFound(self, _p0: Any = ...) -> Any: ...
    def remove_NoFocusCandidateFound(self, _p0: Any = ...) -> Any: ...
    def add_PreviewKeyDown(self, _p0: Any = ...) -> Any: ...
    def remove_PreviewKeyDown(self, _p0: Any = ...) -> Any: ...
    def add_PreviewKeyUp(self, _p0: Any = ...) -> Any: ...
    def remove_PreviewKeyUp(self, _p0: Any = ...) -> Any: ...
    def add_BringIntoViewRequested(self, _p0: Any = ...) -> Any: ...
    def remove_BringIntoViewRequested(self, _p0: Any = ...) -> Any: ...
    def Measure(self, _p0: Any = ...) -> Any: ...
    def Arrange(self, _p0: Any = ...) -> Any: ...
    def CapturePointer(self, _p0: Any = ...) -> Any: ...
    def ReleasePointerCapture(self, _p0: Any = ...) -> Any: ...
    def ReleasePointerCaptures(self) -> Any: ...
    def AddHandler(self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    def RemoveHandler(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def TransformToVisual(self, _p0: Any = ...) -> Any: ...
    def InvalidateMeasure(self) -> Any: ...
    def InvalidateArrange(self) -> Any: ...
    def UpdateLayout(self) -> Any: ...
    def CancelDirectManipulations(self) -> Any: ...
    def StartDragAsync(self, _p0: Any = ...) -> Any: ...
    def StartBringIntoView(self) -> Any: ...
    def StartBringIntoViewWithOptions(self, _p0: Any = ...) -> Any: ...
    def TryInvokeKeyboardAccelerator(self, _p0: Any = ...) -> Any: ...
    def Focus(self, _p0: Any = ...) -> Any: ...
    def StartAnimation(self, _p0: Any = ...) -> Any: ...
    def StopAnimation(self, _p0: Any = ...) -> Any: ...
    def OnCreateAutomationPeer(self) -> Any: ...
    def OnDisconnectVisualChildren(self) -> Any: ...
    def FindSubElementsForTouchTargeting(
        self, _p0: Any = ..., _p1: Any = ...
    ) -> Any: ...
    def GetChildrenInTabFocusOrder(self) -> Any: ...
    def OnKeyboardAcceleratorInvoked(self, _p0: Any = ...) -> Any: ...
    def OnProcessKeyboardAccelerators(self, _p0: Any = ...) -> Any: ...
    def OnBringIntoViewRequested(self, _p0: Any = ...) -> Any: ...
    def PopulatePropertyInfoOverride(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def PopulatePropertyInfo(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def GetVisualInternal(self) -> Any: ...
    @classmethod
    def TryStartDirectManipulation(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def RegisterAsScrollPort(cls, _p0: Any = ...) -> Any: ...

class UIElementWeakCollection:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any
    def GetAt(self, _p0: Any = ...) -> Any: ...
    def GetView(self) -> Any: ...
    def IndexOf(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def SetAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def InsertAt(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def RemoveAt(self, _p0: Any = ...) -> Any: ...
    def Append(self, _p0: Any = ...) -> Any: ...
    def RemoveAtEnd(self) -> Any: ...
    def Clear(self) -> Any: ...
    def GetMany(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def ReplaceAll(self, _p0: Any = ...) -> Any: ...
    def First(self) -> Any: ...

class UnhandledExceptionEventArgs:
    Exception: Any
    Handled: Any
    Message: Any

class UnhandledExceptionEventHandler:
    def Invoke(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class Vector3Transition:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Components: Any
    Duration: Any

class Vector3TransitionComponents(int):
    X: int
    Y: int
    Z: int

class VerticalAlignment(int):
    Top: int
    Center: int
    Bottom: int
    Stretch: int

class Visibility(int):
    Visible: int
    Collapsed: int

class VisualState(DependencyObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Name: Any
    Setters: Any
    StateTriggers: Any
    Storyboard: Any

class VisualStateChangedEventArgs:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Control: Any
    NewState: Any
    OldState: Any

class VisualStateChangedEventHandler:
    def Invoke(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class VisualStateGroup(DependencyObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    CurrentState: Any
    Name: Any
    States: Any
    Transitions: Any
    CurrentStateChanged: Any
    CurrentStateChanging: Any
    def add_CurrentStateChanged(self, _p0: Any = ...) -> Any: ...
    def remove_CurrentStateChanged(self, _p0: Any = ...) -> Any: ...
    def add_CurrentStateChanging(self, _p0: Any = ...) -> Any: ...
    def remove_CurrentStateChanging(self, _p0: Any = ...) -> Any: ...

class VisualStateManager(DependencyObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    CustomVisualStateManagerProperty: Any
    def RaiseCurrentStateChanging(
        self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...
    ) -> Any: ...
    def RaiseCurrentStateChanged(
        self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...
    ) -> Any: ...
    def GoToStateCore(
        self,
        _p0: Any = ...,
        _p1: Any = ...,
        _p2: Any = ...,
        _p3: Any = ...,
        _p4: Any = ...,
        _p5: Any = ...,
    ) -> Any: ...
    @classmethod
    def GetVisualStateGroups(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def GetCustomVisualStateManager(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def SetCustomVisualStateManager(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def GoToState(cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...

class VisualTransition(DependencyObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    From: Any
    GeneratedDuration: Any
    GeneratedEasingFunction: Any
    Storyboard: Any
    To: Any

class Window:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    AppWindow: Any
    Bounds: Any
    Compositor: Any
    Content: Any
    CoreWindow: Any
    Dispatcher: Any
    DispatcherQueue: Any
    ExtendsContentIntoTitleBar: Any
    SystemBackdrop: Any
    Title: Any
    Visible: Any
    Activated: Any
    Closed: Any
    SizeChanged: Any
    VisibilityChanged: Any
    Current: Any
    def add_Activated(self, _p0: Any = ...) -> Any: ...
    def remove_Activated(self, _p0: Any = ...) -> Any: ...
    def add_Closed(self, _p0: Any = ...) -> Any: ...
    def remove_Closed(self, _p0: Any = ...) -> Any: ...
    def add_SizeChanged(self, _p0: Any = ...) -> Any: ...
    def remove_SizeChanged(self, _p0: Any = ...) -> Any: ...
    def add_VisibilityChanged(self, _p0: Any = ...) -> Any: ...
    def remove_VisibilityChanged(self, _p0: Any = ...) -> Any: ...
    def Activate(self) -> Any: ...
    def Close(self) -> Any: ...
    def SetTitleBar(self, _p0: Any = ...) -> Any: ...

class WindowActivatedEventArgs:
    Handled: Any
    WindowActivationState: Any

class WindowActivationState(int):
    CodeActivated: int
    Deactivated: int
    PointerActivated: int

class WindowEventArgs:
    Handled: Any

class WindowSizeChangedEventArgs:
    Handled: Any
    Size: Any

class WindowVisibilityChangedEventArgs:
    Handled: Any
    Visible: Any

class XamlIsland:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Content: Any
    ContentIsland: Any
    SystemBackdrop: Any
    def Close(self) -> Any: ...

class XamlResourceReferenceFailedEventArgs:
    Message: Any

class XamlRoot:
    Content: Any
    ContentIsland: Any
    ContentIslandEnvironment: Any
    CoordinateConverter: Any
    IsHostVisible: Any
    RasterizationScale: Any
    Size: Any
    Changed: Any
    def add_Changed(self, _p0: Any = ...) -> Any: ...
    def remove_Changed(self, _p0: Any = ...) -> Any: ...

class XamlRootChangedEventArgs: ...
