# Auto-generated type stubs for win32more
# Generated by winui3/tools/generate_win32more_stubs.py
# Property types are typed as Any; the goal is attribute existence,
# not full type safety for win32more internals.

from typing import Any

class AppActivationResult:
    AppResourceGroupInfo: Any
    ExtendedError: Any

class AppDiagnosticInfo:
    AppInfo: Any
    def GetResourceGroups(self) -> Any: ...
    def CreateResourceGroupWatcher(self) -> Any: ...
    def LaunchAsync(self) -> Any: ...
    @classmethod
    def CreateWatcher(cls) -> Any: ...
    @classmethod
    def RequestAccessAsync(cls) -> Any: ...
    @classmethod
    def RequestInfoForPackageAsync(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def RequestInfoForAppAsync(cls) -> Any: ...
    @classmethod
    def RequestInfoForAppUserModelId(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def RequestInfoAsync(cls) -> Any: ...

class AppDiagnosticInfoWatcher:
    Status: Any
    Added: Any
    EnumerationCompleted: Any
    Removed: Any
    Stopped: Any
    def add_Added(self, _p0: Any = ...) -> Any: ...
    def remove_Added(self, _p0: Any = ...) -> Any: ...
    def add_Removed(self, _p0: Any = ...) -> Any: ...
    def remove_Removed(self, _p0: Any = ...) -> Any: ...
    def add_EnumerationCompleted(self, _p0: Any = ...) -> Any: ...
    def remove_EnumerationCompleted(self, _p0: Any = ...) -> Any: ...
    def add_Stopped(self, _p0: Any = ...) -> Any: ...
    def remove_Stopped(self, _p0: Any = ...) -> Any: ...
    def Start(self) -> Any: ...
    def Stop(self) -> Any: ...

class AppDiagnosticInfoWatcherEventArgs:
    AppDiagnosticInfo: Any

class AppDiagnosticInfoWatcherStatus(int):
    Created: int
    Started: int
    EnumerationCompleted: int
    Stopping: int
    Stopped: int
    Aborted: int

class AppExecutionStateChangeResult:
    ExtendedError: Any

class AppMemoryReport:
    ExpectedTotalCommitLimit: Any
    PeakPrivateCommitUsage: Any
    PrivateCommitUsage: Any
    TotalCommitLimit: Any
    TotalCommitUsage: Any

class AppMemoryUsageLevel(int):
    Low: int
    Medium: int
    High: int
    OverLimit: int

class AppMemoryUsageLimitChangingEventArgs:
    NewLimit: Any
    OldLimit: Any

class AppResourceGroupBackgroundTaskReport:
    EntryPoint: Any
    Name: Any
    TaskId: Any
    Trigger: Any

class AppResourceGroupEnergyQuotaState(int):
    Unknown: int
    Over: int
    Under: int

class AppResourceGroupExecutionState(int):
    Unknown: int
    Running: int
    Suspending: int
    Suspended: int
    NotRunning: int

class AppResourceGroupInfo:
    InstanceId: Any
    IsShared: Any
    def GetBackgroundTaskReports(self) -> Any: ...
    def GetMemoryReport(self) -> Any: ...
    def GetProcessDiagnosticInfos(self) -> Any: ...
    def GetStateReport(self) -> Any: ...
    def StartSuspendAsync(self) -> Any: ...
    def StartResumeAsync(self) -> Any: ...
    def StartTerminateAsync(self) -> Any: ...

class AppResourceGroupInfoWatcher:
    Status: Any
    Added: Any
    EnumerationCompleted: Any
    ExecutionStateChanged: Any
    Removed: Any
    Stopped: Any
    def add_Added(self, _p0: Any = ...) -> Any: ...
    def remove_Added(self, _p0: Any = ...) -> Any: ...
    def add_Removed(self, _p0: Any = ...) -> Any: ...
    def remove_Removed(self, _p0: Any = ...) -> Any: ...
    def add_EnumerationCompleted(self, _p0: Any = ...) -> Any: ...
    def remove_EnumerationCompleted(self, _p0: Any = ...) -> Any: ...
    def add_Stopped(self, _p0: Any = ...) -> Any: ...
    def remove_Stopped(self, _p0: Any = ...) -> Any: ...
    def add_ExecutionStateChanged(self, _p0: Any = ...) -> Any: ...
    def remove_ExecutionStateChanged(self, _p0: Any = ...) -> Any: ...
    def Start(self) -> Any: ...
    def Stop(self) -> Any: ...

class AppResourceGroupInfoWatcherEventArgs:
    AppDiagnosticInfos: Any
    AppResourceGroupInfo: Any

class AppResourceGroupInfoWatcherExecutionStateChangedEventArgs:
    AppDiagnosticInfos: Any
    AppResourceGroupInfo: Any

class AppResourceGroupInfoWatcherStatus(int):
    Created: int
    Started: int
    EnumerationCompleted: int
    Stopping: int
    Stopped: int
    Aborted: int

class AppResourceGroupMemoryReport:
    CommitUsageLevel: Any
    CommitUsageLimit: Any
    PrivateCommitUsage: Any
    TotalCommitUsage: Any

class AppResourceGroupStateReport:
    EnergyQuotaState: Any
    ExecutionState: Any

class AppUriHandlerHost:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    IsEnabled: Any
    Name: Any

class AppUriHandlerRegistration:
    Name: Any
    PackageFamilyName: Any
    User: Any
    def GetAppAddedHostsAsync(self) -> Any: ...
    def SetAppAddedHostsAsync(self, _p0: Any = ...) -> Any: ...
    def GetAllHosts(self) -> Any: ...
    def UpdateHosts(self, _p0: Any = ...) -> Any: ...

class AppUriHandlerRegistrationManager:
    PackageFamilyName: Any
    User: Any
    def TryGetRegistration(self, _p0: Any = ...) -> Any: ...
    @classmethod
    def GetForPackage(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def GetForPackageForUser(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def GetDefault(cls) -> Any: ...
    @classmethod
    def GetForUser(cls, _p0: Any = ...) -> Any: ...

class AutoUpdateTimeZoneStatus(int):
    Attempted: int
    TimedOut: int
    Failed: int

class DateTimeSettings:
    @classmethod
    def SetSystemDateTime(cls, _p0: Any = ...) -> Any: ...

class DiagnosticAccessStatus(int):
    Unspecified: int
    Denied: int
    Limited: int
    Allowed: int

class DispatcherQueue:
    HasThreadAccess: Any
    ShutdownCompleted: Any
    ShutdownStarting: Any
    def CreateTimer(self) -> Any: ...
    def TryEnqueue(self, _p0: Any = ...) -> Any: ...
    def TryEnqueueWithPriority(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def add_ShutdownStarting(self, _p0: Any = ...) -> Any: ...
    def remove_ShutdownStarting(self, _p0: Any = ...) -> Any: ...
    def add_ShutdownCompleted(self, _p0: Any = ...) -> Any: ...
    def remove_ShutdownCompleted(self, _p0: Any = ...) -> Any: ...
    @classmethod
    def GetForCurrentThread(cls) -> Any: ...

class DispatcherQueueController:
    DispatcherQueue: Any
    def ShutdownQueueAsync(self) -> Any: ...
    @classmethod
    def CreateOnDedicatedThread(cls) -> Any: ...

class DispatcherQueueHandler:
    def Invoke(self) -> Any: ...

class DispatcherQueuePriority(int):
    Normal: int
    High: int

class DispatcherQueueShutdownStartingEventArgs:
    def GetDeferral(self) -> Any: ...

class DispatcherQueueTimer:
    Interval: Any
    IsRepeating: Any
    IsRunning: Any
    Tick: Any
    def Start(self) -> Any: ...
    def Stop(self) -> Any: ...
    def add_Tick(self, _p0: Any = ...) -> Any: ...
    def remove_Tick(self, _p0: Any = ...) -> Any: ...

class FolderLauncherOptions:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    DesiredRemainingView: Any
    ItemsToSelect: Any

class IAppActivationResult:
    AppResourceGroupInfo: Any
    ExtendedError: Any

class IAppDiagnosticInfo:
    AppInfo: Any

class IAppDiagnosticInfoWatcher:
    Status: Any
    Added: Any
    EnumerationCompleted: Any
    Removed: Any
    Stopped: Any
    def add_Added(self, _p0: Any = ...) -> Any: ...
    def remove_Added(self, _p0: Any = ...) -> Any: ...
    def add_Removed(self, _p0: Any = ...) -> Any: ...
    def remove_Removed(self, _p0: Any = ...) -> Any: ...
    def add_EnumerationCompleted(self, _p0: Any = ...) -> Any: ...
    def remove_EnumerationCompleted(self, _p0: Any = ...) -> Any: ...
    def add_Stopped(self, _p0: Any = ...) -> Any: ...
    def remove_Stopped(self, _p0: Any = ...) -> Any: ...
    def Start(self) -> Any: ...
    def Stop(self) -> Any: ...

class IAppDiagnosticInfoWatcherEventArgs:
    AppDiagnosticInfo: Any

class IAppExecutionStateChangeResult:
    ExtendedError: Any

class IAppMemoryReport:
    PeakPrivateCommitUsage: Any
    PrivateCommitUsage: Any
    TotalCommitLimit: Any
    TotalCommitUsage: Any

class IAppMemoryReport2:
    ExpectedTotalCommitLimit: Any

class IAppMemoryUsageLimitChangingEventArgs:
    NewLimit: Any
    OldLimit: Any

class IAppResourceGroupBackgroundTaskReport:
    EntryPoint: Any
    Name: Any
    TaskId: Any
    Trigger: Any

class IAppResourceGroupInfo:
    InstanceId: Any
    IsShared: Any
    def GetBackgroundTaskReports(self) -> Any: ...
    def GetMemoryReport(self) -> Any: ...
    def GetProcessDiagnosticInfos(self) -> Any: ...
    def GetStateReport(self) -> Any: ...

class IAppResourceGroupInfoWatcher:
    Status: Any
    Added: Any
    EnumerationCompleted: Any
    ExecutionStateChanged: Any
    Removed: Any
    Stopped: Any
    def add_Added(self, _p0: Any = ...) -> Any: ...
    def remove_Added(self, _p0: Any = ...) -> Any: ...
    def add_Removed(self, _p0: Any = ...) -> Any: ...
    def remove_Removed(self, _p0: Any = ...) -> Any: ...
    def add_EnumerationCompleted(self, _p0: Any = ...) -> Any: ...
    def remove_EnumerationCompleted(self, _p0: Any = ...) -> Any: ...
    def add_Stopped(self, _p0: Any = ...) -> Any: ...
    def remove_Stopped(self, _p0: Any = ...) -> Any: ...
    def add_ExecutionStateChanged(self, _p0: Any = ...) -> Any: ...
    def remove_ExecutionStateChanged(self, _p0: Any = ...) -> Any: ...
    def Start(self) -> Any: ...
    def Stop(self) -> Any: ...

class IAppResourceGroupInfoWatcherEventArgs:
    AppDiagnosticInfos: Any
    AppResourceGroupInfo: Any

class IAppResourceGroupInfoWatcherExecutionStateChangedEventArgs:
    AppDiagnosticInfos: Any
    AppResourceGroupInfo: Any

class IAppResourceGroupMemoryReport:
    CommitUsageLevel: Any
    CommitUsageLimit: Any
    PrivateCommitUsage: Any
    TotalCommitUsage: Any

class IAppResourceGroupStateReport:
    EnergyQuotaState: Any
    ExecutionState: Any

class IAppUriHandlerHost:
    Name: Any

class IAppUriHandlerHost2:
    IsEnabled: Any

class IAppUriHandlerRegistration:
    Name: Any
    User: Any
    def GetAppAddedHostsAsync(self) -> Any: ...
    def SetAppAddedHostsAsync(self, _p0: Any = ...) -> Any: ...

class IAppUriHandlerRegistration2:
    PackageFamilyName: Any
    def GetAllHosts(self) -> Any: ...
    def UpdateHosts(self, _p0: Any = ...) -> Any: ...

class IAppUriHandlerRegistrationManager:
    User: Any
    def TryGetRegistration(self, _p0: Any = ...) -> Any: ...

class IAppUriHandlerRegistrationManager2:
    PackageFamilyName: Any

class IDispatcherQueue2:
    HasThreadAccess: Any

class IDispatcherQueueController:
    DispatcherQueue: Any
    def ShutdownQueueAsync(self) -> Any: ...

class IDispatcherQueueTimer:
    Interval: Any
    IsRepeating: Any
    IsRunning: Any
    Tick: Any
    def Start(self) -> Any: ...
    def Stop(self) -> Any: ...
    def add_Tick(self, _p0: Any = ...) -> Any: ...
    def remove_Tick(self, _p0: Any = ...) -> Any: ...

class IFolderLauncherOptions:
    ItemsToSelect: Any

class IKnownUserPropertiesStatics:
    AccountName: Any
    DisplayName: Any
    DomainName: Any
    FirstName: Any
    GuestHost: Any
    LastName: Any
    PrincipalName: Any
    ProviderName: Any
    SessionInitiationProtocolUri: Any

class IKnownUserPropertiesStatics2:
    AgeEnforcementRegion: Any

class ILaunchUriResult:
    Result: Any
    Status: Any

class ILauncherOptions:
    ContentType: Any
    DisplayApplicationPicker: Any
    FallbackUri: Any
    PreferredApplicationDisplayName: Any
    PreferredApplicationPackageFamilyName: Any
    TreatAsUntrusted: Any
    UI: Any

class ILauncherOptions2:
    NeighboringFilesQuery: Any
    TargetApplicationPackageFamilyName: Any

class ILauncherOptions3:
    IgnoreAppUriHandlers: Any

class ILauncherOptions4:
    LimitPickerToCurrentAppAndAppUriHandlers: Any

class ILauncherUIOptions:
    InvocationPoint: Any
    PreferredPlacement: Any
    SelectionRect: Any

class ILauncherViewOptions:
    DesiredRemainingView: Any

class IMemoryManagerStatics:
    AppMemoryUsage: Any
    AppMemoryUsageLevel: Any
    AppMemoryUsageLimit: Any
    AppMemoryUsageDecreased: Any
    AppMemoryUsageIncreased: Any
    AppMemoryUsageLimitChanging: Any
    def add_AppMemoryUsageIncreased(self, _p0: Any = ...) -> Any: ...
    def remove_AppMemoryUsageIncreased(self, _p0: Any = ...) -> Any: ...
    def add_AppMemoryUsageDecreased(self, _p0: Any = ...) -> Any: ...
    def remove_AppMemoryUsageDecreased(self, _p0: Any = ...) -> Any: ...
    def add_AppMemoryUsageLimitChanging(self, _p0: Any = ...) -> Any: ...
    def remove_AppMemoryUsageLimitChanging(self, _p0: Any = ...) -> Any: ...

class IMemoryManagerStatics4:
    ExpectedAppMemoryUsageLimit: Any

class IProcessLauncherOptions:
    StandardError: Any
    StandardInput: Any
    StandardOutput: Any
    WorkingDirectory: Any

class IProcessLauncherResult:
    ExitCode: Any

class IProcessMemoryReport:
    PrivateWorkingSetUsage: Any
    TotalWorkingSetUsage: Any

class IRemoteLauncherOptions:
    FallbackUri: Any
    PreferredAppIds: Any

class ITimeZoneSettingsStatics:
    CanChangeTimeZone: Any
    CurrentTimeZoneDisplayName: Any
    SupportedTimeZoneDisplayNames: Any
    def ChangeTimeZoneByDisplayName(self, _p0: Any = ...) -> Any: ...

class IUser:
    AuthenticationStatus: Any
    NonRoamableId: Any
    Type: Any
    def GetPropertyAsync(self, _p0: Any = ...) -> Any: ...
    def GetPropertiesAsync(self, _p0: Any = ...) -> Any: ...
    def GetPictureAsync(self, _p0: Any = ...) -> Any: ...

class IUserAuthenticationStatusChangingEventArgs:
    CurrentStatus: Any
    NewStatus: Any
    User: Any
    def GetDeferral(self) -> Any: ...

class IUserChangedEventArgs:
    User: Any

class IUserChangedEventArgs2:
    ChangedPropertyKinds: Any

class IUserDeviceAssociationChangedEventArgs:
    DeviceId: Any
    NewUser: Any
    OldUser: Any

class IUserPicker:
    AllowGuestAccounts: Any
    SuggestedSelectedUser: Any
    def PickSingleUserAsync(self) -> Any: ...

class IUserWatcher:
    Status: Any
    Added: Any
    AuthenticationStatusChanged: Any
    AuthenticationStatusChanging: Any
    EnumerationCompleted: Any
    Removed: Any
    Stopped: Any
    Updated: Any
    def Start(self) -> Any: ...
    def Stop(self) -> Any: ...
    def add_Added(self, _p0: Any = ...) -> Any: ...
    def remove_Added(self, _p0: Any = ...) -> Any: ...
    def add_Removed(self, _p0: Any = ...) -> Any: ...
    def remove_Removed(self, _p0: Any = ...) -> Any: ...
    def add_Updated(self, _p0: Any = ...) -> Any: ...
    def remove_Updated(self, _p0: Any = ...) -> Any: ...
    def add_AuthenticationStatusChanged(self, _p0: Any = ...) -> Any: ...
    def remove_AuthenticationStatusChanged(self, _p0: Any = ...) -> Any: ...
    def add_AuthenticationStatusChanging(self, _p0: Any = ...) -> Any: ...
    def remove_AuthenticationStatusChanging(self, _p0: Any = ...) -> Any: ...
    def add_EnumerationCompleted(self, _p0: Any = ...) -> Any: ...
    def remove_EnumerationCompleted(self, _p0: Any = ...) -> Any: ...
    def add_Stopped(self, _p0: Any = ...) -> Any: ...
    def remove_Stopped(self, _p0: Any = ...) -> Any: ...

class KnownUserProperties:
    AccountName: Any
    AgeEnforcementRegion: Any
    DisplayName: Any
    DomainName: Any
    FirstName: Any
    GuestHost: Any
    LastName: Any
    PrincipalName: Any
    ProviderName: Any
    SessionInitiationProtocolUri: Any

class LaunchFileStatus(int):
    Success: int
    AppUnavailable: int
    DeniedByPolicy: int
    FileTypeNotSupported: int
    Unknown: int

class LaunchQuerySupportStatus(int):
    Available: int
    AppNotInstalled: int
    AppUnavailable: int
    NotSupported: int
    Unknown: int

class LaunchQuerySupportType(int):
    Uri: int
    UriForResults: int

class LaunchUriResult:
    Result: Any
    Status: Any

class LaunchUriStatus(int):
    Success: int
    AppUnavailable: int
    ProtocolUnavailable: int
    Unknown: int

class Launcher:
    @classmethod
    def LaunchFolderPathAsync(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def LaunchFolderPathWithOptionsAsync(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def LaunchFolderPathForUserAsync(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def LaunchFolderPathWithOptionsForUserAsync(cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    @classmethod
    def QueryAppUriSupportAsync(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def QueryAppUriSupportWithPackageFamilyNameAsync(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def FindAppUriHandlersAsync(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def LaunchUriForUserAsync(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def LaunchUriWithOptionsForUserAsync(cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    @classmethod
    def LaunchUriWithDataForUserAsync(cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...) -> Any: ...
    @classmethod
    def LaunchUriForResultsForUserAsync(cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    @classmethod
    def LaunchUriForResultsWithDataForUserAsync(cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...) -> Any: ...
    @classmethod
    def LaunchFileAsync(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def LaunchFileWithOptionsAsync(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def LaunchUriAsync(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def LaunchUriWithOptionsAsync(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def LaunchFolderAsync(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def LaunchFolderWithOptionsAsync(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def LaunchUriForResultsAsync(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def LaunchUriForResultsWithDataAsync(cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    @classmethod
    def LaunchUriWithDataAsync(cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    @classmethod
    def QueryUriSupportAsync(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def QueryUriSupportWithPackageFamilyNameAsync(cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    @classmethod
    def QueryFileSupportAsync(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def QueryFileSupportWithPackageFamilyNameAsync(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def FindUriSchemeHandlersAsync(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def FindUriSchemeHandlersWithLaunchUriTypeAsync(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def FindFileHandlersAsync(cls, _p0: Any = ...) -> Any: ...

class LauncherOptions:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    ContentType: Any
    DesiredRemainingView: Any
    DisplayApplicationPicker: Any
    FallbackUri: Any
    IgnoreAppUriHandlers: Any
    LimitPickerToCurrentAppAndAppUriHandlers: Any
    NeighboringFilesQuery: Any
    PreferredApplicationDisplayName: Any
    PreferredApplicationPackageFamilyName: Any
    TargetApplicationPackageFamilyName: Any
    TreatAsUntrusted: Any
    UI: Any

class LauncherUIOptions:
    InvocationPoint: Any
    PreferredPlacement: Any
    SelectionRect: Any

class MemoryManager:
    AppMemoryUsage: Any
    AppMemoryUsageLevel: Any
    AppMemoryUsageLimit: Any
    ExpectedAppMemoryUsageLimit: Any
    @classmethod
    def TrySetAppMemoryUsageLimit(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def GetAppMemoryReport(cls) -> Any: ...
    @classmethod
    def GetProcessMemoryReport(cls) -> Any: ...
    def add_AppMemoryUsageIncreased(self, _p0: Any = ...) -> Any: ...
    def remove_AppMemoryUsageIncreased(self, _p0: Any = ...) -> Any: ...
    def add_AppMemoryUsageDecreased(self, _p0: Any = ...) -> Any: ...
    def remove_AppMemoryUsageDecreased(self, _p0: Any = ...) -> Any: ...
    def add_AppMemoryUsageLimitChanging(self, _p0: Any = ...) -> Any: ...
    def remove_AppMemoryUsageLimitChanging(self, _p0: Any = ...) -> Any: ...

class PowerState(int):
    ConnectedStandby: int
    SleepS3: int

class ProcessLauncher:
    @classmethod
    def RunToCompletionAsync(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def RunToCompletionAsyncWithOptions(cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...

class ProcessLauncherOptions:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    StandardError: Any
    StandardInput: Any
    StandardOutput: Any
    WorkingDirectory: Any

class ProcessLauncherResult:
    ExitCode: Any

class ProcessMemoryReport:
    PrivateWorkingSetUsage: Any
    TotalWorkingSetUsage: Any

class ProcessorArchitecture(int):
    X86: int
    Arm: int
    X64: int
    Neutral: int
    Arm64: int
    X86OnArm64: int
    Unknown: int

class ProtocolForResultsOperation:
    def ReportCompleted(self, _p0: Any = ...) -> Any: ...

class RemoteLaunchUriStatus(int):
    Unknown: int
    Success: int
    AppUnavailable: int
    ProtocolUnavailable: int
    RemoteSystemUnavailable: int
    ValueSetTooLarge: int
    DeniedByLocalSystem: int
    DeniedByRemoteSystem: int

class RemoteLauncher:
    @classmethod
    def LaunchUriAsync(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def LaunchUriWithOptionsAsync(cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    @classmethod
    def LaunchUriWithDataAsync(cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...) -> Any: ...

class RemoteLauncherOptions:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    FallbackUri: Any
    PreferredAppIds: Any

class ShutdownKind(int):
    Shutdown: int
    Restart: int

class ShutdownManager:
    @classmethod
    def IsPowerStateSupported(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def EnterPowerState(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def EnterPowerStateWithTimeSpan(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def BeginShutdown(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def CancelShutdown(cls) -> Any: ...

class TimeZoneSettings:
    CanChangeTimeZone: Any
    CurrentTimeZoneDisplayName: Any
    SupportedTimeZoneDisplayNames: Any
    @classmethod
    def AutoUpdateTimeZoneAsync(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def ChangeTimeZoneByDisplayName(cls, _p0: Any = ...) -> Any: ...

class User:
    AuthenticationStatus: Any
    NonRoamableId: Any
    Type: Any
    def GetPropertyAsync(self, _p0: Any = ...) -> Any: ...
    def GetPropertiesAsync(self, _p0: Any = ...) -> Any: ...
    def GetPictureAsync(self, _p0: Any = ...) -> Any: ...
    def CheckUserAgeConsentGroupAsync(self, _p0: Any = ...) -> Any: ...
    @classmethod
    def GetDefault(cls) -> Any: ...
    @classmethod
    def CreateWatcher(cls) -> Any: ...
    @classmethod
    def FindAllAsync(cls) -> Any: ...
    @classmethod
    def FindAllAsyncByType(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def FindAllAsyncByTypeAndStatus(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def GetFromId(cls, _p0: Any = ...) -> Any: ...

class UserAgeConsentGroup(int):
    Child: int
    Minor: int
    Adult: int

class UserAgeConsentResult(int):
    NotEnforced: int
    Included: int
    NotIncluded: int
    Unknown: int
    Ambiguous: int

class UserAuthenticationStatus(int):
    Unauthenticated: int
    LocallyAuthenticated: int
    RemotelyAuthenticated: int

class UserAuthenticationStatusChangeDeferral:
    def Complete(self) -> Any: ...

class UserAuthenticationStatusChangingEventArgs:
    CurrentStatus: Any
    NewStatus: Any
    User: Any
    def GetDeferral(self) -> Any: ...

class UserChangedEventArgs:
    ChangedPropertyKinds: Any
    User: Any

class UserDeviceAssociation:
    @classmethod
    def FindUserFromDeviceId(cls, _p0: Any = ...) -> Any: ...
    def add_UserDeviceAssociationChanged(self, _p0: Any = ...) -> Any: ...
    def remove_UserDeviceAssociationChanged(self, _p0: Any = ...) -> Any: ...

class UserDeviceAssociationChangedEventArgs:
    DeviceId: Any
    NewUser: Any
    OldUser: Any

class UserPicker:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    AllowGuestAccounts: Any
    SuggestedSelectedUser: Any
    def PickSingleUserAsync(self) -> Any: ...
    @classmethod
    def IsSupported(cls) -> Any: ...

class UserPictureSize(int):
    Size64x64: int
    Size208x208: int
    Size424x424: int
    Size1080x1080: int

class UserType(int):
    LocalUser: int
    RemoteUser: int
    LocalGuest: int
    RemoteGuest: int
    SystemManaged: int

class UserWatcher:
    Status: Any
    Added: Any
    AuthenticationStatusChanged: Any
    AuthenticationStatusChanging: Any
    EnumerationCompleted: Any
    Removed: Any
    Stopped: Any
    Updated: Any
    def Start(self) -> Any: ...
    def Stop(self) -> Any: ...
    def add_Added(self, _p0: Any = ...) -> Any: ...
    def remove_Added(self, _p0: Any = ...) -> Any: ...
    def add_Removed(self, _p0: Any = ...) -> Any: ...
    def remove_Removed(self, _p0: Any = ...) -> Any: ...
    def add_Updated(self, _p0: Any = ...) -> Any: ...
    def remove_Updated(self, _p0: Any = ...) -> Any: ...
    def add_AuthenticationStatusChanged(self, _p0: Any = ...) -> Any: ...
    def remove_AuthenticationStatusChanged(self, _p0: Any = ...) -> Any: ...
    def add_AuthenticationStatusChanging(self, _p0: Any = ...) -> Any: ...
    def remove_AuthenticationStatusChanging(self, _p0: Any = ...) -> Any: ...
    def add_EnumerationCompleted(self, _p0: Any = ...) -> Any: ...
    def remove_EnumerationCompleted(self, _p0: Any = ...) -> Any: ...
    def add_Stopped(self, _p0: Any = ...) -> Any: ...
    def remove_Stopped(self, _p0: Any = ...) -> Any: ...

class UserWatcherStatus(int):
    Created: int
    Started: int
    EnumerationCompleted: int
    Stopping: int
    Stopped: int
    Aborted: int

class UserWatcherUpdateKind(int):
    Properties: int
    Picture: int

class VirtualKey(int):
    None_: int
    LeftButton: int
    RightButton: int
    Cancel: int
    MiddleButton: int
    XButton1: int
    XButton2: int
    Back: int
    Tab: int
    Clear: int
    Enter: int
    Shift: int
    Control: int
    Menu: int
    Pause: int
    CapitalLock: int
    Kana: int
    Hangul: int
    ImeOn: int
    Junja: int
    Final: int
    Hanja: int
    Kanji: int
    ImeOff: int
    Escape: int
    Convert: int
    NonConvert: int
    Accept: int
    ModeChange: int
    Space: int
    PageUp: int
    PageDown: int
    End: int
    Home: int
    Left: int
    Up: int
    Right: int
    Down: int
    Select: int
    Print: int
    Execute: int
    Snapshot: int
    Insert: int
    Delete: int
    Help: int
    Number0: int
    Number1: int
    Number2: int
    Number3: int
    Number4: int
    Number5: int
    Number6: int
    Number7: int
    Number8: int
    Number9: int
    A: int
    B: int
    C: int
    D: int
    E: int
    F: int
    G: int
    H: int
    I: int
    J: int
    K: int
    L: int
    M: int
    N: int
    O: int
    P: int
    Q: int
    R: int
    S: int
    T: int
    U: int
    V: int
    W: int
    X: int
    Y: int
    Z: int
    LeftWindows: int
    RightWindows: int
    Application: int
    Sleep: int
    NumberPad0: int
    NumberPad1: int
    NumberPad2: int
    NumberPad3: int
    NumberPad4: int
    NumberPad5: int
    NumberPad6: int
    NumberPad7: int
    NumberPad8: int
    NumberPad9: int
    Multiply: int
    Add: int
    Separator: int
    Subtract: int
    Decimal: int
    Divide: int
    F1: int
    F2: int
    F3: int
    F4: int
    F5: int
    F6: int
    F7: int
    F8: int
    F9: int
    F10: int
    F11: int
    F12: int
    F13: int
    F14: int
    F15: int
    F16: int
    F17: int
    F18: int
    F19: int
    F20: int
    F21: int
    F22: int
    F23: int
    F24: int
    NavigationView: int
    NavigationMenu: int
    NavigationUp: int
    NavigationDown: int
    NavigationLeft: int
    NavigationRight: int
    NavigationAccept: int
    NavigationCancel: int
    NumberKeyLock: int
    Scroll: int
    LeftShift: int
    RightShift: int
    LeftControl: int
    RightControl: int
    LeftMenu: int
    RightMenu: int
    GoBack: int
    GoForward: int
    Refresh: int
    Stop: int
    Search: int
    Favorites: int
    GoHome: int
    GamepadA: int
    GamepadB: int
    GamepadX: int
    GamepadY: int
    GamepadRightShoulder: int
    GamepadLeftShoulder: int
    GamepadLeftTrigger: int
    GamepadRightTrigger: int
    GamepadDPadUp: int
    GamepadDPadDown: int
    GamepadDPadLeft: int
    GamepadDPadRight: int
    GamepadMenu: int
    GamepadView: int
    GamepadLeftThumbstickButton: int
    GamepadRightThumbstickButton: int
    GamepadLeftThumbstickUp: int
    GamepadLeftThumbstickDown: int
    GamepadLeftThumbstickRight: int
    GamepadLeftThumbstickLeft: int
    GamepadRightThumbstickUp: int
    GamepadRightThumbstickDown: int
    GamepadRightThumbstickRight: int
    GamepadRightThumbstickLeft: int

class VirtualKeyModifiers(int):
    None_: int
    Control: int
    Menu: int
    Shift: int
    Windows: int
