# Auto-generated type stubs for win32more
# Generated by winui3/tools/generate_win32more_stubs.py
# Property types are typed as Any; the goal is attribute existence,
# not full type safety for win32more internals.

from typing import Any

class CharacterReceivedEventArgs:
    Handled: Any
    KeyCode: Any
    KeyStatus: Any

class ContextMenuKeyEventArgs:
    Handled: Any

class CrossSlideThresholds:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SelectionStart: Any
    SpeedBumpStart: Any
    SpeedBumpEnd: Any
    RearrangeStart: Any

class CrossSlidingEventArgs:
    CrossSlidingState: Any
    PointerDeviceType: Any
    Position: Any

class CrossSlidingState(int):
    Started: int
    Dragging: int
    Selecting: int
    SelectSpeedBumping: int
    SpeedBumping: int
    Rearranging: int
    Completed: int

class DraggingEventArgs:
    DraggingState: Any
    PointerDeviceType: Any
    Position: Any

class DraggingState(int):
    Started: int
    Continuing: int
    Completed: int

class EnteredMoveSizeEventArgs:
    MoveSizeOperation: Any
    PointerScreenPoint: Any

class EnteringMoveSizeEventArgs:
    MoveSizeOperation: Any
    MoveSizeWindowId: Any
    PointerScreenPoint: Any

class ExitedMoveSizeEventArgs:
    MoveSizeOperation: Any
    PointerScreenPoint: Any

class FocusChangedEventArgs:
    Handled: Any

class FocusNavigationReason(int):
    Programmatic: int
    Restore: int
    First: int
    Last: int
    Left: int
    Up: int
    Right: int
    Down: int

class FocusNavigationRequest:
    CorrelationId: Any
    HintRect: Any
    Reason: Any
    @classmethod
    def Create(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def CreateWithHintRect(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def CreateWithHintRectAndId(
        cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...
    ) -> Any: ...

class FocusNavigationRequestEventArgs:
    Request: Any
    Result: Any

class FocusNavigationResult(int):
    NotMoved: int
    Moved: int
    NoFocusableElements: int

class GestureRecognizer:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    AutoProcessInertia: Any
    CrossSlideExact: Any
    CrossSlideHorizontally: Any
    CrossSlideThresholds: Any
    GestureSettings: Any
    InertiaExpansion: Any
    InertiaExpansionDeceleration: Any
    InertiaRotationAngle: Any
    InertiaRotationDeceleration: Any
    InertiaTranslationDeceleration: Any
    InertiaTranslationDisplacement: Any
    IsActive: Any
    IsInertial: Any
    ManipulationExact: Any
    MouseWheelParameters: Any
    PivotCenter: Any
    PivotRadius: Any
    ShowGestureFeedback: Any
    CrossSliding: Any
    Dragging: Any
    Holding: Any
    ManipulationCompleted: Any
    ManipulationInertiaStarting: Any
    ManipulationStarted: Any
    ManipulationUpdated: Any
    RightTapped: Any
    Tapped: Any
    def CanBeDoubleTap(self, _p0: Any = ...) -> Any: ...
    def CompleteGesture(self) -> Any: ...
    def ProcessDownEvent(self, _p0: Any = ...) -> Any: ...
    def ProcessMoveEvents(self, _p0: Any = ...) -> Any: ...
    def ProcessMouseWheelEvent(
        self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...
    ) -> Any: ...
    def ProcessInertia(self) -> Any: ...
    def ProcessUpEvent(self, _p0: Any = ...) -> Any: ...
    def add_Tapped(self, _p0: Any = ...) -> Any: ...
    def remove_Tapped(self, _p0: Any = ...) -> Any: ...
    def add_RightTapped(self, _p0: Any = ...) -> Any: ...
    def remove_RightTapped(self, _p0: Any = ...) -> Any: ...
    def add_Holding(self, _p0: Any = ...) -> Any: ...
    def remove_Holding(self, _p0: Any = ...) -> Any: ...
    def add_Dragging(self, _p0: Any = ...) -> Any: ...
    def remove_Dragging(self, _p0: Any = ...) -> Any: ...
    def add_ManipulationStarted(self, _p0: Any = ...) -> Any: ...
    def remove_ManipulationStarted(self, _p0: Any = ...) -> Any: ...
    def add_ManipulationUpdated(self, _p0: Any = ...) -> Any: ...
    def remove_ManipulationUpdated(self, _p0: Any = ...) -> Any: ...
    def add_ManipulationInertiaStarting(self, _p0: Any = ...) -> Any: ...
    def remove_ManipulationInertiaStarting(self, _p0: Any = ...) -> Any: ...
    def add_ManipulationCompleted(self, _p0: Any = ...) -> Any: ...
    def remove_ManipulationCompleted(self, _p0: Any = ...) -> Any: ...
    def add_CrossSliding(self, _p0: Any = ...) -> Any: ...
    def remove_CrossSliding(self, _p0: Any = ...) -> Any: ...

class GestureSettings(int):
    None_: int
    Tap: int
    DoubleTap: int
    Hold: int
    HoldWithMouse: int
    RightTap: int
    Drag: int
    ManipulationTranslateX: int
    ManipulationTranslateY: int
    ManipulationTranslateRailsX: int
    ManipulationTranslateRailsY: int
    ManipulationRotate: int
    ManipulationScale: int
    ManipulationTranslateInertia: int
    ManipulationRotateInertia: int
    ManipulationScaleInertia: int
    CrossSlide: int
    ManipulationMultipleFingerPanning: int

class HoldingEventArgs:
    HoldingState: Any
    PointerDeviceType: Any
    Position: Any

class HoldingState(int):
    Started: int
    Completed: int
    Canceled: int

class ICharacterReceivedEventArgs:
    Handled: Any
    KeyCode: Any
    KeyStatus: Any

class IContextMenuKeyEventArgs:
    Handled: Any

class ICrossSlidingEventArgs:
    CrossSlidingState: Any
    PointerDeviceType: Any
    Position: Any

class IDraggingEventArgs:
    DraggingState: Any
    PointerDeviceType: Any
    Position: Any

class IEnteredMoveSizeEventArgs:
    MoveSizeOperation: Any
    PointerScreenPoint: Any

class IEnteringMoveSizeEventArgs:
    MoveSizeOperation: Any
    MoveSizeWindowId: Any
    PointerScreenPoint: Any

class IExitedMoveSizeEventArgs:
    MoveSizeOperation: Any
    PointerScreenPoint: Any

class IFocusChangedEventArgs:
    Handled: Any

class IFocusNavigationRequest:
    CorrelationId: Any
    HintRect: Any
    Reason: Any

class IFocusNavigationRequestEventArgs:
    Request: Any
    Result: Any

class IGestureRecognizer:
    AutoProcessInertia: Any
    CrossSlideExact: Any
    CrossSlideHorizontally: Any
    CrossSlideThresholds: Any
    GestureSettings: Any
    InertiaExpansion: Any
    InertiaExpansionDeceleration: Any
    InertiaRotationAngle: Any
    InertiaRotationDeceleration: Any
    InertiaTranslationDeceleration: Any
    InertiaTranslationDisplacement: Any
    IsActive: Any
    IsInertial: Any
    ManipulationExact: Any
    MouseWheelParameters: Any
    PivotCenter: Any
    PivotRadius: Any
    ShowGestureFeedback: Any
    CrossSliding: Any
    Dragging: Any
    Holding: Any
    ManipulationCompleted: Any
    ManipulationInertiaStarting: Any
    ManipulationStarted: Any
    ManipulationUpdated: Any
    RightTapped: Any
    Tapped: Any
    def CanBeDoubleTap(self, _p0: Any = ...) -> Any: ...
    def CompleteGesture(self) -> Any: ...
    def ProcessDownEvent(self, _p0: Any = ...) -> Any: ...
    def ProcessMoveEvents(self, _p0: Any = ...) -> Any: ...
    def ProcessMouseWheelEvent(
        self, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...
    ) -> Any: ...
    def ProcessInertia(self) -> Any: ...
    def ProcessUpEvent(self, _p0: Any = ...) -> Any: ...
    def add_Tapped(self, _p0: Any = ...) -> Any: ...
    def remove_Tapped(self, _p0: Any = ...) -> Any: ...
    def add_RightTapped(self, _p0: Any = ...) -> Any: ...
    def remove_RightTapped(self, _p0: Any = ...) -> Any: ...
    def add_Holding(self, _p0: Any = ...) -> Any: ...
    def remove_Holding(self, _p0: Any = ...) -> Any: ...
    def add_Dragging(self, _p0: Any = ...) -> Any: ...
    def remove_Dragging(self, _p0: Any = ...) -> Any: ...
    def add_ManipulationStarted(self, _p0: Any = ...) -> Any: ...
    def remove_ManipulationStarted(self, _p0: Any = ...) -> Any: ...
    def add_ManipulationUpdated(self, _p0: Any = ...) -> Any: ...
    def remove_ManipulationUpdated(self, _p0: Any = ...) -> Any: ...
    def add_ManipulationInertiaStarting(self, _p0: Any = ...) -> Any: ...
    def remove_ManipulationInertiaStarting(self, _p0: Any = ...) -> Any: ...
    def add_ManipulationCompleted(self, _p0: Any = ...) -> Any: ...
    def remove_ManipulationCompleted(self, _p0: Any = ...) -> Any: ...
    def add_CrossSliding(self, _p0: Any = ...) -> Any: ...
    def remove_CrossSliding(self, _p0: Any = ...) -> Any: ...

class IHoldingEventArgs:
    HoldingState: Any
    PointerDeviceType: Any
    Position: Any

class IInputActivationListener:
    State: Any
    InputActivationChanged: Any
    def add_InputActivationChanged(self, _p0: Any = ...) -> Any: ...
    def remove_InputActivationChanged(self, _p0: Any = ...) -> Any: ...

class IInputDesktopNamedResourceCursor:
    ModuleName: Any
    ResourceName: Any

class IInputDesktopResourceCursor:
    ModuleName: Any
    ResourceId: Any

class IInputFocusController:
    HasFocus: Any
    GotFocus: Any
    LostFocus: Any
    def TrySetFocus(self) -> Any: ...
    def add_GotFocus(self, _p0: Any = ...) -> Any: ...
    def remove_GotFocus(self, _p0: Any = ...) -> Any: ...
    def add_LostFocus(self, _p0: Any = ...) -> Any: ...
    def remove_LostFocus(self, _p0: Any = ...) -> Any: ...

class IInputFocusNavigationHost:
    ContainsFocus: Any
    DepartFocusRequested: Any
    def NavigateFocus(self, _p0: Any = ...) -> Any: ...
    def add_DepartFocusRequested(self, _p0: Any = ...) -> Any: ...
    def remove_DepartFocusRequested(self, _p0: Any = ...) -> Any: ...

class IInputNonClientPointerSource:
    DispatcherQueue: Any
    CaptionTapped: Any
    PointerEntered: Any
    PointerExited: Any
    PointerMoved: Any
    PointerPressed: Any
    PointerReleased: Any
    RegionsChanged: Any
    def ClearAllRegionRects(self) -> Any: ...
    def ClearRegionRects(self, _p0: Any = ...) -> Any: ...
    def GetRegionRects(self, _p0: Any = ...) -> Any: ...
    def SetRegionRects(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def add_CaptionTapped(self, _p0: Any = ...) -> Any: ...
    def remove_CaptionTapped(self, _p0: Any = ...) -> Any: ...
    def add_PointerEntered(self, _p0: Any = ...) -> Any: ...
    def remove_PointerEntered(self, _p0: Any = ...) -> Any: ...
    def add_PointerExited(self, _p0: Any = ...) -> Any: ...
    def remove_PointerExited(self, _p0: Any = ...) -> Any: ...
    def add_PointerMoved(self, _p0: Any = ...) -> Any: ...
    def remove_PointerMoved(self, _p0: Any = ...) -> Any: ...
    def add_PointerPressed(self, _p0: Any = ...) -> Any: ...
    def remove_PointerPressed(self, _p0: Any = ...) -> Any: ...
    def add_PointerReleased(self, _p0: Any = ...) -> Any: ...
    def remove_PointerReleased(self, _p0: Any = ...) -> Any: ...
    def add_RegionsChanged(self, _p0: Any = ...) -> Any: ...
    def remove_RegionsChanged(self, _p0: Any = ...) -> Any: ...

class IInputObject:
    DispatcherQueue: Any

class IInputPointerSource:
    Cursor: Any
    DeviceKinds: Any
    PointerCaptureLost: Any
    PointerEntered: Any
    PointerExited: Any
    PointerMoved: Any
    PointerPressed: Any
    PointerReleased: Any
    PointerRoutedAway: Any
    PointerRoutedReleased: Any
    PointerRoutedTo: Any
    PointerWheelChanged: Any
    def add_PointerCaptureLost(self, _p0: Any = ...) -> Any: ...
    def remove_PointerCaptureLost(self, _p0: Any = ...) -> Any: ...
    def add_PointerEntered(self, _p0: Any = ...) -> Any: ...
    def remove_PointerEntered(self, _p0: Any = ...) -> Any: ...
    def add_PointerExited(self, _p0: Any = ...) -> Any: ...
    def remove_PointerExited(self, _p0: Any = ...) -> Any: ...
    def add_PointerMoved(self, _p0: Any = ...) -> Any: ...
    def remove_PointerMoved(self, _p0: Any = ...) -> Any: ...
    def add_PointerPressed(self, _p0: Any = ...) -> Any: ...
    def remove_PointerPressed(self, _p0: Any = ...) -> Any: ...
    def add_PointerReleased(self, _p0: Any = ...) -> Any: ...
    def remove_PointerReleased(self, _p0: Any = ...) -> Any: ...
    def add_PointerRoutedAway(self, _p0: Any = ...) -> Any: ...
    def remove_PointerRoutedAway(self, _p0: Any = ...) -> Any: ...
    def add_PointerRoutedReleased(self, _p0: Any = ...) -> Any: ...
    def remove_PointerRoutedReleased(self, _p0: Any = ...) -> Any: ...
    def add_PointerRoutedTo(self, _p0: Any = ...) -> Any: ...
    def remove_PointerRoutedTo(self, _p0: Any = ...) -> Any: ...
    def add_PointerWheelChanged(self, _p0: Any = ...) -> Any: ...
    def remove_PointerWheelChanged(self, _p0: Any = ...) -> Any: ...

class IInputSystemCursor:
    CursorShape: Any

class IKeyEventArgs:
    Handled: Any
    KeyStatus: Any
    Timestamp: Any
    VirtualKey: Any

class IManipulationCompletedEventArgs:
    Cumulative: Any
    PointerDeviceType: Any
    Position: Any
    Velocities: Any

class IManipulationInertiaStartingEventArgs:
    Cumulative: Any
    Delta: Any
    PointerDeviceType: Any
    Position: Any
    Velocities: Any

class IManipulationStartedEventArgs:
    Cumulative: Any
    PointerDeviceType: Any
    Position: Any

class IManipulationUpdatedEventArgs:
    Cumulative: Any
    Delta: Any
    PointerDeviceType: Any
    Position: Any
    Velocities: Any

class IMouseWheelParameters:
    CharTranslation: Any
    DeltaRotationAngle: Any
    DeltaScale: Any
    PageTranslation: Any

class INonClientCaptionTappedEventArgs:
    Point: Any
    PointerDeviceType: Any

class INonClientPointerEventArgs:
    IsPointInRegion: Any
    Point: Any
    PointerDeviceType: Any
    RegionKind: Any

class INonClientRegionsChangedEventArgs:
    ChangedRegions: Any

class IPointerEventArgs:
    CurrentPoint: Any
    Handled: Any
    KeyModifiers: Any
    def GetIntermediatePoints(self) -> Any: ...
    def GetIntermediateTransformedPoints(self, _p0: Any = ...) -> Any: ...

class IPointerPoint:
    FrameId: Any
    IsInContact: Any
    PointerDeviceType: Any
    PointerId: Any
    Position: Any
    Properties: Any
    Timestamp: Any
    def GetTransformedPoint(self, _p0: Any = ...) -> Any: ...

class IPointerPointProperties:
    ContactRect: Any
    IsBarrelButtonPressed: Any
    IsCanceled: Any
    IsEraser: Any
    IsHorizontalMouseWheel: Any
    IsInRange: Any
    IsInverted: Any
    IsLeftButtonPressed: Any
    IsMiddleButtonPressed: Any
    IsPrimary: Any
    IsRightButtonPressed: Any
    IsXButton1Pressed: Any
    IsXButton2Pressed: Any
    MouseWheelDelta: Any
    Orientation: Any
    PointerUpdateKind: Any
    Pressure: Any
    TouchConfidence: Any
    Twist: Any
    XTilt: Any
    YTilt: Any

class IPointerPointTransform:
    Inverse: Any
    def TryTransform(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def TryTransformBounds(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class IPointerPredictor:
    PredictionTime: Any
    def GetPredictedPoints(self, _p0: Any = ...) -> Any: ...

class IRightTappedEventArgs:
    PointerDeviceType: Any
    Position: Any

class ITappedEventArgs:
    PointerDeviceType: Any
    Position: Any
    TapCount: Any

class IWindowRectChangedEventArgs:
    MoveSizeOperation: Any
    NewWindowRect: Any
    OldWindowRect: Any
    PointerScreenPoint: Any

class IWindowRectChangingEventArgs:
    AllowRectChange: Any
    MoveSizeOperation: Any
    NewWindowRect: Any
    OldWindowRect: Any
    PointerScreenPoint: Any
    ShowWindow: Any

class InputActivationListener(InputObject):
    State: Any
    InputActivationChanged: Any
    def remove_InputActivationChanged(self, _p0: Any = ...) -> Any: ...
    def add_InputActivationChanged(self, _p0: Any = ...) -> Any: ...
    @classmethod
    def GetForIsland(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def GetForWindowId(cls, _p0: Any = ...) -> Any: ...

class InputActivationListenerActivationChangedEventArgs: ...

class InputActivationState(int):
    None_: int
    Deactivated: int
    Activated: int

class InputCursor:
    def Close(self) -> Any: ...
    @classmethod
    def CreateFromCoreCursor(cls, _p0: Any = ...) -> Any: ...

class InputCustomCursor(InputCursor): ...

class InputDesktopNamedResourceCursor(InputCursor):
    ModuleName: Any
    ResourceName: Any
    @classmethod
    def Create(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def CreateFromModule(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class InputDesktopResourceCursor(InputCursor):
    ModuleName: Any
    ResourceId: Any
    @classmethod
    def Create(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def CreateFromModule(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class InputFocusController(InputObject):
    HasFocus: Any
    GotFocus: Any
    LostFocus: Any
    NavigateFocusRequested: Any
    def TrySetFocus(self) -> Any: ...
    def add_GotFocus(self, _p0: Any = ...) -> Any: ...
    def remove_GotFocus(self, _p0: Any = ...) -> Any: ...
    def add_LostFocus(self, _p0: Any = ...) -> Any: ...
    def remove_LostFocus(self, _p0: Any = ...) -> Any: ...
    def DepartFocus(self, _p0: Any = ...) -> Any: ...
    def add_NavigateFocusRequested(self, _p0: Any = ...) -> Any: ...
    def remove_NavigateFocusRequested(self, _p0: Any = ...) -> Any: ...
    @classmethod
    def GetForIsland(cls, _p0: Any = ...) -> Any: ...

class InputFocusNavigationHost(InputObject):
    ContainsFocus: Any
    DepartFocusRequested: Any
    def NavigateFocus(self, _p0: Any = ...) -> Any: ...
    def remove_DepartFocusRequested(self, _p0: Any = ...) -> Any: ...
    def add_DepartFocusRequested(self, _p0: Any = ...) -> Any: ...
    @classmethod
    def GetForSiteLink(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def GetForSiteBridge(cls, _p0: Any = ...) -> Any: ...

class InputKeyboardSource(InputObject):
    CharacterReceived: Any
    ContextMenuKey: Any
    KeyDown: Any
    KeyUp: Any
    SystemKeyDown: Any
    SystemKeyUp: Any
    def remove_KeyDown(self, _p0: Any = ...) -> Any: ...
    def add_CharacterReceived(self, _p0: Any = ...) -> Any: ...
    def remove_CharacterReceived(self, _p0: Any = ...) -> Any: ...
    def add_ContextMenuKey(self, _p0: Any = ...) -> Any: ...
    def remove_ContextMenuKey(self, _p0: Any = ...) -> Any: ...
    def add_KeyDown(self, _p0: Any = ...) -> Any: ...
    def GetKeyState(self, _p0: Any = ...) -> Any: ...
    def add_KeyUp(self, _p0: Any = ...) -> Any: ...
    def remove_KeyUp(self, _p0: Any = ...) -> Any: ...
    def add_SystemKeyDown(self, _p0: Any = ...) -> Any: ...
    def remove_SystemKeyDown(self, _p0: Any = ...) -> Any: ...
    def GetCurrentKeyState(self, _p0: Any = ...) -> Any: ...
    def remove_SystemKeyUp(self, _p0: Any = ...) -> Any: ...
    def add_SystemKeyUp(self, _p0: Any = ...) -> Any: ...
    @classmethod
    def GetForIsland(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def GetKeyStateForCurrentThread(cls, _p0: Any = ...) -> Any: ...

class InputLightDismissAction(InputObject):
    Dismissed: Any
    def remove_Dismissed(self, _p0: Any = ...) -> Any: ...
    def add_Dismissed(self, _p0: Any = ...) -> Any: ...
    @classmethod
    def GetForWindowId(cls, _p0: Any = ...) -> Any: ...

class InputLightDismissEventArgs: ...

class InputNonClientPointerSource:
    DispatcherQueue: Any
    CaptionTapped: Any
    EnteredMoveSize: Any
    EnteringMoveSize: Any
    ExitedMoveSize: Any
    PointerEntered: Any
    PointerExited: Any
    PointerMoved: Any
    PointerPressed: Any
    PointerReleased: Any
    RegionsChanged: Any
    WindowRectChanged: Any
    WindowRectChanging: Any
    def remove_PointerPressed(self, _p0: Any = ...) -> Any: ...
    def ClearRegionRects(self, _p0: Any = ...) -> Any: ...
    def GetRegionRects(self, _p0: Any = ...) -> Any: ...
    def SetRegionRects(self, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def add_CaptionTapped(self, _p0: Any = ...) -> Any: ...
    def remove_CaptionTapped(self, _p0: Any = ...) -> Any: ...
    def add_PointerEntered(self, _p0: Any = ...) -> Any: ...
    def remove_PointerEntered(self, _p0: Any = ...) -> Any: ...
    def add_PointerExited(self, _p0: Any = ...) -> Any: ...
    def remove_PointerExited(self, _p0: Any = ...) -> Any: ...
    def add_PointerMoved(self, _p0: Any = ...) -> Any: ...
    def remove_PointerMoved(self, _p0: Any = ...) -> Any: ...
    def add_PointerPressed(self, _p0: Any = ...) -> Any: ...
    def remove_PointerReleased(self, _p0: Any = ...) -> Any: ...
    def add_PointerReleased(self, _p0: Any = ...) -> Any: ...
    def add_RegionsChanged(self, _p0: Any = ...) -> Any: ...
    def remove_RegionsChanged(self, _p0: Any = ...) -> Any: ...
    def add_EnteringMoveSize(self, _p0: Any = ...) -> Any: ...
    def remove_EnteringMoveSize(self, _p0: Any = ...) -> Any: ...
    def add_EnteredMoveSize(self, _p0: Any = ...) -> Any: ...
    def remove_EnteredMoveSize(self, _p0: Any = ...) -> Any: ...
    def add_WindowRectChanging(self, _p0: Any = ...) -> Any: ...
    def remove_WindowRectChanging(self, _p0: Any = ...) -> Any: ...
    def add_WindowRectChanged(self, _p0: Any = ...) -> Any: ...
    def remove_WindowRectChanged(self, _p0: Any = ...) -> Any: ...
    def add_ExitedMoveSize(self, _p0: Any = ...) -> Any: ...
    def remove_ExitedMoveSize(self, _p0: Any = ...) -> Any: ...
    def ClearAllRegionRects(self) -> Any: ...
    @classmethod
    def GetForWindowId(cls, _p0: Any = ...) -> Any: ...

class InputObject:
    DispatcherQueue: Any

class InputPointerSource(InputObject):
    Cursor: Any
    DeviceKinds: Any
    PointerCaptureLost: Any
    PointerEntered: Any
    PointerExited: Any
    PointerMoved: Any
    PointerPressed: Any
    PointerReleased: Any
    PointerRoutedAway: Any
    PointerRoutedReleased: Any
    PointerRoutedTo: Any
    PointerWheelChanged: Any
    def remove_PointerCaptureLost(self, _p0: Any = ...) -> Any: ...
    def add_PointerCaptureLost(self, _p0: Any = ...) -> Any: ...
    def add_PointerEntered(self, _p0: Any = ...) -> Any: ...
    def remove_PointerEntered(self, _p0: Any = ...) -> Any: ...
    def add_PointerExited(self, _p0: Any = ...) -> Any: ...
    def remove_PointerExited(self, _p0: Any = ...) -> Any: ...
    def add_PointerMoved(self, _p0: Any = ...) -> Any: ...
    def remove_PointerMoved(self, _p0: Any = ...) -> Any: ...
    def add_PointerPressed(self, _p0: Any = ...) -> Any: ...
    def remove_PointerPressed(self, _p0: Any = ...) -> Any: ...
    def add_PointerReleased(self, _p0: Any = ...) -> Any: ...
    def remove_PointerReleased(self, _p0: Any = ...) -> Any: ...
    def add_PointerRoutedAway(self, _p0: Any = ...) -> Any: ...
    def remove_PointerRoutedAway(self, _p0: Any = ...) -> Any: ...
    def add_PointerRoutedReleased(self, _p0: Any = ...) -> Any: ...
    def remove_PointerRoutedReleased(self, _p0: Any = ...) -> Any: ...
    def add_PointerRoutedTo(self, _p0: Any = ...) -> Any: ...
    def remove_PointerRoutedTo(self, _p0: Any = ...) -> Any: ...
    def add_PointerWheelChanged(self, _p0: Any = ...) -> Any: ...
    def remove_PointerWheelChanged(self, _p0: Any = ...) -> Any: ...
    @classmethod
    def GetForIsland(cls, _p0: Any = ...) -> Any: ...

class InputPointerSourceDeviceKinds(int):
    None_: int
    Touch: int
    Pen: int
    Mouse: int

class InputPreTranslateKeyboardSource(InputObject):
    @classmethod
    def GetForIsland(cls, _p0: Any = ...) -> Any: ...

class InputSystemCursor(InputCursor):
    CursorShape: Any
    @classmethod
    def Create(cls, _p0: Any = ...) -> Any: ...

class InputSystemCursorShape(int):
    Arrow: int
    Cross: int
    Hand: int
    Help: int
    IBeam: int
    SizeAll: int
    SizeNortheastSouthwest: int
    SizeNorthSouth: int
    SizeNorthwestSoutheast: int
    SizeWestEast: int
    UniversalNo: int
    UpArrow: int
    Wait: int
    Pin: int
    Person: int
    AppStarting: int

class KeyEventArgs:
    Handled: Any
    KeyStatus: Any
    Timestamp: Any
    VirtualKey: Any

class ManipulationCompletedEventArgs:
    Cumulative: Any
    PointerDeviceType: Any
    Position: Any
    Velocities: Any

class ManipulationDelta:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Translation: Any
    Scale: Any
    Rotation: Any
    Expansion: Any

class ManipulationInertiaStartingEventArgs:
    Cumulative: Any
    Delta: Any
    PointerDeviceType: Any
    Position: Any
    Velocities: Any

class ManipulationStartedEventArgs:
    Cumulative: Any
    PointerDeviceType: Any
    Position: Any

class ManipulationUpdatedEventArgs:
    Cumulative: Any
    Delta: Any
    PointerDeviceType: Any
    Position: Any
    Velocities: Any

class ManipulationVelocities:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Linear: Any
    Angular: Any
    Expansion: Any

class MouseWheelParameters:
    CharTranslation: Any
    DeltaRotationAngle: Any
    DeltaScale: Any
    PageTranslation: Any

class MoveSizeOperation(int):
    Move: int
    SizeBottom: int
    SizeBottomLeft: int
    SizeBottomRight: int
    SizeLeft: int
    SizeRight: int
    SizeTop: int
    SizeTopLeft: int
    SizeTopRight: int

class NonClientCaptionTappedEventArgs:
    Point: Any
    PointerDeviceType: Any

class NonClientPointerEventArgs:
    IsPointInRegion: Any
    Point: Any
    PointerDeviceType: Any
    RegionKind: Any

class NonClientRegionKind(int):
    Close: int
    Maximize: int
    Minimize: int
    Icon: int
    Caption: int
    TopBorder: int
    LeftBorder: int
    BottomBorder: int
    RightBorder: int
    Passthrough: int

class NonClientRegionsChangedEventArgs:
    ChangedRegions: Any

class PhysicalKeyStatus:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    RepeatCount: Any
    ScanCode: Any
    IsExtendedKey: Any
    IsMenuKeyDown: Any
    WasKeyDown: Any
    IsKeyReleased: Any

class PointerDeviceType(int):
    Touch: int
    Pen: int
    Mouse: int
    Touchpad: int

class PointerEventArgs:
    CurrentPoint: Any
    Handled: Any
    KeyModifiers: Any
    def GetIntermediatePoints(self) -> Any: ...
    def GetIntermediateTransformedPoints(self, _p0: Any = ...) -> Any: ...

class PointerPoint:
    FrameId: Any
    IsInContact: Any
    PointerDeviceType: Any
    PointerId: Any
    Position: Any
    Properties: Any
    Timestamp: Any
    def GetTransformedPoint(self, _p0: Any = ...) -> Any: ...

class PointerPointProperties:
    ContactRect: Any
    IsBarrelButtonPressed: Any
    IsCanceled: Any
    IsEraser: Any
    IsHorizontalMouseWheel: Any
    IsInRange: Any
    IsInverted: Any
    IsLeftButtonPressed: Any
    IsMiddleButtonPressed: Any
    IsPrimary: Any
    IsRightButtonPressed: Any
    IsXButton1Pressed: Any
    IsXButton2Pressed: Any
    MouseWheelDelta: Any
    Orientation: Any
    PointerUpdateKind: Any
    Pressure: Any
    TouchConfidence: Any
    Twist: Any
    XTilt: Any
    YTilt: Any

class PointerPredictor:
    PredictionTime: Any
    def GetPredictedPoints(self, _p0: Any = ...) -> Any: ...
    def Close(self) -> Any: ...
    @classmethod
    def CreateForInputPointerSource(cls, _p0: Any = ...) -> Any: ...

class PointerUpdateKind(int):
    Other: int
    LeftButtonPressed: int
    LeftButtonReleased: int
    RightButtonPressed: int
    RightButtonReleased: int
    MiddleButtonPressed: int
    MiddleButtonReleased: int
    XButton1Pressed: int
    XButton1Released: int
    XButton2Pressed: int
    XButton2Released: int

class RightTappedEventArgs:
    PointerDeviceType: Any
    Position: Any

class TappedEventArgs:
    PointerDeviceType: Any
    Position: Any
    TapCount: Any

class VirtualKeyStates(int):
    None_: int
    Down: int
    Locked: int

class WindowRectChangedEventArgs:
    MoveSizeOperation: Any
    NewWindowRect: Any
    OldWindowRect: Any
    PointerScreenPoint: Any

class WindowRectChangingEventArgs:
    AllowRectChange: Any
    MoveSizeOperation: Any
    NewWindowRect: Any
    OldWindowRect: Any
    PointerScreenPoint: Any
    ShowWindow: Any
