# Auto-generated type stubs for win32more
# Generated by winui3/tools/generate_win32more_stubs.py
# Property types are typed as Any; the goal is attribute existence,
# not full type safety for win32more internals.

from typing import Any

class CanvasGradientStop:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Position: Any
    Color: Any

class CanvasGradientStopHdr:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Position: Any
    Color: Any

class CanvasImageBrush:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Device: Any
    ExtendX: Any
    ExtendY: Any
    Image: Any
    Interpolation: Any
    Opacity: Any
    SourceRectangle: Any
    Transform: Any
    @classmethod
    def Create(cls, _p0: Any = ...) -> Any: ...
    @classmethod
    def CreateWithImage(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def Close(self) -> Any: ...

class CanvasLinearGradientBrush:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    AlphaMode: Any
    BufferPrecision: Any
    Device: Any
    EdgeBehavior: Any
    EndPoint: Any
    Opacity: Any
    PostInterpolationSpace: Any
    PreInterpolationSpace: Any
    StartPoint: Any
    Stops: Any
    StopsHdr: Any
    Transform: Any
    @classmethod
    def CreateWithStops(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def CreateSimple(cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    @classmethod
    def CreateWithEdgeBehaviorAndAlphaMode(cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...) -> Any: ...
    @classmethod
    def CreateWithEdgeBehaviorAndInterpolationOptions(cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ..., _p4: Any = ..., _p5: Any = ..., _p6: Any = ...) -> Any: ...
    def Close(self) -> Any: ...
    @classmethod
    def CreateHdrSimple(cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    @classmethod
    def CreateHdrWithStops(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def CreateHdrWithEdgeBehaviorAndAlphaMode(cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...) -> Any: ...
    @classmethod
    def CreateHdrWithEdgeBehaviorAndInterpolationOptions(cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ..., _p4: Any = ..., _p5: Any = ..., _p6: Any = ...) -> Any: ...
    @classmethod
    def CreateRainbow(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class CanvasRadialGradientBrush:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    AlphaMode: Any
    BufferPrecision: Any
    Center: Any
    Device: Any
    EdgeBehavior: Any
    Opacity: Any
    OriginOffset: Any
    PostInterpolationSpace: Any
    PreInterpolationSpace: Any
    RadiusX: Any
    RadiusY: Any
    Stops: Any
    StopsHdr: Any
    Transform: Any
    @classmethod
    def CreateWithStops(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def CreateSimple(cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    @classmethod
    def CreateWithEdgeBehaviorAndAlphaMode(cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...) -> Any: ...
    @classmethod
    def CreateWithEdgeBehaviorAndInterpolationOptions(cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ..., _p4: Any = ..., _p5: Any = ..., _p6: Any = ...) -> Any: ...
    def Close(self) -> Any: ...
    @classmethod
    def CreateHdrSimple(cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ...) -> Any: ...
    @classmethod
    def CreateHdrWithStops(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    @classmethod
    def CreateHdrWithEdgeBehaviorAndAlphaMode(cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ...) -> Any: ...
    @classmethod
    def CreateHdrWithEdgeBehaviorAndInterpolationOptions(cls, _p0: Any = ..., _p1: Any = ..., _p2: Any = ..., _p3: Any = ..., _p4: Any = ..., _p5: Any = ..., _p6: Any = ...) -> Any: ...
    @classmethod
    def CreateRainbow(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class CanvasSolidColorBrush:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Color: Any
    ColorHdr: Any
    Device: Any
    Opacity: Any
    Transform: Any
    @classmethod
    def Create(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...
    def Close(self) -> Any: ...
    @classmethod
    def CreateHdr(cls, _p0: Any = ..., _p1: Any = ...) -> Any: ...

class ICanvasBrush:
    Device: Any
    Opacity: Any
    Transform: Any

class ICanvasImageBrush:
    ExtendX: Any
    ExtendY: Any
    Image: Any
    Interpolation: Any
    SourceRectangle: Any

class ICanvasLinearGradientBrush:
    AlphaMode: Any
    BufferPrecision: Any
    EdgeBehavior: Any
    EndPoint: Any
    PostInterpolationSpace: Any
    PreInterpolationSpace: Any
    StartPoint: Any
    Stops: Any
    StopsHdr: Any

class ICanvasRadialGradientBrush:
    AlphaMode: Any
    BufferPrecision: Any
    Center: Any
    EdgeBehavior: Any
    OriginOffset: Any
    PostInterpolationSpace: Any
    PreInterpolationSpace: Any
    RadiusX: Any
    RadiusY: Any
    Stops: Any
    StopsHdr: Any

class ICanvasSolidColorBrush:
    Color: Any
    ColorHdr: Any
