# Auto-generated type stubs for win32more
# Generated by winui3/tools/generate_win32more_stubs.py
# Property types are typed as Any; the goal is attribute existence,
# not full type safety for win32more internals.

from typing import Any

class ACCEL:
    fVirt: Any
    key: Any
    cmd: Any

class ALTTABINFO:
    cbSize: Any
    cItems: Any
    cColumns: Any
    cRows: Any
    iColFocus: Any
    iRowFocus: Any
    cxItem: Any
    cyItem: Any
    ptStart: Any

class ANIMATIONINFO:
    cbSize: Any
    iMinAnimate: Any

class AUDIODESCRIPTION:
    cbSize: Any
    Enabled: Any
    Locale: Any

class CBTACTIVATESTRUCT:
    fMouse: Any
    hWndActive: Any

class CBT_CREATEWNDA:
    lpcs: Any
    hwndInsertAfter: Any

class CBT_CREATEWNDW:
    lpcs: Any
    hwndInsertAfter: Any

class CHANGEFILTERSTRUCT:
    cbSize: Any
    ExtStatus: Any

class CLIENTCREATESTRUCT:
    hWindowMenu: Any
    idFirstChild: Any

class CREATESTRUCTA:
    lpCreateParams: Any
    hInstance: Any
    hMenu: Any
    hwndParent: Any
    cy: Any
    cx: Any
    y: Any
    x: Any
    style: Any
    lpszName: Any
    lpszClass: Any
    dwExStyle: Any

class CREATESTRUCTW:
    lpCreateParams: Any
    hInstance: Any
    hMenu: Any
    hwndParent: Any
    cy: Any
    cx: Any
    y: Any
    x: Any
    style: Any
    lpszName: Any
    lpszClass: Any
    dwExStyle: Any

class CURSORINFO:
    cbSize: Any
    flags: Any
    hCursor: Any
    ptScreenPos: Any

class CURSORSHAPE:
    xHotSpot: Any
    yHotSpot: Any
    cx: Any
    cy: Any
    cbWidth: Any
    Planes: Any
    BitsPixel: Any

class CWPRETSTRUCT:
    lResult: Any
    lParam: Any
    wParam: Any
    message: Any
    hwnd: Any

class CWPSTRUCT:
    lParam: Any
    wParam: Any
    message: Any
    hwnd: Any

class DEBUGHOOKINFO:
    idThread: Any
    idThreadInstaller: Any
    lParam: Any
    wParam: Any
    code: Any

class DEVICE_EVENT_BECOMING_READY:
    Version: Any
    Reason: Any
    Estimated100msToReady: Any

class DEVICE_EVENT_EXTERNAL_REQUEST:
    Version: Any
    DeviceClass: Any
    ButtonStatus: Any
    Request: Any
    SystemTime: Any

class DEVICE_EVENT_GENERIC_DATA:
    EventNumber: Any

class DEVICE_EVENT_MOUNT:
    Version: Any
    Flags: Any
    FileSystemNameLength: Any
    FileSystemNameOffset: Any

class DEVICE_EVENT_RBC_DATA:
    EventNumber: Any
    SenseQualifier: Any
    SenseCode: Any
    SenseKey: Any
    Reserved: Any
    Information: Any

class DEV_BROADCAST_DEVICEINTERFACE_A:
    dbcc_size: Any
    dbcc_devicetype: Any
    dbcc_reserved: Any
    dbcc_classguid: Any
    dbcc_name: Any

class DEV_BROADCAST_DEVICEINTERFACE_W:
    dbcc_size: Any
    dbcc_devicetype: Any
    dbcc_reserved: Any
    dbcc_classguid: Any
    dbcc_name: Any

class DEV_BROADCAST_DEVNODE:
    dbcd_size: Any
    dbcd_devicetype: Any
    dbcd_reserved: Any
    dbcd_devnode: Any

class DEV_BROADCAST_HANDLE:
    dbch_size: Any
    dbch_devicetype: Any
    dbch_reserved: Any
    dbch_handle: Any
    dbch_hdevnotify: Any
    dbch_eventguid: Any
    dbch_nameoffset: Any
    dbch_data: Any

class DEV_BROADCAST_HANDLE32:
    dbch_size: Any
    dbch_devicetype: Any
    dbch_reserved: Any
    dbch_handle: Any
    dbch_hdevnotify: Any
    dbch_eventguid: Any
    dbch_nameoffset: Any
    dbch_data: Any

class DEV_BROADCAST_HANDLE64:
    dbch_size: Any
    dbch_devicetype: Any
    dbch_reserved: Any
    dbch_handle: Any
    dbch_hdevnotify: Any
    dbch_eventguid: Any
    dbch_nameoffset: Any
    dbch_data: Any

class DEV_BROADCAST_HDR:
    dbch_size: Any
    dbch_devicetype: Any
    dbch_reserved: Any

class DEV_BROADCAST_NET:
    dbcn_size: Any
    dbcn_devicetype: Any
    dbcn_reserved: Any
    dbcn_resource: Any
    dbcn_flags: Any

class DEV_BROADCAST_OEM:
    dbco_size: Any
    dbco_devicetype: Any
    dbco_reserved: Any
    dbco_identifier: Any
    dbco_suppfunc: Any

class DEV_BROADCAST_PORT_A:
    dbcp_size: Any
    dbcp_devicetype: Any
    dbcp_reserved: Any
    dbcp_name: Any

class DEV_BROADCAST_PORT_W:
    dbcp_size: Any
    dbcp_devicetype: Any
    dbcp_reserved: Any
    dbcp_name: Any

class DEV_BROADCAST_VOLUME:
    dbcv_size: Any
    dbcv_devicetype: Any
    dbcv_reserved: Any
    dbcv_unitmask: Any
    dbcv_flags: Any

class DISK_HEALTH_NOTIFICATION_DATA:
    DeviceGuid: Any

class DLGITEMTEMPLATE:
    style: Any
    dwExtendedStyle: Any
    x: Any
    y: Any
    cx: Any
    cy: Any
    id: Any

class DLGTEMPLATE:
    style: Any
    dwExtendedStyle: Any
    cdit: Any
    x: Any
    y: Any
    cx: Any
    cy: Any

class DROPSTRUCT:
    hwndSource: Any
    hwndSink: Any
    wFmt: Any
    dwData: Any
    ptDrop: Any
    dwControlData: Any

class EVENTMSG:
    message: Any
    paramL: Any
    paramH: Any
    time: Any
    hwnd: Any

class FLASHWINFO:
    cbSize: Any
    hwnd: Any
    dwFlags: Any
    uCount: Any
    dwTimeout: Any

class FRAME_MARGIN:
    left: Any
    right: Any
    top: Any
    bottom: Any

class GETCLIPBMETADATA:
    Version: Any
    IsDelayRendered: Any
    IsSynthetic: Any

class GUID_IO_DISK_CLONE_ARRIVAL_INFORMATION:
    DiskNumber: Any

class GUITHREADINFO:
    cbSize: Any
    flags: Any
    hwndActive: Any
    hwndFocus: Any
    hwndCapture: Any
    hwndMenuOwner: Any
    hwndMoveSize: Any
    hwndCaret: Any
    rcCaret: Any

class HARDWAREHOOKSTRUCT:
    hwnd: Any
    message: Any
    wParam: Any
    lParam: Any

class IndexedResourceQualifier:
    name: Any
    value: Any

class KBDLLHOOKSTRUCT:
    vkCode: Any
    scanCode: Any
    flags: Any
    time: Any
    dwExtraInfo: Any

class MDICREATESTRUCTA:
    szClass: Any
    szTitle: Any
    hOwner: Any
    x: Any
    y: Any
    cx: Any
    cy: Any
    style: Any
    lParam: Any

class MDICREATESTRUCTW:
    szClass: Any
    szTitle: Any
    hOwner: Any
    x: Any
    y: Any
    cx: Any
    cy: Any
    style: Any
    lParam: Any

class MDINEXTMENU:
    hmenuIn: Any
    hmenuNext: Any
    hwndNext: Any

class MENUBARINFO:
    cbSize: Any
    rcBar: Any
    hMenu: Any
    hwndMenu: Any
    fBarFocused: Any
    fFocused: Any
    fUnused: Any

class MENUEX_TEMPLATE_HEADER:
    wVersion: Any
    wOffset: Any
    dwHelpId: Any

class MENUEX_TEMPLATE_ITEM:
    dwType: Any
    dwState: Any
    uId: Any
    wFlags: Any
    szText: Any

class MENUGETOBJECTINFO:
    dwFlags: Any
    uPos: Any
    hmenu: Any
    riid: Any
    pvObj: Any

class MENUINFO:
    cbSize: Any
    fMask: Any
    dwStyle: Any
    cyMax: Any
    hbrBack: Any
    dwContextHelpID: Any
    dwMenuData: Any

class MENUITEMINFOA:
    cbSize: Any
    fMask: Any
    fType: Any
    fState: Any
    wID: Any
    hSubMenu: Any
    hbmpChecked: Any
    hbmpUnchecked: Any
    dwItemData: Any
    dwTypeData: Any
    cch: Any
    hbmpItem: Any

class MENUITEMINFOW:
    cbSize: Any
    fMask: Any
    fType: Any
    fState: Any
    wID: Any
    hSubMenu: Any
    hbmpChecked: Any
    hbmpUnchecked: Any
    dwItemData: Any
    dwTypeData: Any
    cch: Any
    hbmpItem: Any

class MENUITEMTEMPLATE:
    mtOption: Any
    mtID: Any
    mtString: Any

class MENUITEMTEMPLATEHEADER:
    versionNumber: Any
    offset: Any

class MENUTEMPLATEEX:
    Anonymous: Any

class MESSAGE_RESOURCE_BLOCK:
    LowId: Any
    HighId: Any
    OffsetToEntries: Any

class MESSAGE_RESOURCE_DATA:
    NumberOfBlocks: Any
    Blocks: Any

class MESSAGE_RESOURCE_ENTRY:
    Length: Any
    Flags: Any
    Text: Any

class MINIMIZEDMETRICS:
    cbSize: Any
    iWidth: Any
    iHorzGap: Any
    iVertGap: Any
    iArrange: Any

class MINMAXINFO:
    ptReserved: Any
    ptMaxSize: Any
    ptMaxPosition: Any
    ptMinTrackSize: Any
    ptMaxTrackSize: Any

class MOUSEHOOKSTRUCT:
    pt: Any
    hwnd: Any
    wHitTestCode: Any
    dwExtraInfo: Any

class MOUSEHOOKSTRUCTEX:
    Base: Any
    mouseData: Any

class MSG:
    hwnd: Any
    message: Any
    wParam: Any
    lParam: Any
    time: Any
    pt: Any

class MSGBOXPARAMSA:
    cbSize: Any
    hwndOwner: Any
    hInstance: Any
    lpszText: Any
    lpszCaption: Any
    dwStyle: Any
    lpszIcon: Any
    dwContextHelpId: Any
    lpfnMsgBoxCallback: Any
    dwLanguageId: Any

class MSGBOXPARAMSW:
    cbSize: Any
    hwndOwner: Any
    hInstance: Any
    lpszText: Any
    lpszCaption: Any
    dwStyle: Any
    lpszIcon: Any
    dwContextHelpId: Any
    lpfnMsgBoxCallback: Any
    dwLanguageId: Any

class MSLLHOOKSTRUCT:
    pt: Any
    mouseData: Any
    flags: Any
    time: Any
    dwExtraInfo: Any

class MrmResourceIndexerHandle:
    handle: Any

class MrmResourceIndexerMessage:
    severity: Any
    id: Any
    text: Any

class NCCALCSIZE_PARAMS:
    rgrc: Any
    lppos: Any

class NONCLIENTMETRICSA:
    cbSize: Any
    iBorderWidth: Any
    iScrollWidth: Any
    iScrollHeight: Any
    iCaptionWidth: Any
    iCaptionHeight: Any
    lfCaptionFont: Any
    iSmCaptionWidth: Any
    iSmCaptionHeight: Any
    lfSmCaptionFont: Any
    iMenuWidth: Any
    iMenuHeight: Any
    lfMenuFont: Any
    lfStatusFont: Any
    lfMessageFont: Any
    iPaddedBorderWidth: Any

class NONCLIENTMETRICSW:
    cbSize: Any
    iBorderWidth: Any
    iScrollWidth: Any
    iScrollHeight: Any
    iCaptionWidth: Any
    iCaptionHeight: Any
    lfCaptionFont: Any
    iSmCaptionWidth: Any
    iSmCaptionHeight: Any
    lfSmCaptionFont: Any
    iMenuWidth: Any
    iMenuHeight: Any
    lfMenuFont: Any
    lfStatusFont: Any
    lfMessageFont: Any
    iPaddedBorderWidth: Any

class SCROLLBARINFO:
    cbSize: Any
    rcScrollBar: Any
    dxyLineButton: Any
    xyThumbTop: Any
    xyThumbBottom: Any
    reserved: Any
    rgstate: Any

class SCROLLINFO:
    cbSize: Any
    fMask: Any
    nMin: Any
    nMax: Any
    nPage: Any
    nPos: Any
    nTrackPos: Any

class SHELLHOOKINFO:
    hwnd: Any
    rc: Any

class STYLESTRUCT:
    styleOld: Any
    styleNew: Any

class TITLEBARINFO:
    cbSize: Any
    rcTitleBar: Any
    rgstate: Any

class TITLEBARINFOEX:
    cbSize: Any
    rcTitleBar: Any
    rgstate: Any
    rgrect: Any

class TOUCHPAD_PARAMETERS_V1:
    versionNumber: Any
    maxSupportedContacts: Any
    legacyTouchpadFeatures: Any
    touchpadPresent: Any
    legacyTouchpadPresent: Any
    externalMousePresent: Any
    touchpadEnabled: Any
    touchpadActive: Any
    feedbackSupported: Any
    clickForceSupported: Any
    Reserved1: Any
    allowActiveWhenMousePresent: Any
    feedbackEnabled: Any
    tapEnabled: Any
    tapAndDragEnabled: Any
    twoFingerTapEnabled: Any
    rightClickZoneEnabled: Any
    mouseAccelSettingHonored: Any
    panEnabled: Any
    zoomEnabled: Any
    scrollDirectionReversed: Any
    Reserved2: Any
    sensitivityLevel: Any
    cursorSpeed: Any
    feedbackIntensity: Any
    clickForceSensitivity: Any
    rightClickZoneWidth: Any
    rightClickZoneHeight: Any

class TOUCHPAD_PARAMETERS_V2:
    Base: Any
    button1Supported: Any
    button2Supported: Any
    button3Supported: Any
    Reserved3: Any

class TOUCHPREDICTIONPARAMETERS:
    cbSize: Any
    dwLatency: Any
    dwSampleTime: Any
    bUseHWTimeStamp: Any

class TPMPARAMS:
    cbSize: Any
    rcExclude: Any

class UPDATELAYEREDWINDOWINFO:
    cbSize: Any
    hdcDst: Any
    pptDst: Any
    psize: Any
    hdcSrc: Any
    pptSrc: Any
    crKey: Any
    pblend: Any
    dwFlags: Any
    prcDirty: Any

class VolLockBroadcast:
    vlb_dbh: Any
    vlb_owner: Any
    vlb_perms: Any
    vlb_lockType: Any
    vlb_drive: Any
    vlb_flags: Any

class WINDOWINFO:
    cbSize: Any
    rcWindow: Any
    rcClient: Any
    dwStyle: Any
    dwExStyle: Any
    dwWindowStatus: Any
    cxWindowBorders: Any
    cyWindowBorders: Any
    atomWindowType: Any
    wCreatorVersion: Any

class WINDOWPLACEMENT:
    length: Any
    flags: Any
    showCmd: Any
    ptMinPosition: Any
    ptMaxPosition: Any
    rcNormalPosition: Any

class WINDOWPOS:
    hwnd: Any
    hwndInsertAfter: Any
    x: Any
    y: Any
    cx: Any
    cy: Any
    flags: Any

class WINDOW_ACTION:
    kinds: Any
    modifiers: Any
    visible: Any
    position: Any
    size: Any
    insertAfter: Any
    placementState: Any
    normalRect: Any
    workArea: Any
    dpi: Any
    pointOnMonitor: Any
    monitorTopologyId: Any

class WNDCLASSA:
    style: Any
    lpfnWndProc: Any
    cbClsExtra: Any
    cbWndExtra: Any
    hInstance: Any
    hIcon: Any
    hCursor: Any
    hbrBackground: Any
    lpszMenuName: Any
    lpszClassName: Any

class WNDCLASSEXA:
    cbSize: Any
    style: Any
    lpfnWndProc: Any
    cbClsExtra: Any
    cbWndExtra: Any
    hInstance: Any
    hIcon: Any
    hCursor: Any
    hbrBackground: Any
    lpszMenuName: Any
    lpszClassName: Any
    hIconSm: Any

class WNDCLASSEXW:
    cbSize: Any
    style: Any
    lpfnWndProc: Any
    cbClsExtra: Any
    cbWndExtra: Any
    hInstance: Any
    hIcon: Any
    hCursor: Any
    hbrBackground: Any
    lpszMenuName: Any
    lpszClassName: Any
    hIconSm: Any

class WNDCLASSW:
    style: Any
    lpfnWndProc: Any
    cbClsExtra: Any
    cbWndExtra: Any
    hInstance: Any
    hIcon: Any
    hCursor: Any
    hbrBackground: Any
    lpszMenuName: Any
    lpszClassName: Any

class _DEV_BROADCAST_HEADER:
    dbcd_size: Any
    dbcd_devicetype: Any
    dbcd_reserved: Any

class _DEV_BROADCAST_USERDEFINED:
    dbud_dbh: Any
    dbud_szName: Any
