# Auto-generated type stubs for win32more
# Generated by winui3/tools/generate_win32more_stubs.py
# Property types are typed as Any; the goal is attribute existence,
# not full type safety for win32more internals.

from typing import Any

class Matrix3x2:
    M11: Any
    M12: Any
    M21: Any
    M22: Any
    M31: Any
    M32: Any

class Matrix4x4:
    M11: Any
    M12: Any
    M13: Any
    M14: Any
    M21: Any
    M22: Any
    M23: Any
    M24: Any
    M31: Any
    M32: Any
    M33: Any
    M34: Any
    M41: Any
    M42: Any
    M43: Any
    M44: Any

class Plane:
    Normal: Any
    D: Any

class Quaternion:
    X: Any
    Y: Any
    Z: Any
    W: Any

class Rational:
    Numerator: Any
    Denominator: Any

class Vector2:
    X: Any
    Y: Any

class Vector3:
    X: Any
    Y: Any
    Z: Any

class Vector4:
    X: Any
    Y: Any
    Z: Any
    W: Any
